### ISSUE TITLE
No duplication of requirements

### ISSUE THREAD

**Issue by annevk** [w3c/mathml#102]
I think https://mathml-refresh.github.io/mathml-core/#web-platform-integration (came across this in #101) is restating requirements already stated in HTML. It would be good to not make those requirements redundantly here to avoid confusion as to what is the normative definition.

**Comment by fred-wang** [comment]
Yes, I had this concern too. Let's see how it looks like after simplification in #101 . Ideally, I would just point to the other specs and add the three specific things for MathML core:
* What are the elements in the MathML namespace
* Accept the MathML namespace as a value of SVG requiredExtensions
* The user agent stylesheet for MathML

**Comment by fred-wang** [comment]
I've cleaned up the section but I'm still waiting decision of the CG on #101

**Comment by fred-wang** [comment]
Section updated https://mathml-refresh.github.io/mathml-core/#html-and-svg
Interesting examples for MathML are mentioned as a non-normative note.
