### ISSUE TITLE
Define menclose@notation as a set of space-separated tokens

### ISSUE THREAD

**Issue by fred-wang** [w3c/mathml#104]
Definition in MathML full is:
https://mathml-refresh.github.io/mathml/chapter3.html#presm.menclose

After #21, we can now define it as "set of space-separated tokens":
https://html.spec.whatwg.org/multipage/common-microsyntaxes.html#space-separated-tokens

The proposal is to define it as a "unordered set of unique space-separated tokens" like it is done for iframe@sandbox https://html.spec.whatwg.org/multipage/iframe-embed-object.html#the-iframe-element:unordered-set-of-unique-space-separated-tokens

i.e. do not allow values like "circle circle".

**Comment by fred-wang** [comment]
WebKit and Gecko will typically treat duplicate notation values as equivalent to a single notation. This is consistent with the MathML suggestion "Each should be rendered as if the others were not present; they should not nest one inside of the other."

**Comment by davidcarlisle** [comment]
seems OK to me, and I'd suggest we make a similar change in full.

**Comment by fred-wang** [comment]
I updated the menclose desc to rely on MathML3 and here is the proposed definition: https://mathml-refresh.github.io/mathml-core/#attribute-notation ; if people disagree I can still update later.

**Comment by fred-wang** [comment]
Consensus during last meeting: we should actually relax this definition to be compatible with MathML3. This has been updated.

**Comment by fred-wang** [comment]
This seems fixed.
