### ISSUE TITLE
Fix text in spec for glyph stretching

### ISSUE THREAD

**Issue by NSoiffer** [w3c/mathml#117]
The [text for glyph stretching](https://mathml-refresh.github.io/mathml-core/#dfn-preferred-inline-size-of-a-stretchy-glyph-in-inline-direction) says to start with the glyph's _advance width_ for _both_ the inline and block directions.

For the inline direction, I'm not sure that's the proper metric. It seems like the _actual_ width is more likely correct as the advance width may not even be relevant.

For the block direction, why should a horizontal direction be used when trying to choose a size in the vertical direction? Also, there is no mention of checking the symmetric attr. This should affect the  size choice.

**Comment by fred-wang** [comment]
> For the inline direction, I'm not sure that's the proper metric. It seems like the _actual_ width is more likely correct as the advance width may not even be relevant.

Yes, I was not sure either. This need to be checked.

> For the block direction, why should a horizontal direction be used when trying to choose a size in the vertical direction?

The link you are referring is for the *preferred inline size* in both inline and block directions. This is used during calculations of min-content/max-content inline size.

> Also, there is no mention of checking the symmetric attr. This should affect the size choice.

I'm not sure about this. This section is about low-level text measuring/shaping APIs. The choice is already handled at the MathML level during vertical operator stretching when deciding the stretch ascent/descent (this is how it was defined in MathML3 and how it is implemented in Gecko and WebKit).

**Comment by NSoiffer** [comment]
Perhaps there is some confusion on my part of what you mean by "inline direction" and "block direction". I assumed they meant horizontal/vertical for left-to-right writing, but a literal interpretation would be the writing direction used for an inline/block element (which are likely the same).

I just googled "block direction" and doesn't return anything that uses that phrase, at least among the top hits. These terms are used several times in the spec. The spec either needs to define these terms or (preferably) we should find a replacement which is used in the HTML or CSS specs.

**Comment by fred-wang** [comment]
"Block" and "inline" are pretty standards, references are already given in https://mathml-refresh.github.io/mathml-core/#box-model
"direction" is used in the CSS Layout API spec. The CSS Writing mode spec seems to use it for a slightly different meaning, maybe we should use "axis" instead.

In any case, it perfectly makes sense to get the horizontal size of a vertical operator, I suspect your issue is that you are not familiar with CSS layout (here min-content/max-content calculation but I noticed another change that seemed to assume layout nodes may not be laid out). Can you please not edit the layout / CSS part of the spec? This is an aspect where we need to be very cautious as we'll ask review to CSS experts & browser vendors. Thanks.

**Comment by NSoiffer** [comment]
My point is that these terms are not defined in the CSS spec, although I see that they are used in examples 8 and 9 of the CSS spec.  "axis" is much better -- "block axis" and "inline axis" are defined terms and are therefore more appropriate to use.

The reason for adding text for this case of `visibility: hidden` was to emphasize that layout of operators can result in a change of size from their glyph's metrics and so shortcuts can't be taken when the character isn't painted. Perhaps that's obvious to you, but operators are special in that sense and may not be obvious to implementers less familiar with math. I'm ok with not including it, but I felt it could be helpful to state.

**Comment by fred-wang** [comment]
> > For the inline direction, I'm not sure that's the proper metric. It seems like the _actual_ width is more likely correct as the advance width may not even be relevant.
> 
> Yes, I was not sure either. This need to be checked.

I opened https://github.com/mathml-refresh/mathml/issues/199 for this.

> > For the block direction, why should a horizontal direction be used when trying to choose a size in the vertical direction?
> 
> The link you are referring is for the _preferred inline size_ in both inline and block directions. This is used during calculations of min-content/max-content inline size.

I replied to this, the algorithm to calculate preferred inline size is for operators stretching along the block axis. And you really want to take the max of the width. So this is correct.

> > Also, there is no mention of checking the symmetric attr. This should affect the size choice.
> 
> I'm not sure about this. This section is about low-level text measuring/shaping APIs. The choice is already handled at the MathML level during vertical operator stretching when deciding the stretch ascent/descent (this is how it was defined in MathML3 and how it is implemented in Gecko and WebKit).

Handling of symmetric attribute is described in the mo section as that's MathML, not the low-level API. When symmetric = true, the target size is adjusted but the low-level API does not need to know about it.
