### ISSUE TITLE
Can semantics be space-like?

### ISSUE THREAD

**Issue by fred-wang** [w3c/mathml#121]
MathML Full defines semantics/maction to be embellished operator if there visible child is and embellished operator:
https://mathml-refresh.github.io/mathml/#exception-for-embellished-operators

Similarly maction can be space-like if its visible child is space-like, but that's not the case for semantics:
https://mathml-refresh.github.io/mathml/#definition-of-space-like-elements

Any rationale for that?

**Comment by davidcarlisle** [comment]
I am fairly sure that is oversight and that the answer should be yes, basically semantics should act as far as possible like its first child if you are not using the annotations

**Comment by NSoiffer** [comment]
That's a good catch. I agree it was an oversight and `semantics` was accidentally left out of space-like elements. In addition to embellished operators, the semantics/maction parity is part of the (rarely implemented) `maligngroup` definition.

I did a quick search of the rest of the spec and didn't find any other cases where one or the other was left out.

**Comment by NSoiffer** [comment]
On the call today, Sam Dooley also agreed this seemed to be an oversight.

**Comment by NSoiffer** [comment]
Added to full spec (https://github.com/mathml-refresh/mathml/commit/38c24705c5e890ac2a9338dbd6b8403a18f8338e).

**Comment by fred-wang** [comment]
Core spec updated too.

**Comment by fred-wang** [comment]
This is tested at least by https://w3c-test.org/mathml/presentation-markup/spaces/space-like-002.html so closing.
