### ISSUE TITLE
Remove xlink:href

### ISSUE THREAD

**Issue by fred-wang** [w3c/mathml#127]
cc @emilio 

In #5 we decided to remove deprecated MathML 3 attributes from MathML Core. However xlink:href is a bit special  because it belongs to a different namespace. This is the text from https://www.w3.org/TR/MathML3/chapter2.html#fund.globatt:

"Note that MathML 2 had no direct support for linking, and instead followed the W3C Recommendation "XML Linking Language" [XLink] in defining links using the xlink:href attribute. This has changed, and MathML 3 now uses an href attribute. However, particular compound document formats may specify the use of XML linking with MathML elements, so user agents that support XML linking should continue to support the use of the xlink:href attribute with MathML 3 as well. "

Firefox has been sending deprecation for xlink:href on MathML elements for 7 years: https://bugzilla.mozilla.org/show_bug.cgi?id=553917 ; AFAIK, WebKit does not support on xlink:href on MathML elements. Igalia does not plan to implement it in Chromium either. Currently the MathML Core does not mention anything about xlink:href.

SVG 2 is also moving to a non-prefix href: https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/xlink:href

I'm opening this to decide what to do for MathML Core / MathML 4. I think it makes sense to remove support for this from Gecko.

**Comment by 1jj** [comment]
Two random opinions about this:

1. Assuming there is (a lot ?) of old content outside (e.g. https://bugzilla.mozilla.org/show_bug.cgi?id=427990#c42), removing support of `xlink:href` it not worth the trouble.
2. `xlink:href` is supported in SVG content anlong wirh `href` (no plans to remove). It should be supported for MATHML too, just to be consistent.

**Comment by NSoiffer** [comment]
If we want to follow how SVG handles this, here's what the [SVG spec](https://www.w3.org/TR/SVG2/linking.html#XLinkRefAttrs) says:

> For backwards compatibility, elements with an ‘href’ attribute also recognize an ‘href’ attribute in the XLink namespace [xlink].
> 
> When the ‘href’ attribute is present in both the XLink namespace and without a namespace, the value of the attribute without a namespace shall be used. The attribute in the XLink namespace shall be ignored.
> 
> A conforming SVG generator must generate ‘href’ attributes without a namespace. However, it may also generate ‘href’ attributes in the XLink namespace to provide backwards compatibility.
> 
> This attribute is Animatable if and only if the corresponding ‘href’ attribute is defined to be animatable.

MathML and SVG have similar views on what to do with deprecated features. MathML has deprecated xlink longer than SVG, so maybe SVG's handling of this feature not relevant for a MathML 4. I'm still in favor of removing it (especially from core), but as per the definition of deprecated, it is still legal (and preferable for backward compatibility) to support it. If it is work, then I don't see the point though given all the other things we have removed from core that aren't deprecated.

**Comment by NSoiffer** [comment]
Since it was deprecated in MathML 3, there is no reason for it to be in core. Plus it introduces the problems with links being everywhere. The 24/2/202 meeting resolved that we should pull this.
