### ISSUE TITLE
tabIndex attribute

### ISSUE THREAD

**Issue by fred-wang** [w3c/mathml#131]
See w3c/mathml#118 and w3c/mathml-core#129 

We need to clearly define how the tabIndex attribute behave, giving the default value, taking into account MathML links (elements with the href attribute) etc

We also need more tests for that as we only have one basic test. More tests were added in https://bugs.webkit.org/show_bug.cgi?id=200470 but they are internal to WebKit. They also don't seem to consider interactions with MathML links.

**Comment by fred-wang** [comment]
I believe https://web-platform-tests.org/writing-tests/testdriver.html should be enough to write UI tests for tabIndex similar to WebKit's internal ones.

**Comment by NSoiffer** [comment]
The [HTML 5.1 spec](https://www.w3.org/TR/2016/REC-html51-20161101/editing.html#the-tabindex-attribute) says the default value is a user agent decision when it is not specifically given
> When the attribute is omitted, the user agent applies defaults

We can of course make a suggetion that all elements with `href` should have `tabindex=0`.

**Comment by fred-wang** [comment]
Brian added https://mathml-refresh.github.io/mathml-core/#focus
and there are now some tests
https://w3c-test.org/mathml/relations/html5-tree/tabindex-001.html
https://w3c-test.org/mathml/relations/html5-tree/tabindex-002.html

**Comment by fred-wang** [comment]
I think this is essentially fixed by https://github.com/mathml-refresh/mathml-core/commit/c2d770cf1b5cef4c75256bb3386697a9f8f9af06 where we now defer the semantic to HTML.

With this plus my previous comment, I think we can close this issue.
