### ISSUE TITLE
Handling of invalid values in menclose notation

### ISSUE THREAD

**Issue by fred-wang** [w3c/mathml#144]
See https://mathml-refresh.github.io/mathml-core/#enclose-expression-inside-notation-menclose

After #104 notation is defined as an unordered set of unique space-separated tokens ; additionally #3 "radical" was removed. The allowed values as "left, right, top, bottom, box, roundedbox, actuarial, madruwb, horizontalstrike, verticalstrike updiagonalstrike, downdiagonalstrike, longdiv, circle.". It think the core spec lacks the usual "If the attribute is absent or has an invalid value,  the default 'longiv' value is used"

In MathML3, the notation values are open-ended so an unknown or duplicate values are just ignored. In particular notation="" or notation="invalid" is equivalent to draw nothing and notation="circle circle" to draw an ellipse.

With the current MathML Core text (amended as above), an unknown value or duplicate value will make the attribute invalid and so the 'longdiv' will be used. Hence notation="", notation="invalid", notation="radical" or notation="circle circle" are all equivalent to "longdiv".

I think these are all edge cases, but I just want to be sure that this is what we want.

**Comment by davidcarlisle** [comment]
making it a fixed list (so unexpected entries invalid) is fine with me. The one odd part of your description is that `<menclose>` with no valid notation attribute acts as `longdiv` .

 `box` would I think be a more natural default.

I know that's what we said the default was in mathml3 but looking at it now it seems like a strange choice.

I'd be tempted to change the default (in full as well) but if others think that compatibility concerns mean we should stay with longdiv, I wouldn't argue too much.

**Comment by fred-wang** [comment]
I don't really have preference about the default, but I would say let's keep longdiv for backward compatibility.

My main concern is that things like notation="", notation="invalid", notation="radical" or notation="circle circle" are now treated as the default while I think in MathML3 they were treated as "no notations drawn" (for the first three) or "circle" (for the fourth one). If people want to preserve the MathML3 behavior, I think the core spec would need to be tweaked a bit.

**Comment by fred-wang** [comment]
I updated the spec as agreed during yesterday's meeting, basically keeping backward compat with MathML3

**Comment by fred-wang** [comment]
I added tests for notation="" or notation="radical"  since that's needed for Gecko.

I'm closing this issue as I don't think we need it to track more tests... I think this is handled by #105 ; we would need to write a complete test suite for menclose if we decide to keep it.
