### ISSUE TITLE
math-script-level - specified value always exists, so font-size interaction needs fixing

### ISSUE THREAD

**Issue by fantasai** [w3c/mathml#155]
>If font-size is specified or if the specified value of math-script-level is initial then math-script-level does not affect the computed value of font-size. Otherwise, the computed value of font-size is obtained by multiplying the inherited value of font-size by a nonzero scale factor calculated by the following procedure: 

"Is specified" isn't a thing we can check, really. There's always a specified value... Probably this should say "If there is a cascaded value for `font-size`..."

**Comment by fantasai** [comment]
https://www.w3.org/TR/css-cascade-3/#value-stages

**Comment by fred-wang** [comment]
After the change to https://github.com/mathml-refresh/mathml/issues/174 the text no longer says "is specified".
