### ISSUE TITLE
MathML Core explainer: Reword caption for Figure 5

### ISSUE THREAD

**Issue by fred-wang** [w3c/mathml#156]
cc @NSoiffer @bkardell 

"Figure 5: LaTeX source in a custom element and its shadow MathML rendered with the Latin Modern Math font ; From top to bottom: Blink (Igalia's build), WebKit (r249360) and Gecko (Firefox 68)"

Neil mentioned "shadow MathML" is not really clear.

**Comment by fred-wang** [comment]
I think this is done too?

**Comment by NSoiffer** [comment]
From 9/12/19 meeting, agreed to close.
