### ISSUE TITLE
Core explainer: suggested changes

### ISSUE THREAD

**Issue by NSoiffer** [w3c/mathml#158]
## Some suggested changes

- the phrase "consistently with" is used repeatedly. You probably mean "consistent with"

>   Effort is made to keep backward compatibility for existing MathML3 content.

That's an awkward sentence. Suggest rewrite to "Backward compatibility for existing MathML3 content is highly desirable."

> Complete and explicit description of semantics which are better described by extending ARIA. 

I was recently reminded by some ARIA folks that using ARIA's 'role' attr is only appropriate when you can map it to a lower level accessibility API, which we can't. It is not clear at all that extending ARIA will be the appropriate solution. Hence, I think this line should be removed.

I found the sublists in non-goal section "To provide a self-contained solution to problems" a little confusing. These are in the "this is not a goal" section. But the sentence before the sublist says to use Web Platform technologies as much as possible. The sublist is "examples include". This list of examples is back to things not to do, but the bullets end with "which are better described by..." or similar text. So we have gone from non-goal to alternative to non-labeled list of items that start one way and end another. Maybe others don't have a problem with this, but I had to stop on each one and remind myself whether the point was something that is good or bad.

> "LaTeX source in a custom element and its shadow MathML rendered "

Since you don't show the shadow MathML, this is better phrased as "LaTeX source in a custom element rendered using MathML in a shadow DOM".

**Comment by fred-wang** [comment]
> > "LaTeX source in a custom element and its shadow MathML rendered "
> 
> Since you don't show the shadow MathML, this is better phrased as "LaTeX source in a custom element rendered using MathML in a shadow DOM".

This is #156

**Comment by fred-wang** [comment]
cc @bkardell

**Comment by fred-wang** [comment]
> > Complete and explicit description of semantics which are better described by extending ARIA.
> 
> I was recently reminded by some ARIA folks that using ARIA's 'role' attr is only appropriate when you can map it to a lower level accessibility API, which we can't. It is not clear at all that extending ARIA will be the appropriate solution. Hence, I think this line should be removed.

cc @joanmarie

I don't know what's the plan for making MathML accessible, but I don't think MathML Core should specify "Complete and explicit description of semantics" anyway. So I still think we should explain where else in the web platform this should be handled, assuming that's actually desirable.

**Comment by fred-wang** [comment]
> > > "LaTeX source in a custom element and its shadow MathML rendered "
> > 
> > 
> > Since you don't show the shadow MathML, this is better phrased as "LaTeX source in a custom element rendered using MathML in a shadow DOM".
> 
> This is #156

Done. I'll let @bkardell handle the rest of the suggestion.

**Comment by joanmarie** [comment]
> > Complete and explicit description of semantics which are better described by extending ARIA.
> 
> I was recently reminded by some ARIA folks that using ARIA's 'role' attr is only appropriate when you can map it to a lower level accessibility API, which we can't. It is not clear at all that extending ARIA will be the appropriate solution. Hence, I think this line should be removed.

ARIA has roles, states, and properties. Adding a ton of new roles for non-roley semantics is probably not going to fly. However, adding new properties in some cases might indeed prove to be the way to go.

That said, your explainer is yours. :slightly_smiling_face:

**Comment by fred-wang** [comment]
@bkardell ping?

**Comment by bkardell** [comment]
I think the explainer is in pretty good shape and has been read by most of the people who will be reading it at that level at this point - let's close this.
