### ISSUE TITLE
Change definition of space-like maction and semantics

### ISSUE THREAD

**Issue by fred-wang** [w3c/mathml#160]
Defintion https://mathml-refresh.github.io/mathml-core/#dfn-space-like has the following:

- Or an unknown MathML element, `<mrow>`, `<mstyle>`, `<mphantom>` or `<mpadded>` all of whose in-flow children are space-like;
- An `<maction>` or `<semantics>` element whose first in-flow child exists and is space-like. 

Test: mathml/presentation-markup/spaces/space-like-002.html

When trying to make maction/semantics behave as mrow in https://bugzilla.mozilla.org/show_bug.cgi?id=1588733 ; this test now fails.

Proposal: merge these two items:

- Or an unknown MathML element, `<mrow>`, `<maction>`, `<semantics>`, `<mstyle>`, `<mphantom>` or `<mpadded>` all of whose in-flow children are space-like;

Since normally non-visible maction/semantics children are displayed "none", they are effectively out-of-flow and the MathML3 logic is preserved.

**Comment by davidcarlisle** [comment]
This seems reasonable to me

**Comment by fred-wang** [comment]
Consensus from 2019/11/11: Handle maction/semantics the same as other mrow-like ("whose in-flow children are space-like" instead of "whose first in-flow child exists and is space-like")

**Comment by NSoiffer** [comment]
@fred-wang: can this be closed due to #182 and #183?

**Comment by fred-wang** [comment]
Tests updated for the new definition https://github.com/web-platform-tests/wpt/pull/21568 (we could add more tests for semantics/maction with more than one child, but I guess that's enough for now).
