### ISSUE TITLE
Add  "Security Considerations" and "Privacy Considerations" 

### ISSUE THREAD

**Issue by bkardell** [w3c/mathml#162]
W3C TAG review generally asks the question if we have sections in our spec about this.

**Comment by fred-wang** [comment]
@bkardell I added something in https://mathml-refresh.github.io/mathml-core/#privacy-and-security-considerations

**Comment by fred-wang** [comment]
@bkardell "Can the Issue 162 Privacy and Security Considerations" label be removed and this issue closed? Or do you need more?

**Comment by fred-wang** [comment]
Brian confirmed we can close this.
