### ISSUE TITLE
Description of movablelimits should take math-style into account

### ISSUE THREAD

**Issue by fred-wang** [w3c/mathml#165]
"If the base is an embellished operator with the movablelimits property then the underscript and overscript are actually drawn as subscript and superscript positions."

It should say and "AND the math-style property on the munder/mover/munderover element is inline".

Actually MathML3 says

> If base is an operator with movablelimits="true" (or an embellished operator whose mo element core has movablelimits="true"), and displaystyle="false"

but it is not really clear whether the displaystyle comes from the element or from its base. This does not make any difference for MathML3 since displaystyle can only be specified on math/mstyle.

We should have tests for this. Gecko reads the math-style from the munder/mover/munderover while WebKit and Igalia's Chromium implementation check the math-style on the core operator instead.

**Comment by NSoiffer** [comment]
MathML 3 spec specifically mentions the `mo` for the first part but not the second; `displaystyle="false"` applies to the value in effect for mover/munder/munderover. Gecko's implementation matches the MathML 3 spec.

As you point out, MathML 3 and core allow setting `displaystyle` on `mstyle`, so this distinction does make a difference in MathML 3 and  in core.

Given the difference in the implementations, this is definitely something worthy of a test.

**Comment by fred-wang** [comment]
Consensus from 2019/11/11: consider the math-style value on the munder/mover/munderover element.

**Comment by fred-wang** [comment]
test added, so closing

**Comment by fred-wang** [comment]
> This does not make any difference for MathML3 since displaystyle can only be specified on math/mstyle.

I stand corrected here, this can be tested in MathML3 using an embellished op:

    `<math><munder><mstyle displaystyle="true"><mo movablelimits="true">1</mo></mstyle><mn>2</mn></math>`

Anyway, Gecko was already implementing what is in MathML Core, the same was implemented in Chromium and I fixed WebKit's yesterday while adding support for math-style ; so all browsers should behave the same now.
