### ISSUE TITLE
respec editors / former editors / authors

### ISSUE THREAD

**Issue by fred-wang** [w3c/mathml#168]
See
https://github.com/w3c/respec/wiki/editors
https://github.com/w3c/respec/wiki/authors
https://github.com/w3c/respec/wiki/formerEditors
https://github.com/w3c/respec/wiki/ReSpec-Editor's-Guide#editors--authors-and-former-editorsauthors

@davidcarlisle pointed out to me that we never really decided about these. Currently, we have:

Editors:
    David Carlisle (NAG) 
    Frédéric Wang (Igalia)

MathML Core (as a markup) is based on MathML 3 but in practice I've rewritten most of the text of the spec from scratch so it only remains introductory paragraph copied from MathML 3. I removed most of the XML/RelaxNG setup and plan to rewrite how the dictionary is presented too. IIRC, the other people who contributed to the text are Neil, Brian and Rob.

IIUC, the Math WG made the choide of having David (XML tools) + the chairs as editors and the rest of people were listed as authors. I wonder if we should organize things better for the core spec, as fantasai explained in https://www.youtube.com/watch?v=rdSSvyXkeK0

Whatever we decide, I think it's good to put David, Patrick and Robert as "former editors" to keep some kind of continuity with MathML3 and I'm a de facto an "editor".

**Comment by davidcarlisle** [comment]
@fred-wang  already knows this, but for the public record I have no objection to being de-listed as editor (having suggested it myself:-).  I think listing the mathml3 editors as former editors is good too.

**Comment by NSoiffer** [comment]
I agree.

Note that some specs (e.g., [CSS Selectors Level 3](https://www.w3.org/TR/selectors-3/)) say "name (former editor, affiliation)", so that is definitely done. [Others ](https://www.w3.org/TR/css-color-3/)list both editors and a few "additional authors". So that's a possibility also.

**Comment by fred-wang** [comment]
Agreement from November 25: Keep David & Fred as editors, add former editors from MathML3, add an acknowledments section.

**Comment by fred-wang** [comment]
I added former editors and acknowledgements section. Probably I missed some people, or the affiliation is wrong etc feel free to ask if you want any change.

**Comment by fred-wang** [comment]
https://mathml-refresh.github.io/mathml-core/#acknowledgments

**Comment by fred-wang** [comment]
For the record, this was inspired from https://www.w3.org/TR/CSS21/about.html#acknowledgements ; I moved this to the end as @bkardell pointed out it is how it is done in CSS3 specs.

**Comment by NSoiffer** [comment]
Can this be closed?

**Comment by fred-wang** [comment]
Yes, nobody commented further on this so it seems they are ok with the current text. More acknowledgments can be added later if needed.
