### ISSUE TITLE
Change definition of embellished / core operator for maction and semantics

### ISSUE THREAD

**Issue by fred-wang** [w3c/mathml#182]
This is similar to #160 

Currently, the definitions refers to the "first in-flow child".

In general maction and semantics just have a single in-flow child so we can just use the same definitions as mrow-like and unknown elements. In particular that will allow to handle consistently maction, semantics, mrow, mstyle, mphantom, mpadded and unknown MathML elements and simplify implementations.

**Comment by fred-wang** [comment]
Consensus from 2020/01/21: approved.

**Comment by NSoiffer** [comment]
@fred-wang: can this be closed? If not, what's left to do?

**Comment by fred-wang** [comment]
> @fred-wang: can this be closed? If not, what's left to do?

We still need to update tests for embellished op. Doing it in https://github.com/web-platform-tests/wpt/pull/22381
