### ISSUE TITLE
Add more definitions

### ISSUE THREAD

**Issue by NSoiffer** [w3c/mathml#186]
The core spec uses a number of terms from HTML and CSS. It also uses some things that aren't probably fully defined. We should have references and/or definitions for them. Note that some CSS specs have a [glossary ](https://www.w3.org/TR/css-display-3/#glossary) and some (most?) have [an index linking to where terms are defined](https://www.w3.org/TR/css-inline-3/#index-defined-here).

Some values to define (please edit to add more):
- inflow
- block/inline
- token
- line ascent/decent

**Comment by fred-wang** [comment]
block/inline and line-ascent/descent are here but probably need internal links: https://mathml-refresh.github.io/mathml-core/#box-model
in-flow should have external and internal links.

I want to add definition of token elements in https://mathml-refresh.github.io/mathml-core/#mathml-elements and add internal links to it.

**Comment by fred-wang** [comment]
I did a first pass for "block size", "inline size", "min-content inline size" and "max-content inline size" which are used everywhere in the layout algo.

We also need to add link to "margin box".

**Comment by fred-wang** [comment]
closing this many definitions have been added. better to open separate issues if there are still some missing.
