### ISSUE TITLE
SubShift calculation doesn't seem to be right

### ISSUE THREAD

**Issue by faceless2** [w3c/mathml#190]
The algorithm in https://mathml-refresh.github.io/mathml-core/#base-with-subscript states:

> SubShift is the maximum between:
> * SubscriptShiftDown
> * SubscriptTopMax + the ink line-ascent of the subscript's margin box
> * SubscriptBaselineDropMin + the ink line-descent of the base's margin box
> 

The second bullet point doesn't seem to match either TeX rule 18b or the code in Gecko (https://github.com/mozilla/gecko-dev/blob/master/layout/mathml/nsMathMLmmultiscriptsFrame.cpp, line 428)

Should this instead be "the ink line-ascent of the subscript's margin box - SubscriptTopMax"?

**Comment by fred-wang** [comment]
Thanks. Yes I think you're right. WebKit and Chromium do the same. I'll check again and fix later.

**Comment by fred-wang** [comment]
@faceless2 this should be fixed now. Thank you again for the report!
