### ISSUE TITLE
User-agent stylesheet incomplete

### ISSUE THREAD

**Issue by faceless2** [w3c/mathml#193]
MathML core Section [3.2.2](https://mathml-refresh.github.io/mathml-core/#identifier-mi) states the following rule is required in the user-agent styleshet
```css
mi {
  text-transform: math-auto;
}
```

but that rule is not part of the  stylesheet at https://mathml-refresh.github.io/mathml-core/#user-agent-stylesheet

I'm pretty sure this is the only one missing.

**Comment by fred-wang** [comment]
Thanks for the report @faceless2 ; yes that seems a mistake.

**Comment by fred-wang** [comment]
@faceless2 Fixed. Thank you again for point that out.
