### ISSUE TITLE
negative linethickness

### ISSUE THREAD

**Issue by fred-wang** [w3c/mathml#195]
The test

https://w3c-test.org/mathml/presentation-markup/fractions/frac-linethickness-002.html

checks that < 0 linethickness are treated as 0

This is consistent with MathML 3: "In some cases, the range of acceptable values for a particular attribute may be restricted; implementations are free to round up or down to the closest allowable value."

Core spec has:

"The linethickness attribute indicates the fraction line thickness to use for the fraction bar. If present, it must have a value that is a valid length-percentage. If the attribute is absent or has an invalid value, FractionRuleThickness is used as the default value. A percentage is interpreted relative to that default value."

I think we should add negative values are interpreted as 0

**Comment by davidcarlisle** [comment]
> I think we should add negative values are interpreted as 0

I think that makes sense. 

For what it's worth TeX, if given negative dimensions, doesn't render the rule but still uses the negative value in the fine print from appendix G, but as the negative spacing is almost completely over-written by the automatic kerns added to keep things positioned on the math axis the effect is very slight and not really useful or document-able.  The image here is with luatex using Cambria Math OpenType font.  Note that 6/x (given 0pt rule width) ends up having a slightly  different  separation than specifying -2pt or -10pt  but not by any useful or simply understandable formula.

![image](https://user-images.githubusercontent.com/1268738/76507694-2127d100-6445-11ea-93b5-6fdbbdc4d1b1.png)


```

\ifx\directlua\undefined\else
\input{luaotfload.sty}
\font\cambriamath="Cambria Math"
\font\cambriamaths="Cambria Math" at 7pt
\font\cambriamathss="Cambria Math" at 6pt
\fi


$
{1 \over x}
{2 \above 2pt x}
{3 \above 10pt x}
{4 \above -2pt x}
{5 \above -10pt x}
{6 \above 0pt x}
$

\bye
```

**Comment by fred-wang** [comment]
consensus from 2020/03/23: clamp to zero.
It's how it is implemented in browsers and it's tested by  frac-linethickness-002.html
I'll just update the spec.
