### ISSUE TITLE
Review global attributes of HTML and SVG for parity

### ISSUE THREAD

**Issue by bkardell** [w3c/mathml#207]
It seems that somehow we didn't spec that MathML's global attributes should support title when we did #118. It seems worth a careful review for parity here to see if/what we are missing and if we have reason to exclude that or not.  Helpful to everyone if we cross-reference the same parity check for SVG so that if they leave something off, we can also see if that has history or rationale or is also just a miss.  

Will catalog, see if we have tests, etc for how to move forward.

**Comment by bkardell** [comment]
I looked into this and it seems we do actually have good parity with SVG at this point in terms of what we support and don't here and we should probably just close and resolve to pursue increased alignment of SVG/MathML generally in the platform.  Things get what we more generally think of as the "global attributes" (https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes) from a lot of different interfaces and mixins.  Some of these make a lot more sense than others and wind up being in `Element` itself (or something that `Element` mixes in like `ARIAMixin` - we get those) and some wind up being in `HTMLOrSVG` (aka HTMLOrForeignElement) etc... Our definitions pretty much match SVG which include pretty much the core set that people use or expect to work and none of the ones that aren't definitely universal.  It seems that `title` was an interesting one here because it definitely _feels_ to me like it should work, but at the current time neither SVG nor MathML (at least not that I see) define a title attribute (SVG has a title _element_).    If we resolve as I suggested above, we could pursue whether it makes sense to add title or not together, it doesn't seem like SVG folks are necessarily opposed to adding it to the common mixin, but I don't think we should expand the scope if we can avoid it.  The big implication here, i guess is mostly that it will not reflect for now as shown in https://software.hixie.ch/utilities/js/live-dom-viewer/?saved=8667 - but it will do that similarly in both.

**Comment by AmeliaBR** [comment]
Relevant SVG discussion is here: https://github.com/w3c/svgwg/issues/395

So far, harmonizing with HTML global attributes (or DOM methods) has been done on a case-by-case basis, based on demand. In general, my policy is to support harmonization for implementation simplicity and author convenience. With `title`, though, there is the added complication of how it interacts with the SVG `<title>` element & therefore with accessible name calculations — so it's not going to be quite as simple.

**Comment by NSoiffer** [comment]
Closing based on @bkardell's investigation and @AmeliaBR's follow-up that there are complications due to SVG's title element. This can always be reconsidered for level 2, but there doesn't seem to anyone pushing for it to be in level 1
