### ISSUE TITLE
various nits

### ISSUE THREAD

**Issue by bkardell** [w3c/mathml#226]
1. https://mathml-refresh.github.io/mathml-core/#legacy-mathml-style-attributes  
  
The last paragraph says  
  
> The mathcolor property describes the foreground fill color of an MathML text, bars etc and the background color of an element.

I believe this intends to say 

> The mathcolor property describes the foreground fill color of an MathML text, bars etc, while the mathbackground color describes the background color of an element.
    
2. https://mathml-refresh.github.io/mathml-core/#the-math-style-property

The example prose confused left and right/former and later with the actual example - it identifies normal as compact and vice versa.  This is less of a nit and actually a pretty seriously confusing error.
 

3. https://mathml-refresh.github.io/mathml-core/#the-math-shift

Current text says
> Page authors or developers of polyfill may also benefit...

Should say 

> Page authors or developers of polyfills may also benefit...
> 
(missing s in polyfills)

**Comment by fred-wang** [comment]
@bkardell can you please send a PR?

**Comment by fred-wang** [comment]
This was not mentioned here, but brian also suggested to improve the color of an example, to improve readability. This has been done.
