### ISSUE TITLE
Align definition of numbers with CSS

### ISSUE THREAD

**Issue by fred-wang** [w3c/mathml#23]
"The definition of numbers is also not very accurate in the MathML
recommendation compared to HTML5. One has to check the RelaxNG schemas
and the predefined RelaxNG types to know the exact syntax. Again, it
think it would be best to rely on the HTML5 definitions. For example,
`<math><mspace width="1E1em" height="10em" mathbackground="red"/></math>`
draws a red square in WebKit but Gecko says "1E1em" is invalid.

   https://www.w3.org/TR/html5/infrastructure.html#numbers"

original report: https://lists.w3.org/Archives/Public/www-math/2016Aug/0000.html

**Comment by NSoiffer** [comment]
I agree that MathML should align it's number parsing with HTML5. Looking at the referenced HTML spec, it appears that attributes can only be pos/neg decimal integers/floating point numbers. They can't be hex or octal except in colors. In looking at the [MathML spec itself](https://www.w3.org/TR/MathML3/chapter2.html#fund.attval), it doesn't seem to allow hex digits anywhere except in colors (search for "hexadecimal"), so it seems like they are in alignment in at least intent. The RelaxNG schema might be off.

I'm pretty sure that MathML 3 made an attempt to align its basic syntax parsing with HTML5. Of course, it might not have been perfect in doing so.

**Comment by fred-wang** [comment]
The definitions are given here ; I think it corresponds to the RelaxNG schema.
https://mathml-refresh.github.io/mathml/chapter2.html#id.2.1.5.1

In particular for "number":
> an optional prefix of "-" (U+002D), followed by an unsigned number, representing a terminating decimal number (a type of rational number)

Not that this does not allow values like `1.3139E2`.

I reopened this since we need to update the specs/relaxng schema and write WPT tests for this.

cc @bkardell

**Comment by fred-wang** [comment]
See https://lists.w3.org/Archives/Public/public-mathml4/2019May/0006.html
I don't have the minutes from this week.

Keeping "need resolution" for now. I think we agreed someone should go over the list of number attributes and check carefully.

**Comment by fred-wang** [comment]
"fw: Numbers like "5." is allowed in MathML currently, but not in CSS. Can
we align? Resolved to align. Since the values are parsed by CSS, we should
follow the CSS spec (as opposed to HTML)"

**Comment by fred-wang** [comment]
Consensus was to follow CSS.

**Comment by fred-wang** [comment]
Core spec now relies on
- non-negative-integer value as defined in [HTML5] 
- length-percentage value as defined in [CSS-VALUES-4]

But some attributes still refer to MathML3

**Comment by fred-wang** [comment]
We have tests for that, so closing.
