### ISSUE TITLE
move codepoints to a registry?

### ISSUE THREAD

**Issue by samuelweiler** [w3c/mathml#238]
the long lists of codepoints in -core look like they should be in a registry (e.g. at IANA) where they can be more readily updated.

**Comment by davidcarlisle** [comment]
As I commented at the charter issue, I don't think a registry is suitable here as the code points lists are as specified by Unicode for the  math Alphabets so they can't be changed here or in a separate registry,

**Comment by NSoiffer** [comment]
Closing because I feel @davidcarlisle's points are correct and there has been no further discussion in six months.
