### ISSUE TITLE
Remove support for nonzero unitless values for MathML lengths

### ISSUE THREAD

**Issue by fred-wang** [w3c/mathml#24]
From https://mathml-refresh.github.io/mathml/chapter2.html#fund.units

"A number without a unit is intepreted as a multiple of the reference value. This form is primarily for backward compatibility and should be avoided, prefering explicit units for clarity. "

Converting unitless to percentage adds some complexity to the code. Moreover it is not very intuitive for users except maybe "0". I wonder if we can somewhat simplify this now.  

cc @rwlbuis

**Comment by physikerwelt** [comment]
discussed in the telco on 2019-02-25:
* consensus here?

**Comment by fred-wang** [comment]
cc @rwlbuis, @emilio

I removed the reference to nonzero unitless values https://github.com/mathml-refresh/mathml-core/commit/6e821b2c9c83de22a3f734465aaf639b5d743b76 ; @davidcarlisle can you please check whether the RelaxNG change is correct? 

I'm leaving this open because it still remains to:

* [ ]  Remove WPT tests if any (probably convert them to check "0"). 
* [ ] Send intent-to-remove to mozilla/webkit-dev mailing lists (maybe old Math WG too?).
* [ ]  Remove browser implementation.
* [ ] Decide what to do for the full MathML spec (they are already deprecated, should we remove them?)
* [ ] Add polyfill to https://github.com/mathml-refresh/mathml-polyfills (e.g. convert nonzero "NUMBER" lengths to (NUMBER/100)%").

Also, despite that "0" has a unique interpretation we might maybe be more explicit about how it is interpreted. CSS suggests it is interpreted as a number (https://drafts.csswg.org/css-values-3/#lengths) so it should be relative ("0%") per the old unitless intepretation. However, an absolute value (e.g. "0px") might be better for implementation since we don't need to bother with the default values. In any case this is an implementation details, it shouldn't affect the result.

**Comment by fred-wang** [comment]
Consensus from https://lists.w3.org/Archives/Public/public-mathml4/2019Mar/0026.html is to deprecate from MathML full.

**Comment by fred-wang** [comment]
Core spec now uses `<length-percentage>` from CSS which does not allow nonzero unitless values.

**Comment by fred-wang** [comment]
This is tested by https://w3c-test.org/mathml/relations/css-styling/lengths-1.html
The rest of the work is about native/polyfill implementation updates, so we can close this.
