### ISSUE TITLE
move discussion of xref

### ISSUE THREAD

**Issue by NSoiffer** [w3c/mathml#250]
Some old timers might remember debate about xlink. It's not part of HTML 5 and was pulled from MathML 3. Parallel markup sort of makes use of it because it uses 'xref'. There is a brief mention of 'xref' in https://www.w3.org/TR/MathML3/chapter2.html#fund.globatt. But it is grouped among HTML attrs, which it is not. Given that it is not standard, it really should be pulled out into its own section and described in more detail, perhaps after the paragraph that mentions xlink is no longer used in MathML 3.

**Comment by davidcarlisle** [comment]
I'm not sure I undersand the implied relationship to xlink here, xref isn't an xlink attribute?

currently the global atributes table is a copy of mathml3 version (apart from core yes/no marking) so it has xref and href which are not in html (or core)

I'd like to refactor the global attributes table here (and the tables of atributes common to presentation mathml) into core and non core  so that would rearrange the chapter2 global attributes table a bit. but I'd probably still leave xref it as a brief table entry there, we could describe xref in more detail in chapter 5 (after the refactor chapter 5 PR is settled)

**Comment by dginev** [comment]
Maybe a good place to sneak in a remark that SVG is using the simple `href` to point to internal SVG nodes for cross-referencing purposes, as in the [`<use>` element](https://developer.mozilla.org/en-US/docs/Web/SVG/Element/use).

They have a note that they've explicitly moved away from `xlink:href`, towards more HTML compatibility. 

So if `xref` is now out of fashion... one could wonder.

**Comment by brucemiller** [comment]
Right, but one has to wonder what kind of compatibility that is.
As near as I can understand, it's a completely different kind of 
"reference" from what href usually means in HTML, more a copy or 
substitution.

Not to open a can'o'worms here, but one can easily imagine wanting to 
have, say, an `mi` with both an href referencing a csymbol in parallel 
content, as well as an href referencing a page on wikipedia.

**Comment by dginev** [comment]
I think expanding+refreshing that line of considerations is exactly what would be needed for a "more detailed discussion of xref", so this is very much on topic for this github issue - thanks @brucemiller !

**Comment by davidcarlisle** [comment]
yes certainly xref was never intended to make an active link in the sense of  an html `<a href` 

we have `href` for that (inspired in part by xhtml2) but that's not ended up being as compatible with the rest of the web as one might have hoped.

I think for this iteration mathml4 full needs to keep both essentially as they are, but come back to this in mathml.next when/if we get some subset of the href functionaliy into mathml core level 2, to see if we can better align full with that.

The description of href (which I guess should be mostly in the  world interactions chapter (6.4.4. linking section currently) needs to say something about href not being in core but that you can embed html a/href (or use javascript or ...)

**Comment by davidcarlisle** [comment]
As it stands now,  `xref` is introduced in the table of global atributes

https://w3c.github.io/mathml/#fund_globatt

and further described under binding operators and semantics where it's used

https://w3c.github.io/mathml/#contm_bvar_sec

https://w3c.github.io/mathml/#mixing_cr


It is more or less just coincidence that all the other attributes in the global attribute table share names with HTML attributes. We could make a table of "attributes shared with HTML"  and then have a separate one-attribute section describing xref, but I don't think that would gain anything.

I don't see any connection to xlink here: `xref` isn't affected by xlink being in or out of MathML. It isn't for making hyperlinks it's a semantic association, more like HTML `label/@for` which similarly takes a value being an `id` specified elsewhere in-document
https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/for

I suggest we close this with no action. @NSoiffer  it's your issue, any objections to closing?

**Comment by NSoiffer** [comment]
Ok. It does say it is an HTML attr, so I agree we leave it as is.
