### ISSUE TITLE
Should there be a way to differentiate (maybe suggest) how to speak non-core intent values

### ISSUE THREAD

**Issue by NSoiffer** [w3c/mathml#256]
'intent's value is a functional notation and the current suggestion is that if the `intent` value name is unknown, a functional style of speech should be used such as "ackermann function of m and n" for `intent='ackermann-function($m, $n)'`. However, some notations are prefix, infix, or postfix and while "factorial of x" is understandable, the more common method is to say "x factorial". That is even more true for nary infix intents such as "plus".

Should `intent` have a way to specify the preferred notational style?

If yes, two alternative methods are:
1. Add `prefix-intent`,  `infix-intent`,  and `postfix-intent` to the existing `intent` list
2. Add a special symbols to the start of the name. I don't know of any intuitive ones, but maybe `@<`, `@|`, and `@>`. E.g., `intent='@>factorial($n)'`.  [I typed a few examples with just `<`, etc., at the start and end and didn't like the look; adding `@` I felt looked better]

I think '1' is clear and simple but '2' is more powerful in that one can mix styles as in `intent='@>factorial(@|plus($a, $b))'`.

I'm sure there are other alternatives to '1' and '2'...

The first thing that needs to be resolved though is: do we want this functionality?

**Comment by davidcarlisle** [comment]
well... one possibility is to drop the functional form for postfix/infix so rather than

```
<mrow intent="factorial($n)"><mi arg="n">n</mi><mo>!</mo></mrow>
```

You could have

```
<mrow><mi>n</mi><mo intent="factorial">!</mo></mrow>
```

**Comment by dginev** [comment]
Personally, my strong instinct is that information that is already available in the presentation tree should not be added to the intent attribute. You can inspect the tree to deduce the prefix/infix/postfix/circumfix/mixfix operator placement. And this is something you'd have to do anyway in the cases where intent was not provided.

I'd also prefer providing (globally) any interesting "speech hints" that may be associated with a notation, by adding them once in the public list of values, rather than depositing them in every formula where a notation is used.

**Comment by davidcarlisle** [comment]
@dginev  yes that's my instinct too (although I'm not sure our instincts lead to the same markup suggestion) that is, I was thinking you know the ! is postfix as it is there in the presentation, the only thing you might not know is that it is factorial so:

```
<mrow><mi>n</mi><mo intent="factorial">!</mo></mrow>
```

**Comment by NSoiffer** [comment]
Figuring it out from the display only works in easy cases. Consider:
```
<math intent='log(plus($arg1, factorial($arg2))'>
   <mi>log</mi><mo>(</mo><mn arg='arg1'>1</mn><mo>+</mo><mi arg='arg2'>n</mi><mo>!</mo><mo>)</mo>
</math>
```

Is it the "+" or the "!" or neither that is associated with "$arg2"?

**Comment by dginev** [comment]
1. Add enough mrows and all you have are easy cases.
2. I'd fix a complicated example by using the syntax we already have, i.e. by adding a reference. Note my change with `$exclamation`:
```xml
<math intent='log(plus($arg1, $exclamation($arg2))'>
   <mi>log</mi><mo>(</mo>
     <mn arg='arg1'>1</mn>
     <mo>+</mo>
     <mi arg='arg2'>n</mi>
     <mo intent='factorial' arg='exclamation'>!</mo>
  <mo>)</mo>
</math>
```

**Comment by davidcarlisle** [comment]
@NSoiffer  I think forcing all infix functions to prefix form complicates the reading and requires more mathematical knowledge than this ought to need (1+2+3 and  1<2<3 having very different prefix forms for example)  so in log(1+n!) hopefully that would all be the default intent anyway but to mark intent do you need more than

```
<mrow>
<mi intent="common-log">log</mi>
 <mo>(</mo><mn>1</mn><mo intent="plus">+</mo><mi>n</mi><mo intent="factorial">!</mo><mo>)</mo>
</mrow>
```
Basically I'd always want to put intent as low down the tree as possible and only put it on a containing element when you need to over-ride the structure or reading order inplied by the presentation tree.

**Comment by NSoiffer** [comment]
I agree with @davidcarlisle's argument that ideally the intent should be as low as possible (which is what @dginev's example also uses). I also agree that it is usually a bad idea to give a prefix form to an infix operator. However, I don't know if generating software is capable of easily doing this.

My feeling is that since the current intent syntax allows the example I gave (and previous people have used similar examples with intent listed higher up), there should be a means to indicate the order intent of how something is spoken. If we feel `intent` should be placed as low as possible is important, either the allowed syntax needs changing or we need explanatory text saying "do it this way, not that way when possible". That's something we haven't explicitly said even in conversations among ourselves. 

I have a better suggestion for naming than my original "@x" syntax: `infix:xxx`, etc. Instead of `intent='plus($x, $y, $z)'`, one would write `intent='infix:plus($x, $y, $z)'`. Understanding (or using) the `infix:` would be optional in that `infix:plus` is just a name and is as meaningful/useful as `plus` in terms of serving as a key to know what to do.

**Comment by dginev** [comment]
Any extension to the syntax of this caliber would make the burden on annotators too heavy (and for no significant value add).

With the minimal consensus syntax by David, AT will be able to pronounce `factorial of $arg` when it is unable to infer the fixity from the presentation tree. To me this is a perfectly reasonable case of "graceful degradation" of service. The value-add of forcing fixity in the intent syntax itself isn't worth a syntax extension, in my view.

The current proposal allows for three upgrade paths to get perfect fixity information:
1. content-near mrow structure
2. using fine-grained references for operators in complex intent expressions (my `$exclamation` example)
3. annotating operator leaf nodes directly, when "intent default" behavior is otherwise sufficient

As to generators, latexml is already generating 1. and 2. in the first prototype, as they align closely to its internal data model. Namely:
```xml
        <mrow intent="$op($arg)">
          <mi arg="arg">x</mi>
          <mo arg="op" intent="factorial">!</mo>
        </mrow>
```

**Comment by davidcarlisle** [comment]
@NSoiffer I'm still not keen, it leaves open both possibilities `infix:plus($x, $y, $z)`  and `plus($x, $y, $z)`  as one of the core/level list `plus` can be known to have an infix reading without this hint so it adds quite some complexity in generation with not so clear benefits.

**Comment by brucemiller** [comment]
As a general rule, I'd align with @davidcarlisle comment to put intent as low as possible. If intent's intent were purely about pronunciation, his example (4 comments up) could be read out as "log open-parenthesis one plus en factorial close-parenthesis" and the question of fixity never arises.

However, if anything more semantic is desired (But is it?), that's a different story. It could conceivably be that the fixity of displayed presentation is distinct from the fixity of pronunciation? (or not). It could be that the pronunciation fixity varies with language? (or not). And any inclination towards computability/content requires more structure.

The latter points would give the advantage to the more functional notation. We don't want to require the UA to parse. OTOH, we may not want to require the generator to parse either (although we can allow them to if they're obsessive).

@NSoiffer original point, I think, was whether unknown symbols *not* in the core dictionaries (which presumably would already have an associated fixity) might need the option to specify fixity. I wonder how many unknown symbols there are which want to be infix/postfix and which would be unpleasant or confusing if read as prefix. Are there enough to be worth the overhead of extending the intent syntax?

**Comment by davidcarlisle** [comment]
I believe this is now covered by hints such as  `@infix` , close?
