### ISSUE TITLE
remove media type registrations

### ISSUE THREAD

**Issue by samuelweiler** [w3c/mathml#258]
These were done in the level 3 spec and do not need to be repeated here.  It would be appropriate to point out that this version (re-)uses these media types, which were previously registered, but we don't need to repeat the template again here.  (and, indeed, repeating it could lead to confusion).

**Comment by davidcarlisle** [comment]
@samuelweiler  @NSoiffer @polx  Just referencing some discussion at

https://github.com/w3c/mathml/pull/299#issuecomment-1073642575

as PR comments more easily lost than issue links,

It seems other W3C media registrations (notably SVG) effectively end up referencing the current version of the specification which seems preferable in the long run than referencing a specification that has been superseded.

**Comment by davidcarlisle** [comment]
@samuelweiler  @NSoiffer @polx  Just referencing some discussion at

https://github.com/w3c/mathml/pull/299#issuecomment-1073642575

as PR comments more easily lost than issue links,

It seems other W3C media registrations (notably SVG) effectively end up referencing the current version of the specification which seems preferable in the long run than referencing a specification that has been superseded.

**Comment by davidcarlisle** [comment]
Referencing obsolete versions does have some issues though, for example XSLT 3 just references the XSLT2 media type registration

https://www.w3.org/TR/xslt-30/#xslt-mime-definition

But the URL given there (and at the IANA registraion for application/xslt-xml) is

https://www.w3.org/TR/2007/REC-xslt20-20070123/#media-type-registration

But this is an obsoleted document that produces the dialog

![image](https://user-images.githubusercontent.com/1268738/159981730-e1b33549-f227-4615-9eef-e25393010e99.png)

It would be good if we could arrange with IANA to give a stable document that just has the registration without being tied to a versioned mathml x.y rec, then we could reference that from MathML 4, ie change the MathML3 links listed at

https://www.iana.org/assignments/media-types/media-types.xhtml#application

**Comment by polx** [comment]
Request to [IETF-types sent](https://mailarchive.ietf.org/arch/msg/media-types/tnsgLJ4zN7etCAA72NWdaDIbgUo/).

**Comment by polx** [comment]
An [answer came quickly](https://mailarchive.ietf.org/arch/msg/media-types/e9-odQ-usqIwpRBrFPVSmWSyqrU/) by Martin Dürst: it is all possible to update and we apply the same process as the registration. That means that we can keep the appendix and a (maybe reduced) part of chapter 6.

**Comment by davidcarlisle** [comment]
media types have been removed from Mathml4 document and the text from MathML3 is being moved to a new document independent of mathml version:  https://www.w3.org/TR/mathml-media-types/
