### ISSUE TITLE
add security considerations section

### ISSUE THREAD

**Issue by samuelweiler** [w3c/mathml#261]
In Mathematical Markup Language (MathML) Version 4.0, add security considerations separate from privacy considerations, per guidance in https://w3ctag.github.io/security-questionnaire/

**Comment by fred-wang** [comment]
@NSoiffer @davidcarlisle I believe this was originally for https://w3c.github.io/mathml/ and should not have been transferred to the mathml-core repo ?

( I still need to split the section for mathml-core, but that's already tracked by w3c/mathml-core#48 )

**Comment by davidcarlisle** [comment]
Security and Privacy sections were added in PR #413  But in comments there they ended up being added as a combined section.

Reviewing the matching discussion on mathml-core 

https://github.com/w3c/mathml-core/issues/48

I guess we need to split that again to two sections. @NSoiffer ?
