### ISSUE TITLE
Introduction

### ISSUE THREAD

**Issue by NSoiffer** [w3c/mathml#263]
The intro needs to move to informative

It should follow other spec intro.

Steve Noble to do work

**Comment by brucemiller** [comment]
@Steve-Noble Just to make sure wires don't get crossed; I understood from last week's discussion regarding core/full (see #266) that I should take over this task while integrating the core/full comparison into Chapter 1's treatment of presentation & content.  Are you good with that, or already working on #263, or would prefer too?

**Comment by davidcarlisle** [comment]
Note the respec markup is `<section class="informative">`  

this will add a boilerplate "This section is non-normative." paragraph and move all the references that are only referenced there to the non normative list H.2 from the normative list H.1

**Comment by Steve-Noble** [comment]
@brucemiller I don't understand the significance of your question. Perhaps I was not paying attention during the discussion you mentioned. I thought that last week's discussion was referring to later sections, not the first section.

**Comment by brucemiller** [comment]
Probably it's me that's confused!  I know that I am tasked to draft the relation of core vs full, and last week we decided that it probably belongs in Chapter 1.  I also know that Chapter 1 needs to be condensed and that you originally were tasked to do that.

What I'm not sure of, is whether I am now assigned to do both of those tasks together (since they both involve Chapter 1), or whether you were still going to deal with the bulk of Ch.1.  In the latter case, we'd need to coordinate.

Maybe @NSoiffer remembers?

**Comment by NSoiffer** [comment]
@brucemiller is tasked with Core vs Full. @Steve-Noble is tasked with describing accessibility.

Where accessibility goes in the spec hasn't been decided:
* SVG puts it in an appendix.
* CSS has a non-normative document [CSS Techniques for WCAG 2.0](https://www.w3.org/TR/WCAG20-TECHS/css.html).
* [EPUB has a separate document](https://www.w3.org/TR/epub-a11y-11/)

My suggestion is let's put it in an appendix for now. That will avoid any conflicts with other sections.

**Comment by brucemiller** [comment]
@davidcarlisle how do we mark a section as informative? I had guessed `class="informative"`, but nothing happened in the html.

**Comment by brucemiller** [comment]
@davidcarlisle Never mind; suddenly it works(!?!?!)

**Comment by davidcarlisle** [comment]
@brucemiller  respec isn't instantaneous (perhaps my fault, it is probaby not optimised for multiple chapter file inclusions, and running post-process functions to index elements or syntax highlight relax ng.... :-)  and also (if you are using the gh-pages view), rebuilding the document is a low priority job on the github server so they do it when they do it, sometimes there can be a delay of a minute or so before it shows up.
