### ISSUE TITLE
Chapter:  Interactions with the Host Environment updates

### ISSUE THREAD

**Issue by davidcarlisle** [w3c/mathml#267]
Paul to take first look at any updates needed

**Comment by polx** [comment]
> are MathML vs CSS rules still applicable?
move to core

> XHTML should be replaced by the XML serialization of HTML5?
guess so

> clipboard still applicable?

yes. Include pickling when it's there.

**Comment by davidcarlisle** [comment]
Yes core should fully specify how CSS applies (although we should check it actually does say everything needed) so we shouldn't say it again here and risk accidental differences being introduced.

I agree we should not use "XHTML" anywhere, the HTML spec actually calls out MathML as one reason for not using the XHTML term:-) see the Note at https://html.spec.whatwg.org/#html-vs-xhtml

**Comment by NSoiffer** [comment]
We should open for specific issues on the text.
