### ISSUE TITLE
Make examples foldable

### ISSUE THREAD

**Issue by NSoiffer** [w3c/mathml#271]
Use summary tag

**Comment by davidcarlisle** [comment]
I had a quick look at this. The standard html markup is

```
<details>
    <summary>some title</summary>
    the exanple here
</details>
```

which makes this (if look in gh not necessarily in email)

<details>
    <summary>some title</summary>
    the exanple here
</details>

It would be possible to get respec to turn existing div class=example to this form but (a) it would have to have some generic summary like **Example** as I don't see any way of inferring a more specific text, and (b) a folded example often doesn't really fit the surrounding text where we tend to say things like 

> The MathML for this is:

which doesn't really read well if the example is folded.

Thus I'm tempted to suggest I don't act on the action item that I took on here to auto-fold examples, and instead suggest that examples are wrapped in `<details>` with custom `<summary>` holding an example specific title text  where this seems to make sense.  The `<details>` could wrap an image and an example and linking paragraphs so they folded together

Her is one example (just coded locally not checked in)

https://w3c.github.io/mathml/#presm_addsub

(the black border a bit ugly but added to show the extend of the folding section, we could decide css styling later)

**Folded**

![image](https://user-images.githubusercontent.com/1268738/156653530-db270a72-bd89-4953-9b61-3f0c2cd2b9c2.png)


**Open**
![image](https://user-images.githubusercontent.com/1268738/156653586-453e0718-d2bf-4f63-b1a8-ee9360490654.png)


The above folding is produced from the following diff

```
diff --git a/src/presentation-markup.html b/src/presentation-markup.html
index 461ac5d..c02dcea 100644
--- a/src/presentation-markup.html
+++ b/src/presentation-markup.html
@@ -11489,7 +11489,8 @@ group-alignment-list-list   = ( "{" <em>group-alignment-list</em> "}" ) +
             </div>
             
             
-            
+           <details style="border:solid thin black">
+             <summary><code>&lt;mstack&gt;</code> addition example</summary>
             <p>Here is an example with the operator on the right. Placing the
                operator on the right is standard in the Netherlands and some other countries.
                Notice that although there are a total of four columns in the example,
@@ -11517,7 +11518,8 @@ group-alignment-list-list   = ( "{" <em>group-alignment-list</em> "}" ) +
             <p>Because the default alignment is placed to the right of number, the
                numbers align properly and none of the rows need to be shifted.</p>
             
-            
+            </details>
+           
```

**Comment by davidcarlisle** [comment]
Currently the folding has broken the table sorting in the newly re-added sortable opdict table, that's probably just an implementation detail but leave this issue open until that's resolved if we want to keep the folding

**Comment by davidcarlisle** [comment]
@NSoiffer  see the notes FOLDING1 and FOLDING2  in chapter 3, FOLDING2 (section 3.3.4.3) is probably the form you want to use as it doesn't require inventing new ids, but both 3.3.2.3 and 3.3.4.3 fold and both links from the table of contents now work.

That is probably enough to start adding the markup, but still to do (possibly)

* add `class=` reflecting the original heading level  so the details summary can be differenly styed in different levels
* restore the `§` section marker self link that normally appears to the left of the sections
* rewrite the folding javascript to use more DOM node re-arrangement rather than innerHML string handling
* fix the table headers in op dict so they again activate sorting (this will probably be fixed by the previous item)

**Comment by NSoiffer** [comment]
@davidcarlisle: I did a pull but I don't see FOLDING1, etc., that you mention.  Is that comment old?

**Comment by davidcarlisle** [comment]
@NSoiffer  sorry the version you had just had one note wih FOLDING, I just pushed it with two as described (I did that somewhere but may have been in one of the other feature branches (too many parallel PRs ....)  anyway now it's checked in the folding sections are 

examples

https://w3c.github.io/mathml/#examples-4

and

https://w3c.github.io/mathml/#examples-5

and opdict sections under

https://w3c.github.io/mathml/#oper-dict_entries-table

**Comment by NSoiffer** [comment]
Thanks for the clarification. I'll get started on adding more `<section class="fold">`s to chapter 3.

**Comment by davidcarlisle** [comment]
@NSoiffer  fold should work on any section but the CSS faking the existing non folding sections is only set up for h4 and h5, which is hopefully enough  I just noticed looking at the second examples example above that if you remove the note it's a bit close to the table at the end of the previous section, so I may need to tweak that a bit more (I can't use exactly the same css as the headings, so I had to merge a simplified version of  respec's heading layout with the `<summary>` styling. But anyway we can fine tune that later, it seems to basically work.

**Comment by NSoiffer** [comment]
I believe this is now resolved.
