### ISSUE TITLE
Update Operator dictionary appendix 

### ISSUE THREAD

**Issue by davidcarlisle** [w3c/mathml#274]
Format to be decided but should match the data in 

https://w3c.github.io/xml-entities/

which will therefore match the data in Core.

Initial proposal to take the compressed view from 

https://w3c.github.io/xml-entities/opdict.html

**Comment by NSoiffer** [comment]
I find both views useful, and with collapsing, it doesn't take up much visual space.

Since this is what is checked in and others don't seem to care, I'm closing this.
