### ISSUE TITLE
mistake in msqrt and being in core

### ISSUE THREAD

**Issue by NSoiffer** [w3c/mathml#290]
@davidcarlisle:
I spotted
```
 <h4 id="presm_mroot">Radicals <code class="defn starttag">&lt;msqrt&gt;</code> <span class="coreno"></span>,
<code class="defn starttag">&lt;mroot&gt;</code> <a class="coreyes" href="https://w3c.github.io/mathml-core/#dfn-msqrt"></a></h4>
```

The `msqrt` has `class="coreno"`. Did you auto generate this, or was this a (gasp) emacs error? I can fix it, but if this was auto generated, then I shouldn't and the script that did it needs fixing.

**Comment by davidcarlisle** [comment]
@NSoiffer  I'll blame emacs as the alternative is unthinkable: user error.
