### ISSUE TITLE
drop maxsize=infinity

### ISSUE THREAD

**Issue by davidcarlisle** [w3c/mathml#294]
`maxsize` has (since the beginning wih MathML 1.0) allowed `<mo maxsize="infinity"`  so has a unique syntax not shared with any other attribute taking a length.

As far as I can tell, the intended effect of `mathsize="infinity"` is the same as not having the attribute at all as extending the maximum amount is the default (once `stretchy="true"`) .

I think the motivation is to be able to give a default value and/or to give a value that can be used in the operator dictionary but no entry in the current operator uses this value.

Having custom length syntax complicates the story re unifying length syntax with css, so I'd like to drop this. I doubt it would have any practical effect (and it could be made valid in the mathml4-legacy schema)

**Comment by davidcarlisle** [comment]
There were no objections to this on the call, so I will adjust the schema, leaving open though until attribute description adjusted.

**Comment by NSoiffer** [comment]
One thing we forget to do is check whether it is used by any MathML generators. I'll send email.

**Comment by davidcarlisle** [comment]
@NSoiffer  actually I think this issue is wrong, sorry, despite the fact I opened it.

I missed some cases in the MathML3 Schema (many of these are not in core at all so unlike maxsize didn't show up as a need to extend an existing attribute's value range, but I think I just missed them for no reason)

```
  attribute linethickness {length | "thin" | "medium" | "thick"}?
  attribute charspacing {length | "loose" | "medium" | "tight"}?,
  attribute mathsize {"small" | "normal" | "big" | length}?,
  attribute mslinethickness {length | "thin" | "medium" | "thick"}?
  attribute indentshiftfirst {length | "indentshift"}?,
  attribute indentshiftlast {length | "indentshift"}?,
  attribute maxsize {length | "infinity"}?
  attribute columnwidth {list {("auto" | length | "fit") +}}?,
```

Given the length of that list we may want to just close this with no action, other than me fix the schemas to allow these, not all of which are valid to the draft mathml4 schema.

**Comment by NSoiffer** [comment]
Closing it is certainly the easy way to go. But if anyone has information on whether any generators actually use these, this could be a good opportunity to simplify MathML 4 (and make it closer to core) if these values are not actually used.

I do remember back when I was working at Design Science and working with ACS on typesetting some tables that needed internal linewrapping and "clever" column widths using (essentially) MathPlayer, I made use of "fit" and "auto" for tables. I think their style also made use of `indentshiftfirst` and/or `indentshiftlast`, but I don't think `indentshift` was ever needed to be set explicitly since it was the default.

**Comment by brucemiller** [comment]
FWIW, as near as I can tell, LaTeXML is not using any of the above keywords.

**Comment by davidcarlisle** [comment]
Thinking about this a bit more I think these cases (and named spaces like `rspace="thinmathspace"` are not too bad really, they are all of the form _length or keyword_, so the css length syntax isn't altered and can still be specified by reference, used in `calc()` expressions or whatever.

More problematic are the extensions to 

* unitless lengths (which were deprecated so I think we can drop)
* pseudo-units such as `height` which appear "within" the length
* mpadded +3em which is syntactically a length but...

**Comment by NSoiffer** [comment]
At the meeting today, we agreed let keep the less problematic ones (at least for now) and split off the `mpadded` attributes into their own issue for discussion.
