### ISSUE TITLE
extract media-type declarations into a standalone specification

### ISSUE THREAD

**Issue by polx** [w3c/mathml#306]
The text in chapter 6 about the resource-types and encodings (e.g. [6.2.3](https://w3c.github.io/mathml/#world_resource_types) and [6.2.4](https://w3c.github.io/mathml/#encoding-names) and the text in [appendix B](https://w3c.github.io/mathml/#media-types-reg) should be extracted into a note that will enter [mathml-docs](https://github.com/w3c/mathml-docs/) and should be prepared to become a recommendation.

**Comment by polx** [comment]
First effort made in [this branch](https://github.com/w3c/mathml-docs/tree/extract-media-type-issue-306).

@davidcarlisle : is there a way for me to have more "wrappings" such as table of contents and a bibliography?
And... how does it get rendered? (I guess into [here](https://w3c.github.io/mathml-docs/mathml-media-types/)?).

Tricky parts thus far:

- refer to MathML's chapter 3 and chapter 4 as the definition of presentation and content is done using such sa https://www.w3.org/TR/MathML/chapter3.html . I guess it is stable enough.
- refer to MathML's declaration is done for MathML3. I think that this stays.

Future: once the [RFC6388](https://datatracker.ietf.org/doc/html/rfc6838) is moved to drop Macintosh 4-letter codes, we shall do so...

**Comment by davidcarlisle** [comment]
@polx to see a rendered version locally I just use a web server rooted at the git checkout, specifically

`python3 -m http.server 8080 &`

then look at ` http://localhost:8080/index.html`  

to get a public view it's easier to do as @samdooley  just did for the chapter 4 re-arrangment, use a fork and run gh-pages on the fork ending up in that caase with  https://github.com/samdooley/mathml

You should get a table of contents automatically just from  using correctly nested `<section><h???>xxxx` in the main document.

For references reference a spec such as `[[MathML3]]` and respec will make a references section. respec knows about all w3c and rfc and similar specs. It doesn't know about MathML4 yet, you can add more though , see the `localBiblio`  entry in the respec config of the main spec. You can check what resepc does already know about at https://www.specref.org/

**Comment by davidcarlisle** [comment]
@polx  the table of contents didn't appear as there was a respec error (the mmlindex function copied from the main spec had no target)  I have fixed it up locally and some other respec warnings.

 I could push to your branch if you have no pending edits or I could make a new branch and PR to your branch if you prefer?

![image](https://user-images.githubusercontent.com/1268738/162278389-77e837cb-9a30-4d9f-ad46-366ef4122cd1.png)

**Comment by polx** [comment]
I have no pending changes yet. Thanks!

**Comment by davidcarlisle** [comment]
@polx  I pushed my edit to the branch, it looks good to merge to `main` branch  so it appears at github.io

**Comment by polx** [comment]
I have created https://github.com/w3c/mathml-docs/pull/37 to merge this into main.

**Comment by davidcarlisle** [comment]
This is merged and added to the mathml-docs index 

https://w3c.github.io/mathml-docs/

**Comment by dginev** [comment]
Writing a comment to avoid opening a new issue:

In the newly factored out document for media types (thanks for which!):
https://w3c.github.io/mathml-docs/mathml-media-types

I read several mentions of the phrase (emphasis mine):

>  normative backward compatibility behavior described in **this specification**.

Now that the two documents are teased apart from each other, it may be better to explicitly reference what "this specification" is naming.

I am also unsure myself it the notes on MathML "backwards compatibility" have a central point of entry that can be linked to, or are interspersed in several places of the main MathML spec text.

**Comment by dginev** [comment]
And another extremely minor note:
> The media types described here may be applied to instances of all versions of MathML up to and including MathML 3.

Should probably get updated to MathML `4`.

**Comment by polx** [comment]
I believe I can close the branch now, or?
@dginev , thanks for the comments, there is now instead of "this specification", "this normative text". The word "specification" is only used with MathML.

**Comment by NSoiffer** [comment]
I agree -- closing the issue.

**Comment by davidcarlisle** [comment]
@NSoiffer  @polx  Not sure this should be closed yet. The full registration text is still in the spec at

https://w3c.github.io/mathml/#media-types-reg


unless we are going  to merge  PR #364 ?

**Comment by NSoiffer** [comment]
I thought this was about the separate media-types spec.  Can't we now just delete appendix b? A reference to the new spec should be added to 6.2.3 and/or 6.2.4. Or maybe those need editing now???

**Comment by NSoiffer** [comment]
I merged #364, but am reopening this because I think we should agree that chapter 6 is ok and doesn't need shortening.

**Comment by polx** [comment]
The way the #364 applied is good. Thanks.
The chapter 6 discussion is much longer to my taste.
There were discussions on shortening it and it got aborted; now that we have an active folding, we could restart it but it might take time.

I would more worry about the shifting of names of appendices and wonder if we should not keep a phantom appendix instead.

**Comment by davidcarlisle** [comment]
> I would more worry about the shifting of names of appendices and wonder if we should not keep a phantom appendix instead.

The (still empty) accessibility appendix is a new addition relative to MathML3 anyway so all appendices after that are naturally re-numbered so only the operator dictionary is affected by deleting this media types appendix I think. A bigger change for referencing is that the normative version is now single file so all chapter and appendix references change form

https://www.w3.org/TR/MathML3/chapter3.html

becomes

https://w3c.github.io/mathml/#presm

**Comment by NSoiffer** [comment]
Worst case is that the new accessibility appendix replaces media types to avoid the shift, but (as with @davidcarlisle), I don't think a shift is a problem. The number of people who remember that Appendix C has the operator dictionary can probably be counted on one hand (and most of them are part of this discussion :-).

**Comment by davidcarlisle** [comment]
This is done, closing.
