### ISSUE TITLE
chapter 4 rearrangement sketch

### ISSUE THREAD

**Issue by davidcarlisle** [w3c/mathml#320]
In #319 @samdooley  proposes a re-organisation of chapter 4 removing the syntax tables from each element.

As I comment in the PR I think this goes too far in removing information from the main section for each element.

I think the main section should have some formal statement that `<plus/>` is empty used with `<apply><plus/>` not a container used as `<plus><cn>1</cn><cn>2</cn></plus>`

Rather than just make negative comments I thought I'd sketch a different direction for condensing this material, although it's at a preliminary stage, and I am not generating a PR.

The basic idea is that currently each section such as the one for `<plus/>` has a table

```
Class                nary-arith
Attributes        CommonAtt, DefEncAtt
Content           Empty
Qualifiers        BvarQ,DomainQ
OM Symbols   [plus](https://openmath.org/cd/arith1#plus)
```

having such a table for every entry does get very verbose,  but acually only the first row is needed, once you know `<plus>` is of class `nary-arith`  you know it is empty and its allowed attributes, and all elements of  that class map to OM arith1 CD symbol of the same name as the the element..

So the basic idea of the fork is to compress the table to one row then put a "template" for all elements where the class is introduced in section 4.3.4

plus:  https://davidcarlisle.github.io/mathml/#contm_plus

conm-nary: https://davidcarlisle.github.io/mathml/#contm_nary

Currenly the same styling is used so the 1-row table looks a bit spacy...

----

This simplification breaks down a bit in cases  where the mapping to OM isn't 1-1 or where there are extra qualifiers eg `<degree/>` but I think with some careful wording that could be managed....  

---

This fork also shows two other unrelated simplifications

 * Content mathml examples are not inlined to be rendered
 * Presentation  MathMl sample renderings  _only_ have the inline mathml not the image (ie support for core is assumed)

(For ease of experimenting, in this sketch they are there just hidden with css)

But all in all 

https://davidcarlisle.github.io/mathml/#contm_plus

is a lot shorter than

https://w3c.github.io/mathml/#contm_plus

**Comment by physikerwelt** [comment]
To me, Section 4.4 has a large overlap with the new intent markup. Maybe we should deprecate the entire set of pragmatic content in favor of the intent attribute. Otherwise, we have two ways of specifying somehow semiformal mathematical expression trees.
If we decide to do so, we can keep the section in its current form and do not need to invest work to restructure the content.

**Comment by davidcarlisle** [comment]
@physikerwelt  I do not agree with deprecation but we will at some point need to be clearer on the relationship, see for example my comment

https://github.com/w3c/mathml/issues/289#issuecomment-1066153024

I don't think intent replaces content mathml, but I think it could potentially replace OpenMath  as providing the ground terms for Content MathML semantics, but that doesn't have to be done in this iteration, I think we are committed to maintaining Content MathML as based on rewrites to Strict and basing Strict on OpenMath Cds   for MathML4.

**Comment by davidcarlisle** [comment]
The original plan, to have single line links from the element sections in 4.4 back to the syntax tables (moved to 4.3) is now in a temporary chapter 5 in the fork at

https://davidcarlisle.github.io/mathml/#contm_abs

Chapter 4 now shows a new re-arrangement in which section 4.4 has been removed completely and merged in to an expanded 4.3. 

https://davidcarlisle.github.io/mathml/#contm_structure_extended

This already shrinks things a lot as you only need one syntax table and one or two examples for all  the elements in the same syntax group. As this just does the re-arrangement moving text, not all oportunies for dropping examples and merging text have been taken yet, that would require reviewing the text in each case.  Also respec is currently showing some errors due to broken links and duplicated ids, due to the two versions of chaper 4 and some references to deleted sections, this can be easily resolved if we go his way,

It is easiest to see the differeces here by reviewing the table of contents in the sidebar, rather than looking at the main body of the document.

**Comment by davidcarlisle** [comment]
@samdooley  as agreed in today's call I stole your content element table appendix and added it as

https://davidcarlisle.github.io/mathml/#contm_cops

I also deleted the second copy of the main content mathml chapter

There are some broken links as it is (not) linking to the re-arranged version of chaper 4, but that is mosly mechanical fixes, but probably not today.

**Comment by davidcarlisle** [comment]
#325 has been merged, so closing here
