### ISSUE TITLE
Non-core MathML examples

### ISSUE THREAD

**Issue by NSoiffer** [w3c/mathml#321]
How do we want to handle MathML examples for things not in core (such as `mfenced`). I thought this was already discussed, but I don't see an issue and I don't remember a resolution.

To make things concrete (and because I was working on fixing this up in the spec), I'll use a specific example...

In "Examples of Linebreaking", there is an example that shows how various linebreaking/indentation should work.

With the standard `class="example mathml"`, both the input and output are shown. However, without the linebreaking polyfill, none of the browsers will get this right.

Following the example is "This displays as" with an image.

I see a few options for what to do:
1. Include the linebreaking polyfill and remove the image
2. Remove the `mathml` from the above so only the input shows
3. Remove the image (but then the example is pretty useless)

I don't see removing the example as useful as the linebreaking/indentation examples are relatively complicated and having an example is useful. In fact, I'm tempted to add one or two more examples.

**Comment by davidcarlisle** [comment]
all? mathml examples are or should by now be one of

`<div class="example mathml mmlcore">`

`<div class="example mathml mml4p">`

`<div class="example mathml mml4c">`

so the mfenced or linebreaking ones should be `mml4p` currently all three are inlined as-is with just the single or double bar marking the mml4p or mml4c ones, but we could decide to only inline mmlcore example or always polyfil the others or ...

Note that currently all the inline mathml renderings are removed when the rec version is saved, but we could leave them in, or just leave the core ones in...

**Comment by NSoiffer** [comment]
I guess I'm about to have merge conflicts :-(

<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by NSoiffer** [comment]
I'm in favor of polyfilling the examples -- it would be a nice touch to list the polyfills used at part of the example)

**Comment by davidcarlisle** [comment]
@NSoiffer  OK I guess we start by removing the `removeOnSave` CSS class from the inlined mathml so that the examples are in the spec then work on polyfilling as needed.  We'd need to either copy them in to the spec area or put them somwhere at a stable URL, not sure we'd want to link directly to the github sources?

**Comment by davidcarlisle** [comment]
There are 28 non-core examples in chapter 3 (and currently 1 in chapter 5, which I will probably mark as not to be inlined, as it's demonstrating `<annotation-xml` markup so the presentation is just a distraction really)

The test document at

https://davidcarlisle.github.io/mathml/mml4p.html

shows all 28 examples with the nearest section heading copied  from the spec.

Each one has

*  `<pre>` with mathml source (black border)
*  Inline MathML as rendered by your browser (green border)
*  Inline MathML modified by `mathml-refresh/mathml-polyfills`  (blue border)
* `alt` text and image from the spec repository (if there is one)  (pink border)

Many of the images have been deleted from the current draft but the `png` are still in the repository and picked up here. Some examples never had a matching image, and they show with a duplicated `to be generated` `alt` text here.

----

Currently the live respec draft

https://w3c.github.io/mathml/#example-1

shows the MathML source and the polyfilled rendering

The exported static HTML version

https://w3c.github.io/mathml/spec.html#example-1

Currently does not reference the polyfill Javascript but is showing the transformed MathML rendering.

I think  the intention is to use images here so we need 28 images,  Looking at this test I'm not sure the polyfills are robust enough to commit to auto-generating these images, and as it's only a few I'm thinking  of using image files as now but deciding in each case whether to update with an image of a browser rendering or to keep the current tex-generated version.

If we rename them to have sensible file names based on the id of the example, it will be easy to switch in images on export from respec.

**Comment by NSoiffer** [comment]
Safe to close?

**Comment by davidcarlisle** [comment]
yes closing
