### ISSUE TITLE
Styling around foldable examples

### ISSUE THREAD

**Issue by NSoiffer** [w3c/mathml#322]
The following looks like a CSS styling issue involving foldable content:
![image](https://user-images.githubusercontent.com/1545836/164341743-b67a02ae-e8ec-4d75-8a77-f5b4c17fd20a.png)

The first example is at the same heading level as the surrounding levels but is indented, making it look like it is part of the previous section, which is wrong. In the second example, the indentation is correct. I suspect there needs to be a second CSS rule .

The actual HTML is 
```
  <section>
   <h5>Attributes</h5>

   <p><code class="element">mn</code> elements accept the attributes listed in <a href="#presm_commatt"></a>.</p>
  </section>

  <section class="fold">
   <h5 id="presm_mn_examples">Examples</h5>
```

**Comment by davidcarlisle** [comment]
I'll look again at the styling

Currently the folding sections are `<details><summary>` elements with css attempting to make it look like a heading, it might be easier to use the same heading markup as normal sections, then add the folding via javascript, but not sure pubrules allows  that.

**Comment by davidcarlisle** [comment]
Now looks like

![image](https://user-images.githubusercontent.com/1268738/169668366-16bfa48c-f8f6-4515-8b95-7631151c9c2e.png)

close?

**Comment by NSoiffer** [comment]
Much better. It would look a little better if the arrow was on the right so the headings really aligned, but it might also be a little surprising/confusing to people because it would be different. In case you want to try, I found [this page](https://stackoverflow.com/questions/56758098/how-to-position-detail-marker-to-come-after-summary) which shows a little CSS to do it. I believe `-webkit-details-marker` can be replaced with a [standardized value ](https://developer.mozilla.org/en-US/docs/Web/CSS/::marker) `marker` now.

I assumed you looked and didn't see any `<h4>`s. But it might be safer to add them to the stylesheet also to future proof this.

Despite the above pickyness, I think this is good enough, so I'm closing this. Thanks for figuring out the css.
