### ISSUE TITLE
Implicit values of boolean attributes

### ISSUE THREAD

**Issue by fred-wang** [w3c/mathml#33]
The proposal was to consider supporting syntax `<mo largeop stretchy>` instead of `<mo
largeop="true" stretchy="true">` for compatibility with HTML5. However, MathML takes default value from the operator dictionary, so it's probably an invalid request.

"MathML boolean attributes take value "true" and "false". In HTML5,
the boolean value is given by the presence/absence of the attribute and
the only allowed value is the name of the attribute. This allows to get
more compact syntax like <mo largeop stretchy> instead of <mo
largeop="true" stretchy="true">. However, Web engines and authoring
tools will continue to support the true/false syntax anyway, so it's
probably not worth adding complexity here...

   https://www.w3.org/TR/html5/infrastructure.html#boolean-attributes"

(original report: https://lists.w3.org/Archives/Public/www-math/2016Aug/0000.html)

**Comment by dani31415** [comment]
Perhaps there are two specifications XML-MathML and HTML-MathML. People are using MathML as a XML format in some contexts DITA and others.

**Comment by physikerwelt** [comment]
discussed in the telco on 2019-02-25:
* seems to be impossible / incompatible with HTML

**Comment by fred-wang** [comment]
closing

**Comment by fred-wang** [comment]
Resolution:
  https://github.com/mathml-refresh/mathml/issues/33#issuecomment-467161079

Specification: N/A

Implementation: N/A

Polyfill: N/A

Tests: N/A
