### ISSUE TITLE
spec load/timing problem

### ISSUE THREAD

**Issue by NSoiffer** [w3c/mathml#330]
I thought my problems with the spec taking forever and my machine freezing up for a while were solved when I turned off some anti-virus "web shield" options, But they are happening again. I used chrome's network debugging and see the following:

![image](https://user-images.githubusercontent.com/1545836/165180829-652772ec-0510-4b28-8ebb-36c53313330a.png)

The bibrefs seems to be causing a hang for some reason. 

Firefox won't finish loading now (this is new):
![image](https://user-images.githubusercontent.com/1545836/165182074-dfe86f0f-9a12-4376-bde2-770a933b7076.png)

Running a local server, I don't seem to have a problem.

@davidcarlisle: any ideas/changes?

**Comment by polx** [comment]
On a cleaned firefox, I get 3.5 s load for the get http://api.specref.org/ 
Down here, the DNS tells me that this server is reachable at one of 18.205.222.128, 54.237.133.81, 52.202.168.65 (all in the US) as wget tells.
Could you click on the bibrefs request to see how it finishes up and try the IP?

**Comment by davidcarlisle** [comment]
@NSoiffer if I run on my local server the history file is always blocked with a CORS error as the w3c server (I think) whitelists github to make that access. So that one is ignorable (and shouldn' take too long, it's just an instantly refused API request)

When using the github version, when the API request isn't blocked it fails as your image shows, simply because TR/MathML4 isn't there yet. It doesn't take long to fail for me though,

![image](https://user-images.githubusercontent.com/1268738/165274870-30ca5e69-be81-40ed-93f4-d5a1e5e6d5ee.png)

**Comment by davidcarlisle** [comment]
If I disable the cache tha bib lookup takes 336ms and total is 803


![image](https://user-images.githubusercontent.com/1268738/165276635-87a0a50d-1e6b-40b7-a7fa-3ea145a4111a.png)

a normal reload, without clearing the cache, is reported as total 332ms

**Comment by NSoiffer** [comment]
It's back to loading ok again. I don't have any idea what is going on...

**Comment by stefnotch** [comment]
@NSoiffer If you can reproduce this issue again, you could try playing around a bit with the "disable cache" feature and with "request blocking". Maybe that'll help with narrowing down the potential causes of this issue. (For the record: The page takes 6 seconds until the loading spinner in the top right corner goes away on my machine.)

Here is an example screenshot that uses the Firefox developer tools, but the Chrome dev tools should be equally capable of doing this.

![image](https://user-images.githubusercontent.com/10220080/165837720-226a473a-34ba-4478-8346-1d20fe8ccb29.png)

**Comment by davidcarlisle** [comment]
can we close this? 

For anyone who just wants to read the spec without  waiting for respec to assemble the references we now have
https://w3c.github.io/mathml/spec.html
available built by gh-actions on each commit (not that that helps you so much while you are editing the spec)

**Comment by davidcarlisle** [comment]
closing as addressd by spec.html for people for whom respc processing is taking too long
