### ISSUE TITLE
policy for images in MathML4 drafts

### ISSUE THREAD

**Issue by davidcarlisle** [w3c/mathml#334]
If PR #333 lands, the exported REC HTML and the live respec draft will show the rendering of inline mathml.

We need to decide what to do about the images of the mathml rendering

They can be 

* dropped or 
* kept or
* re-generated with browser MathML rather than TeX rendering.

This decision can be made separately for each of the example CSS classes

* mmlcore (Core)
* mml4p (Presentation)
* mml4c (Content)

It can also be made separately for

* The live respec draft redering
* Exported REC track HTML

No actual proposal here just opening this as a tracker issue

**Comment by davidcarlisle** [comment]
We are, I think, converging on a policy of:

* In the source files
   
   - Dropping images from content mathml examples (they all have a paired presentation mathml example)
   - dropping images from mathml core examples
   - keeping images for mml4p examples

This results in a display

* In the live respec draft

  - No display of Content MathML rendering
  - Inline rendered display of MathML Core (all the `<math>`  elements have a generated `alttext` attribute for use by non-mathml capable browsers. This is required by W3C pubrules, although testing with opera, I don't think this attribute is used by default, it just shows the MathML character data "falling through" uknown mathml elements.
  - polyfilled mml4p (@NSoiffer polyfills not set up, they could access `mahml-refresh` github if not being used in TR space.)

* In the exported w3.org/TR HTML document
    - No display of Content MathML rendering
    - Inline rendered display of MathML Core, with alttext fallback at least in principle.
    - Images for mml4p examples.  We may wish to regenerate all images using a browser rendering (firefox seems easiest to script here), replacing the TeX generated images used currently).

**Comment by NSoiffer** [comment]
For the source file, I do _not_ think we are converging towards keeping images for mml4p examples -- I've eliminated all the images. Also, that doesn't correspond to what you wrote later.

For the last point in exported w3.org/TR HTML document, I assume you mean generated images in Firefox after the polyfills have rendered the (potentially non-core) MathML.

**Comment by davidcarlisle** [comment]
@NSoiffer I think we should lose the tex generated images, but I thought the plan was to use images rather than polyfills for exported REC, which means having them in the source somehow, possibly a json mapping of the example ids to data blob URLs of the firefox rendering or something. Can't really expriment until we get the polyfills at least working in the respec version,

**Comment by NSoiffer** [comment]
My thought was that the images are generated from the polyfills used in the respec version and they then replace the polyfill rendering ("We may wish to regenerate all images using a browser rendering").

Do you mean that get generated from the polyfill rendering (semi-manually) and are stuck in the respec/main branch version and are only used in the TR space version?

**Comment by davidcarlisle** [comment]
@NSoiffer 

> Do you mean that get generated from the polyfill rendering (semi-manually) and are stuck in the respec/main branch version and are only used in the TR space version?

Yes, I was hoping to generate json  something like the following which we could load into `index.html` for use in the   
"export to TR/" HTML

```
{
"presm_example_id_whatever":
"data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAGQAAABkCAYAAABw4pVUAAAGlUlEQVR4Xu2cyc9uQxDG7/0HiGFFWBh2EmLcsLFAsCNBWEjcGBMJEbMdERYkEmNILAgSdshly4IYwtoQYWsI/wDPj1PJuceZu/pV71EnqXzv933ndFc/T1d1dVe95+CBvEIhcDCUNqnMgSQk2CSITsi1wutkyZPBcLtX+vwoedNbr6iEHKeBvi7h512Sj70HXtjehXr+ackvkuubn4VN/vN4VEION6NzHawLYkc2goWcKjnPq+2IhOCmnpOc7jnzvADrtIMFfyN5QPKiRx8RCflWA3tJEm3dGMKb9eR+ybFbJORyDeq9xg187zHAHbRxivr4TnKdpHiRj2YhuKpLJKftAEjPLj5TY8jtpY1GI4RBMdtYR/bpcptI0Qj5Uyzc57x+WJAA0URDFlJjhV6WyDryhKQYz+IGHKfxmWrrK2dCAP9uySuN5V2hn3c2fXztqDukvyG5SFK0Z4pECJutjzwGNQA07pDrkMSTDNp00/3/RMhjAu4cyWWOlmFNJSELQcUdvixhV+2yX+j0v2lCvBd1yGDBJSRlYWcdOUPytsRrr7PpNcSTEHb9iJ2JsXG7RuKyiWtZiUVZm1zUPQlZ6NlW375JQkCDfcgHlRbe1WjPeNAs73jdy5H86itSlLXPhJAuuFRSjGdxA6unQv+DDOx8SY1IyFnVI5pjnfpNUpwXiUiIy0yriX5P226uNhohtjiyX/AKSXfBjdsZXFRCisPHXbDQ9GGbQpfoMBohlqDaR0Jc9jbRCHE7gvgPLMRlEvURcosG80IzoOK4eiEw+5jC5Yj/Z0k1CyGEY1HlculkASmuBQML+i291a0wo2shzNDXJBzCnSt5S7LLdCqpUK7i3HQpwgufR2/2TsVYdQlhY/aFhDLJuW4LJW6cMYCpPITVODER9inkZehUnnwuKa4laxNi5SzmrrASrim3xXMnzCBkLLUJGc82lvnQjLYi3kICDOzukKw+z2oTgtkBrs1kUp67cFtWhPC8+ttXMmyCQMptElzuqhotI8TcxTEDU28s2ip1WUyCqyU3S66SeOe7GRLju0lytqTYzw9gRCLsHQlVl6uTX0YIoe7jkrYPtCoQ+h9zWx4uiz4IKJ6RXFBi8j1gWeXJ7/rfxS0PMIDr6j8TaVHR8v7qFvQghNiCZHVL1p7F1/xOjmIXlei4SXLfLoXLHWDYdD5ciRCs7lFJcZ0XhNhZPvq3z2Paf+/+r2QSjD2LD6aUtPgYu6eTmoRYdFq8BkY7OrFTghp61SRks6e9Nc+yIJsiOW/rs7W22llWLXc0p91ahDCD25cLeE2DpjPlRUULOu3VcA1zgB+6x616o0SJhc9uOh9ihJwlUGrsRxZiPet2O+HYZIKKKOvBgJY7xQwukZOG4kPRaC7LrZxmCkHn/2+2yMG+MuAdCTnj/6/mmEhspIv1jmYhUzOtGy3VBrrb/hBebpYdkZBdJ8U8SOWknFPeYjyLG/AYTdNGja+0Oao32pRbuB6JkJJ4HkA4yaXqseY1hNemCblViC497cWHc9q65AuXnNCuSiL1MO5WTxbRQpYeawDGSStJnMrzz7U2tyOfLRDCgvqIxPLY7JzvkfwgGXtfClaVhIxMOZtlU0UVWMSnLQIgxHbIBAasI6Rqv+whxF6IhhqkjEm32lXysptNWsicKAsyrmzNfn4/qmctYJHl6oI8lxBbE1jPPpFYrnyItE0u6gA4J9HDjhgLIffOWxqealmLzfYhQloG8XemdMhlQcgfEt4ax+nBuwPEt/vb3Ks1GByDZy2Y8u0G+NG6ty9tWkoIulhNwZzvqmz26GTuaa9ZyVCVB+EsRRtjOe6hsJfM4k8SXCMBwquNtYwln37VPS51ZZGiLGal5RbmZN+4t1tyaotr2zUtHSPWZTViJ+ozL1QbCzRsvXHJ4SxVtj3QWp8xf64pt1Wr/6XtuuobkRCrE1tdjrkU0YL7Xa0DPSISgl5W73uDPhcXDhQAPvaofXXDdeJEJQQgrLT0Q30uTo06k2Kv9CsuHe3qFZkQ05UNY7SCh2o67QMhzpM7dnNJSDB+kpAkJBgCwdRJC0lCgiEQTJ20kCQkGALB1EkLSUKCIRBMnbSQJCQYAsHUSQtJQoIhEEydtJAkJBgCwdRJC0lCgiEQTJ20kCQkGALB1EkLSUKCIRBMnbSQJCQYAsHUSQtJQoIhEEydtJAkJBgCwdRJC0lCgiEQTJ20kCQkGALB1EkLSUKCIRBMnbSQJCQYAsHUSQsJRshfNMpQdHQAlYcAAAAASUVORK5CYII="
}
```

which on export we could use to remove the non core inline mathml and drop in a data: URL image, which I can not get to work in this markdown, but should look like:

![image](https://user-images.githubusercontent.com/1268738/168418869-da5648c0-b343-470e-8239-63f4103c4048.png)


But actually I only know I can automatically do this for core rendering (where it isn't needed:-), I didn't manage to get the polyfill modules to cooperate with respec, so if you could push a version of the spec with polyfills enabled I'll try again. 

A fallback position (as there are not so many non-core examples) would be to simply generate them from a screen snip (as I did above) and check them in to git as png images, again just to be used in the exported rec trac html version (but I can't do that either until we get a version of the spec with polyfills enabled)

Hopefully all that is needed here would be to add

```
<script src="https://mathml-refresh.github.io/mathml-polyfills/loadall.js" class="removeOnSave"></script>
```

But my attempt to write `loadall.js` failed (I forget where now)

**Comment by davidcarlisle** [comment]
closing this.  We have (hand maintained) images for (just) non-core examples with the live respec version also showing rendering with mathml-refresh polyfills
