### ISSUE TITLE
Change default value of mfrac@linethickness 

### ISSUE THREAD

**Issue by NSoiffer** [w3c/mathml#335]
MathML Full says that the default value is `medium`, but that's not a legal core value. MathML Core says the default value comes from the OpenType math table value `MATH.MathConstants.fractionRuleThickness`.

I think it is would be good to harmonize full with core.

Also, in the description of `mstyle`, an example is given using `linethickness`, and there it says the default is `1` (should at least have a unit). This should get adjusted to the real default.

**Comment by davidcarlisle** [comment]
I don't think we can assume a MATH table is available but we could add something like

Change

> the exact thickness of these is left up to the rendering agent. 

To

> the exact thickness of these is left up to the rendering agent, however if OpenType Math fonts are available then the renderer SHOULD set `medium` to the value  `MATH.MathConstants.fractionRuleThickness.` which would align with the default value in MathML Core.
