### ISSUE TITLE
Work remaining towards FPWD

### ISSUE THREAD

**Issue by NSoiffer** [w3c/mathml#342]
The following work was identified as being needed to be done before we can have a First Public Working Draft:

* [x] index.hml integrate polyfill for respec draft (and related, generate images for non-core examples)
* [x] Chapter 3: finish reviewing the content and aligning with core and plans for current spec
* [x] Chapter 4: finish rearranging content, merging sections, hiding examples
* [x] Chapter 5: nail down intent syntax; decide how much (if any) to say about level 0 
* [x] Appendix B: move most content to a FPWD for Media Types and then make this something short that points to it
* [x] #346
* [x] Appendix F: Clean up/simplify table
* [ ] Overall review
* [x] The document would need to pass pubrules, in particular be valid here https://validator.w3.org/nu/?doc=https%3A%2F%2Fw3c.github.io%2Fmathml%2Fspec.html

**Comment by davidcarlisle** [comment]
* On chapter 4, there are currently 4 open PRs with "sample" clean-ups of individual sections.

   If they are OK then can probably do all other sections of 4.3 in similar style. Perhaps main thing that needs to be agreed is dropping the images. The current PR comment them out in case they need to be brought back, but it would be simpler to remove them. (All sample renderings in chapter 4 use mathml core examples)

* I added one bullet point to the main description above, re polyfills. @NSoiffer  locally I tried making a top level  
`https://mathml-refresh.github.io/mathml-polyfills/mathml-polyfills.js`
and including a `<script src=` reference to that script here, but it seems my module flavoured JavaScript foo is lacking, I got no errors in the console, but the polyfills didn't fire. If we have a version of the spec with polyfills enabled I think I can generate a json file with data: URL encoding png images of firefox renderings of all inline mathml examples which we could then use for the non core examples in the exported version (if we decide not to copy the polyfill code here)

**Comment by davidcarlisle** [comment]
Some of the validation errors are github markdown generated things in issue notes that will go, but many are not. I just cleaned up a load but over 100 errors/warnings still to go....

Now just one error at https://validator.w3.org/nu/?doc=https%3A%2F%2Fw3c.github.io%2Fmathml%2Fspec.html  the invalid math as reported in #347

still link checker issues to work through

https://validator.w3.org/checklink?uri=https%3A%2F%2Fw3c.github.io%2Fmathml%2Fspec.html

**Comment by davidcarlisle** [comment]
![pubrules happy](https://user-images.githubusercontent.com/1268738/184492786-9b5625a1-9282-44bf-876a-623e987cbc33.png)


pubrules link https://www.w3.org/pubrules/?url=https%3A%2F%2Fw3c.github.io%2Fmathml%2Fspec.html&profile=FPWD&validation=simple-validation&informativeOnly=false&echidnaReady=false&patentPolicy=pp2020

**Comment by davidcarlisle** [comment]
The deed is done:  https://www.w3.org/TR/2022/WD-mathml4-20220908/
