### ISSUE TITLE
Fix examples at the start of "3.5.5 Alignment Markers"

### ISSUE THREAD

**Issue by NSoiffer** [w3c/mathml#354]
The examples at the start of 3.5.5 are done with a `pre` and don't use italics for the vars or proper math spacing. These should be images (there are not any polyfills for the alignment markers).

The same needs to be done with the examples in https://w3c.github.io/mathml/spec.html#table-cells-that-are-not-divided-into-alignment-groups.

**Comment by davidcarlisle** [comment]
or perhaps clearer than images here espcially as it's introductory "somewhat like that shown here:" rather than claiming to show MathML, would be to use HTML tables.

**Comment by davidcarlisle** [comment]
these now use html table markup, closing
