### ISSUE TITLE
"thin", "thick", "medium" values mfrac@linethickness

### ISSUE THREAD

**Issue by fred-wang** [w3c/mathml#4]
From https://mathml-refresh.github.io/mathml/chapter3.html#presm.mfrac :

> Specifies the thickness of the horizontal "fraction bar", or "rule" The default value is "medium", "thin" is thinner, but visible, "thick" is thicker; the exact thickness of these is left up to the rendering agent.

The MathML Core spec suggests 50%, 100%, 200%.

It's possible that we also want to remove/deprecate these values if they are not used in practice.

Math WG discussion: https://lists.w3.org/Archives/Public/www-math/2016Aug/0001.html

**Comment by physikerwelt** [comment]
I think we should remove the string constants "thin" (50%), "thick" (200%), "medium" (100%)

**Comment by fred-wang** [comment]
cc @rwlbuis, @emilio :

This was removed from MathML core in https://github.com/mathml-refresh/mathml-core/commit/ce02fd15cadb6bcb2d27368eac50027f9ab78c71

I'm leaving this open because it still remains to:
* [ ] Remove WPT tests if any.
* [ ] Send intent-to-remove to mozilla/webkit-dev mailing lists (maybe old Math WG too?).
* [ ]  Remove browser implementation.
* [ ]  Decide what to do for the full MathML spec (remove values? deprecate them? specify explicit numbers?).
* [ ] Add polyfill to https://github.com/mathml-refresh/mathml-polyfills (e.g. convert to linethickness="50%",  "100%", "200%" respectively).

**Comment by fred-wang** [comment]
Decision is to keep in MathML full but note in main spec that non core features will require polyfills so you may not want to use them. https://lists.w3.org/Archives/Public/public-mathml4/2019Mar/0026.html

**Comment by fred-wang** [comment]
Resolution:
  https://github.com/mathml-refresh/mathml/issues/4#issuecomment-475505979

Specification:
  Add deprecation warning in Full?

Implementation:
  WebKit: https://bugs.webkit.org/show_bug.cgi?id=196142
  Firefox: https://bugzilla.mozilla.org/show_bug.cgi?id=1548529
  Not implemented in Chromium.

Polyfill:
  Convert to length values
  Maybe using CSS variables to make values configurable?

Tests:
  - Remove WPT tests or check that these values are not supported.

**Comment by NSoiffer** [comment]
MathPlayer uses the values 4.0, 7.5, 12.0.  I'm not certain, but it appears these values are a percent of the font size. The default value is 5.0.

Here's an example from MathPlayer:
```
<math display='block' xmlns='http://www.w3.org/1998/Math/MathML' mathsize="24pt">
 <mrow>
  <mfrac linethickness="thin">
   <mn>5</mn>
   <mn>888</mn>
  </mfrac>
  <mfrac>
   <mn>5</mn>
   <mn>888</mn>
  </mfrac>
  <mfrac linethickness="medium">
   <mn>5</mn>
   <mn>888</mn>
  </mfrac>
  <mfrac linethickness="thick">
   <mn>5</mn>
   <mn>888</mn>
  </mfrac>
  </mrow>
</math>
```
![img](https://user-images.githubusercontent.com/1545836/58051484-2b1fc280-7b07-11e9-8059-013c53126809.png)

I'm not particular fond of the MathPlayer values. Here's a modification that uses the values @fred-wang  proposed:
```
<math display='block' xmlns='http://www.w3.org/1998/Math/MathML' mathsize="24pt">
 <mrow>
  <mfrac linethickness="0.5">
   <mn>5</mn>
   <mn>888</mn>
  </mfrac>
  <mfrac>
   <mn>5</mn>
   <mn>888</mn>
  </mfrac>
  <mfrac linethickness="1">
   <mn>5</mn>
   <mn>888</mn>
  </mfrac>
  <mfrac linethickness="2">
   <mn>5</mn>
   <mn>888</mn>
  </mfrac>
  </mrow>
</math>
```
![img](https://user-images.githubusercontent.com/1545836/58051936-4dfea680-7b08-11e9-9d59-8f8605a2648d.png)

More realistically, here it is at 12pt:
![img](https://user-images.githubusercontent.com/1545836/58051993-81d9cc00-7b08-11e9-8058-85149127d5c3.png)

Which seems fine to me. 10pt renders similarly (i.e, the line thickness is distinguishable).

**Comment by fred-wang** [comment]
@davidcarlisle As said in https://github.com/mathml-refresh/mathml/issues/4#issuecomment-472788833 this was removed from core. Please do the update in mathml full, if any before removing the label.

**Comment by NSoiffer** [comment]
As per my action item, MathJax uses these values: 0.67, 1, 1.67. These seem to be multiples of the rule thickness.

**Comment by fred-wang** [comment]
Firefox and WebKit use values .5, 1 and 2:
https://searchfox.org/mozilla-central/source/layout/mathml/nsMathMLmfracFrame.cpp#31
https://trac.webkit.org/browser/webkit/trunk/Source/WebCore/mathml/MathMLFractionElement.cpp#L63

**Comment by fred-wang** [comment]
It seems MathJax, Firefox and WebKit values are relatively close so I'm happy to take any of them.

It looks like MathJax does not use the factor for medium/thin and thick/medium, but that's also the case for the CSS-based proposal #7

**Comment by fred-wang** [comment]
https://lists.w3.org/Archives/Public/public-mathml4/2019Jun/0013.html 

NO Objections - ADOPTED  067, 1.0, 1.67

**Comment by fred-wang** [comment]
Polyfill:

    window.addEventListener("load", function() {
        const namespaceURI = "http://www.w3.org/1998/Math/MathML";
        Array.from(document.body.
                   getElementsByTagNameNS(namespaceURI, "mfrac")).
            forEach(mfrac => {
                if (!mfrac.hasAttribute("linethickness"))
                    return;
                var value = mfrac.getAttribute("linethickness").
                    replace(/thin|medium|thick/, match => {
                        switch (match) {
                        case "thin": return "67%";
                        case "medium": return "100%";
                        case "thick": return "167%";
                        }
                    });
                mfrac.setAttribute("linethickness", value);
            });
    });

**Comment by fred-wang** [comment]
Tested by https://w3c-test.org/mathml/presentation-markup/fractions/frac-linethickness-001.html

**Comment by NSoiffer** [comment]
In "full", 3.3.2 (mfrac) for `linethickness` mentions "thin", etc. The attr is marked as "core", but the named values are "not-core" and should probably have that tag. Currently it says (with poor English):
> Note: MathML Core does only allow [<length-percentage>](https://www.w3.org/TR/css-values-3/#typedef-length-percentage) values.

So "does only allow" ->"only allows" and somehow "not-core" should get added.

**Comment by davidcarlisle** [comment]
@NSoiffer 

> So "does only allow" ->"only allows" and somehow "not-core" should get added.

agree with english change, for marking, we could either mark the attribute as something like `restricted-core` or we could try to mark the individual named lengths as not-core (that's probaby more disruptive)
