### ISSUE TITLE
Table of content is broken / Improve ids

### ISSUE THREAD

**Issue by fred-wang** [w3c/mathml#41]
For example if you mfrac, you go to https://mathml-refresh.github.io/mathml-core/#SS3.SSS2 which is "User Agent Stylesheet for MathML ". I guess this happened because we merged all in a single page. We should probably rationalize the ids so that we have stable links we can use as references (e.g. from WPT tests). I'm assigning to David.

See also #32

cc @rwlbuis

**Comment by fred-wang** [comment]
@davidcarlisle this is fixed, right?

**Comment by davidcarlisle** [comment]
I hope so, closing,
