### ISSUE TITLE
Intent should prefer reference over repeating a literal

### ISSUE THREAD

**Issue by davidfarmer** [w3c/mathml#422]
In the intent example "x prime" the intent is given as
`intent="x-prime"`.

I understand that this will work, but I'd like to include a strong suggestion that
a better way is `intent="$a-prime"` , where `arg="a"` has been added to the `<mi>x</mi>`.
It is generally bad practice to repeat the literal instead of referencing it.  If the `x`
were changed to another letter, then the intent would also have to be changed.
(Use of literal makes sense in cases like the Bell number occurring a couple
of examples later.)

That example also contains an error:  the default reading writes `f superscript...` instead of `x superscript...`.

https://github.com/w3c/mathml/blob/8971e48e83c489723841394b78bba84cc58800e7/src/mixing.html#L293

**Comment by davidcarlisle** [comment]
@davidfarmer  `intent="$a-prime"` would be an invalid reference to a non-existing `arg="a-prime"` as `-` is a name character.

You could use `intent="prime@postfix($a)"`  but I believe the idea here was to show _x'_ as "just another name" rather than the result of a mathematical operation denoted by prime being applied to _x_.

> That example also contains an error: the default reading writes f superscript... instead of x superscript....

oops, fixed at d726ea8 thanks

**Comment by dginev** [comment]
<table>
<tr>
<td>Literal + Defaults</td>
<td>

```xml
<msup intent="_($base,$script)">
  <mi arg="base">x</mi>
  <mo arg="script">&#x2032;</mo>
</msup>
```

</td></tr>
<tr><td>

Literal override

</td><td>

```xml
<msup intent="_($base,$script)">
  <mi arg="base">x</mi>
  <mo arg="script" intent="_prime">&#x27;</mo>
</msup>
```

</td></tr>
<tr><td>
Literal, international override

</td><td>

```xml
<msup intent="_($base,$script)">
  <mi arg="base" intent="_хикс">x</mi>
  <mo arg="script" intent="_прим">&#x2032;</mo>
</msup>
```

</td>
</tr>
</table>

**Comment by davidcarlisle** [comment]
@dginev  ah yes , the current draft only has one small example of `_(` we need to add more words about the possiblities here.

**Comment by NSoiffer** [comment]
I like @dginev's example. We should add this or something similar to the spec to indicate the options.
