### ISSUE TITLE
Deprecate <none> element

### ISSUE THREAD

**Issue by dginev** [w3c/mathml#428]
I have recently started to wonder if the `<none>` element has outlived its usefulness.
- The current MathML Core [description of `<none>`](https://w3c.github.io/mathml-core/#dfn-none) states:
   > The empty `<mprescripts>` and `<none>` elements are laid out as an `<mrow>` element.
- The naming of `<none>` appears inconsistent with the rest of Presentation MathML, as one would have expected `<mnone>`.
- MathML Core also states that "[Unknown MathML elements](https://w3c.github.io/mathml-core/#dfn-unknown-mathml-element) behave the same as the [`<mrow>`](https://w3c.github.io/mathml-core/#dfn-mrow) element"
    - which induces backwards compatibility in a world where `<none>` is relegated to unknown, and `<mrow>` is recommended in its place.

---

**Proposal:** Deprecate and ultimately remove `<none>`, in favor of using an empty `<mrow>` element in its place.

---

P.S. There may be reasons to preserve `<none>` that I am not yet aware of - comments are most welcome. I also suspect this suggestion comes too late for MathML 4, and will only be addressed in work following that milestone.

**Comment by NSoiffer** [comment]
> The current MathML Core [description of <none>](https://w3c.github.io/mathml-core/#dfn-none) states:
> The empty <mprescripts> and <none> elements are laid out as an <mrow> element.

That description only applies when they are not in an `mmultiscripts`. Prior to that statement, it says:
>  ...then they are laid out according to the CSS specification where the corresponding value is described. Otherwise, the layout below is performed. 

I don't know whether your proposal presents a problem with that description.

An empty `mrow` is sometimes used to indicate a slot to be filled in, so potentially it means something different than `none`.

`none` is also used by elementary math in `msrow`, `mscarries`, and `mscarry` to indicate an empty column.  These uses might be compatible with your proposal, but I'd need to think about it more.

As for why it is "none" and not "mnone", I don't remember. There are a few other elements that don't start with 'm' that are allowed in presentation: `semantics`, `annotation`, and `annotation-xml`. One could argue they straddle the line between presentation and content MathML and hence aren't strictly part of presentation MathML.

As for timing, I think now is the time to make the change if people think it is appropriate: do it before core is an official rec. This probably should be a MathML core issue.

**Comment by dginev** [comment]
> That description only applies when they are not in an mmultiscripts. Prior to that statement, it says:
> >    ...then they are laid out according to the CSS specification where the corresponding value is described. Otherwise, the layout below is performed.

I am usually quite worried that I do not read the spec documents with sufficient context, but I really tried for this issue. The `...` you added disguises a good point of clarity:
> If the `<mmultiscripts>`, `<mprescripts>` or `<none>` elements **do not** have their computed [display property](https://w3c.github.io/mathml-core/#dfn-display-property) equal to **block math or inline math** then they are laid out according to the CSS specification where the corresponding value is described.

Emphasis mine. The way I read that, it is a generic escape hatch clause, where non-MathML display modes are delegated to CSS, while the MathML display modes are specified directly after. So, the current MathML Core will give `<none>` the empty `<mrow>` layout, wherever it gets used in MathML, as long as the implied display is inline-math or block-math.

There is additional clarity added a little further down in the text: *"In order to keep the algorithm simple, no attempt is made to handle empty or `<none>` scripts in a special way."*

> An empty mrow is sometimes used to indicate a slot to be filled in, so potentially it means something different than none.

Hm, that seems a little odd. And maybe non-standard? An empty `<mrow>` could be useful for a variety of reasons, so generally reserving it only for "fill-able blanks" could be a bit limiting.

> This probably should be a MathML core issue.

I was hoping to suggest the change for MathML in general. Making it Core-specific could leave the impression that the element may return to Core at a later date, and is just temporarily moved to Full. Certainly, this may be the practical resolution of the issue at the end of discussion, but I'd like to at least try for "general deprecation" first.

**Comment by dginev** [comment]
Noting here that there was general consensus to proceed with the deprecation in both Full and Core, during our meeting on November 17th, 2022.

**Comment by NSoiffer** [comment]
Spec is updated.
