### ISSUE TITLE
Inference Rules and TeX Semantic Package

### ISSUE THREAD

**Issue by AaronNGray** [w3c/mathml#431]
I am wondering if there will be any support in MathML for Inference Rules particularly the type used in Type Theory using the TeX Semantic Package.

There are a large number of papers written in the feilds of Type Theory and Proof Theory using the CTAN TeX Semantic Package :-

https://ctan.org/pkg/semantic?lang=en

http://mirror.its.dal.ca/ctan/macros/latex/contrib/semantic/semantic.pdf

AFAICT most if not all symbols used in all the papers I have read have support in UNICODE. ANd are possibly all within those outlined in MathML Core :-

https://www.w3.org/TR/mathml-core/#operator-dictionary-human

The layout is the main issue being able to stack inference rules to show derivation arguments and also things like floating premisies which I have seen before and just came up on a google search :-

https://tex.stackexchange.com/questions/478383/semantic-package-floating-premises-with-nested-inference

In practical terms it would be nice to have support for inference rules which dont even seem to be in version 4 of the MathML spec :-

https://w3c.github.io/mathml/

To have support for both static HTML MathML and also for dynamic editors, and from XML, and maybe even from RDF/OWL style semantics. I have long been loking into sematic specifcation of programming languages using inference systems and can envisenge the stage where we can dynamically edit language semantic specifications, and convert those specifications into a form transferable to a proof system and also semi automatic generation of type checking, inference systems, and code generation.

So it would be wonderful to have support simular to the TeX CPAN Semantic Package for Type and Proof Theorists to share work on the web but on another level semantically.

**Comment by dginev** [comment]
As a quick first comment:

A brief test with tex4ht shows that it can convert some of the simpler inference rules, using `<mfrac>` to present them in MathML. Specifically, I tried:
```tex
\[  \inference {A \quad B}{C}[d]  \]
```

Another possible approach with the currently available markup is to use an mtable with `mtd` cells with a set bottom border.

I think the "floating" effect can also be recreated with available markup (e.g. strategic use of `<mspace>`, or an empty `<mtd>`), or with some stylistic padding, maybe via CSS.

Separately, it would be interesting to consider a "content dictionary" for inference rule `<csymbol>`s (maybe one exists already?), and how that can be cross-referenced with the presentation. That is a domain where latexml has had some prior work.

So, on a first reading, I think it would be worthwhile to first try and implement support for the TeX package in one of the existing conversion tools to HTML, and then report back to the group where the available markup may be currently lacking.

**Comment by AaronNGray** [comment]
@dginev - Great, do you think using these techniques it might be possible to support the direct TeX syntax and semantics of the CTAN Semantic Package at all ? As people are familuar with this already.

**Comment by dginev** [comment]
@AaronNGray yes, I think the current model of MathML Core + Strict Content MathML would be able to support quite a lot more than what conversion tools cover today. The `semantic.sty` macros ought to be achievable, since previous work in the group has had some focus on formal logic already.

And better if it did, since introducing new domain-specific elements (or other markup) poses a burden on various development teams (browsers, generators, consumers, accessibility tools, ...)

I've cross-referenced this issue to our open issue on `semantic.sty` in latexml, but there are 10+ other converters you may choose from as well, some of which may have already added some support for the package.

**Comment by AaronNGray** [comment]
@dginev thanks for making the link ! Would it be posible to list the other packages when you have some time please.

**Comment by dginev** [comment]
> Would it be possible to list the other packages when you have some time please.

I keep a partial table of known conversion engines maintained after 2020, but I may be missing some. And naturally you would have to go and check if each one has looked into `semantic.sty` or not.

<table><thead>
<th>software</th><th>language</th><th>homepage</th>
</thead><tbody>
<tr><td>latex2html</td><td>perl</td><td><a href="https://github.com/latex2html/latex2html/">link</a></td></tr>
<tr><td>latexml</td><td>perl</td><td><a href="https://math.nist.gov/~BMiller/LaTeXML/">link</a></td></tr>
<tr><td>lwarp</td><td>TeX, lua</td><td><a href="https://www.ctan.org/pkg/lwarp">link</a></td></tr>
<tr><td>pandoc</td><td>haskell, lua</td><td><a href="https://pandoc.org/">link</a></td></tr>
<tr><td>plastex</td><td>python</td><td><a href="http://plastex.github.io/plastex/">link</a></td></tr>
<tr><td>tex2page</td><td>scheme</td><td><a href="http://ds26gte.github.io/tex2page/index.html">link</a></td></tr>
<tr><td>tex4ht</td><td>TeX, lua</td><td><a href="https://tug.org/tex4ht/">link</a></td></tr>
<tr><td>tralics</td><td>C++</td><td><a href="http://www-sop.inria.fr/marelle/tralics/">link</a></td></tr>
<tr><td>HeVeA</td><td>OCaml</td><td><a href="http://hevea.inria.fr/">link</a></td></tr>
<tr><td>TTH</td><td>C</td><td><a href="http://hutchinson.belmont.ma.us/tth/">link</a></td></tr>
<tr><td>LaTeX.js</td><td>JavaScript</td><td><a href="https://latex.js.org/">link</a></td></tr>
</tbody></table>

Let me know if this helps - and I think we can start thinking about closing this specific issue for now.

**Comment by AaronNGray** [comment]
@dginev - Great thank you ! I will go through them when I get some time spare.

**Comment by dginev** [comment]
@AaronNGray enjoy. Let us reopen here when it becomes clear the currently available markup isn't sufficient. You're welcome to drop us a line on the latexml issue if you'd like to discuss the specifics on our end.
