### ISSUE TITLE
Conflicting intents: who wins?

### ISSUE THREAD

**Issue by NSoiffer** [w3c/mathml#439]
This is somewhat related to the initial question in #435 (but the discussion ended up focusing on hints).

This came up as I was trying to hook up a given `intent` to its matching built-in core definition. The following example is a bit contrived, but I suspect it is real and comes up. Suppose we have the following MathML and that `determinant` is a core intent. I'm using a hypothetical `*` to represent the children of the `mtable`, but feel free to think of it as the equivalent `this` or `self`.
```
<math display="block">
 <mrow intent="determinant($M)">
  <mo>|</mo>
  <mtable arg="M" intent="lines(*)">
   <mtr>
    <mtd><mi>a</mi></mtd>
    <mtd><mi>b</mi></mtd>
   </mtr>
   <mtr>
    <mtd><mi>c</mi></mtd>
    <mtd><mi>d</mi></mtd>
   </mtr>
  </mtable>
  <mo>|</mo>
 </mrow>
</math>
```

The outer `mrow` has a known way to speak the `mtable` ("row 1 ..., row 2 ..."),
but the intent on the `mtable` is saying something different. There are two cases to consider here:
1. `lines` is a core intent
2. `lines` is an open intent

Does the core `determinant` intent win out or does the inner `lines` intent win out (never, always, only if it is core)?

Does anyone have a better example? I don't think an example like the following is the same.
```
<mrow intent="star@infix($x, $y)>
  <mi arg="x">x</mi>
  <mo intent="convolution">⋆</mo>
  <mi arg="y">y</mi>
</mrow>
```
In this case, the inner intent is never referenced. In the first example, it is explicitly referenced.

**Comment by davidcarlisle** [comment]
I think there are some unresolved issues for similar cases, but is this really conflicting?

```
<mrow intent="determinant($M)">
  <mo>|</mo>
  <mtable arg="M" intent="lines(*)">
```

I'd expect the core rule for determinant to apply and say "the determinant of"  then $M gets referenced, 
it could be  `<mi arg="M">M</mi>` so just adding "M", if it was `<mtable arg="M">` it would trigger some system specific tabular reading, as it has intent= it presumably reads as "line 1, a, b; line 2, c, d"  which may sound a bit odd after  "the determinant of"   but fits what was requested I think?

**Comment by dginev** [comment]
As David mentioned, I don't think there is any conflict here.

> The outer mrow has a known way to speak the mtable ("row 1 ..., row 2 ..."),

This is system-specific behavior, in contrast to spec-prescribed behavior. If a system knows how to deal with an mtable *in the context of* a "determinant" intent, it can use that enhanced behavior. Else, the intent annotation "wins" (i.e. one gets the "baseline narration").

Edit: `lines` does not qualify as an Open intent concept using the "encyclopedic names" rule, so I am unsure what the "Core team" wants to do with such custom keywords.

**Comment by davidcarlisle** [comment]
by now standard disagreement with Deyan's reading of the last point but we can address that elsewhere but I think intent should always win (as otherwise why did the author use it)

so `<mtable arg="M">`   I agree can use:

> If a system knows how to deal with an mtable in the context of a "determinant" intent, it can use that enhanced behavior.

But as you have `intent=lines` it should read the mtable using that intent, but either way I don't see this as  a conflict with the outer intent on the mrow.

**Comment by NSoiffer** [comment]
Deyan: Assuming determinant is in core, than being in core means there is an expected way that it is spoken. Although there are many variants on how to speak the determinant, I don't think anyone would agree that "line" or "case" (if the `mtable` had used "case") is appropriate. So I don't see this as "enhanced" behavior, reading it appropriately is _expected_ behavior. 

David: if seems you are saying that the inner intent should win? That is, although `determinant` has a way to say some content, if that content has intent on it, that inner intent should win. It is not clear to me that is the right thing. I wish I could think of more cases. And maybe this isn't really a true case here because if we have a way to reference the children of the `mtable`, then the intent on the `mtable` is never referenced. It is more like ignoring the `intent`s on the `|` in the following example because they aren't referenced in the outer level:
```
 <mrow intent='absolute-value($x)'>
  <mo intent='vertical bar'>|</mo>
  <mi arg='x'>x</mi>
  <mo intent='vertical bar'>|</mo>
 </mrow>
```
@Deyan: Do you agree the intent's on the `|` should be ignored because they aren't referenced? Or is this another area where we disagree about how intent should work?

Note: I actually do see "lines" or some similar name as part of core along with "cases" and "equation" (or some similar names). If one is doing a derivation, the derivation consists of lines or steps. So maybe I should have said "derivation" or some more generic term.

**Comment by davidcarlisle** [comment]
> David: if seems you are saying that the inner intent should win?

Not really, I just don't see they are in conflict. just as if you have 

```
<mfrac intent="divdes($a,$b)">
<mrow arg="a" intent="equals(x,y)"><mi>x</mi><mo>=</mo><mi>y</mi></mrow>
<mrow arg="b" intent="equals(x,y)"><mi>x</mi><mo>=</mo><mi>y</mi></mrow>
</mfrac>
```

You may suspect this mfrac is really some kind of proof derivation but if the intents mark it up as a division of equalities then you just have to read as instructed.

The determinant example is the same, there is not any conflict: it's marking up to be read as  the determinant of a list of derivation lines which is probably mathematcally nonsense but that's not our problem.

**Comment by dginev** [comment]
> Assuming determinant is in core, then being in core means there is an expected way that it is spoken.

Yes, but intent is still compositional over the argument references - the *spec* should not pose additional requirements on how one speaks arguments hidden behind `$references`, even if *a system* may have enhanced contextual/case-by-case reasoning that depends on what hides behind a `$reference`.

> Although there are many variants on how to speak the determinant, I don't think anyone would agree that "line" or "case" (if the mtable had used "case") is appropriate.

The author that wrote that annotation would disagree. In this case the author was you, so you should take this up with yourself. I wouldn't have used `lines` in the first place, but had I used it I would have had a good reason to.

> So I don't see this as "enhanced" behavior, reading it appropriately is expected behavior.

We have consensus on "bad narration is bad". Also

> reading it appropriately is expected behavior.

*Given* such a premise *then* please notice that the expected behavior *requires* examining the presentation tree in certain cases where a system is attempting to be "flawless", because ostensibly these two determinant applications may have different preferred speech, while having identical `intent` annotations:

```xml
 <mrow intent="determinant($M)">
  <mo>|</mo>
  <mtable arg="M"> ... </mtable>
  <mo>|</mo>
 </mrow>
```

```xml
 <mrow intent="determinant($M)">
  <mi>det</mi>
  <mo>(</mo>
  <mi arg="M">M</mi>
  <mo>)</mo>
 </mrow>
```

> @deyan: Do you agree the intent's on the | should be ignored because they aren't referenced?

For the application of "generating accessible speech starting from the root `<math>` node" - yes.
For a MathML editor where an AT navigates the raw presentation tree as the user is editing it, it's a little more subtle.

**Comment by davidcarlisle** [comment]
@dginev 
> For a MathML editor where an AT navigates the raw presentation tree as the user is editing it, it's a little more subtle.

Yes, not only editors, presumably also in browser contexts where you can navgate the expression you could "land on" the `|` and (presumably?) the `intent` would then have an effect.

**Comment by davidcarlisle** [comment]
Neil is happy to close (he says)
