### ISSUE TITLE
hints (and is-a properties) on intents other than function heads

### ISSUE THREAD

**Issue by davidcarlisle** [w3c/mathml#440]
The current grammar only allows hints on function heads so you can do

`<mrow intent="foo@silent(x)"`

but not

`<mi intent="foo@silent">foo</mi>`

The grammar in PR #438 allows `@` hints after any literals and concept names, partly as it seemed more natural to me at the time, and partly to make it easier to contemplate merging with `:` properties, which I think have to be allowed after concept names.

But are the following hints legal and do they have the suggested meanings? (If you don't like `@` examples, substitute `:property` as the question is about the implied scope, not the specific annotation)

1.
```
<mrow intent="$f@postfix($x)">
 <mi arg="f">foo</mi>
 <mi arg="x">x</mi>
</mrow>
```
  `x foo`

2.
```
<mrow intent="$f($x)">
 <mi arg="f" intent="foo@postfix">foo</mi>
 <mi arg="x">x</mi>
</mrow>
```
  `x foo`?

3.
```
<mrow>
 <mi intent="foo@postfix">foo</mi>
 <mi>x</mi>
</mrow>
```
  `x foo`??

4.
```
<mrow>
 <mi intent="foo@silent">foo</mi>
 <mi>x</mi>
</mrow>
```
  `x` ?

--------

2 seems quite natural to me, as `$f` can be substituted by the (possibly implicit) intent of the referenced element so `$f($x)` is `foo@postfix(x)` using explicit intent from arg=f and implicit intent from arg=x.

3 is more speculative as it is giving a postfix hint with no indication what argument it is supposed to postfix. perhaps this should be invalid or valid but ignored (ie fixity hints only have effect if eventually substituted into a function head as in 1 or 2), or we have to specify what it means.

4 is structurally like 3 but `silent` doesn't require inferring an argument so seems much easier to specify how it works.

**Comment by dginev** [comment]
Two other natural fixity alternatives possible with the current spec:
```xml
<mrow intent="_($x,$f)">
 <mi arg="f">foo</mi>
 <mi arg="x">x</mi>
</mrow>
```
x foo

```xml
<mrow>
 <mi intent="_">foo</mi>
 <mi>x</mi>
</mrow>
```
x

---

As to `is-a`, if one takes the view that it implies an [accessible description](https://www.w3.org/TR/accname-1.2/#dfn-accessible-description) available on demand, then it should be positioned on the exact node it describes. And indeed we may have three ways to achieve that - either via a self-reference such as `$this:property` or via a regular reference `$descendant:property`, or if there is no node to reference at all (e.g. an invisible times that did not have an invisible character in an `<mo>`), it would annotate a literal. 

Here is that last example:
```xml
<mrow intent="times:invisible-operator(x,y)">
 <mi>x</mi>
 <mi>y</mi>
</mrow>
```

**Comment by brucemiller** [comment]
Nice examples, all round!

I think @dginev 's examples have straightforward interpretations; and I also think `isa` properties should follow the rule "lower is better", and wouldn't expect any conflicts from that.

OTOH, @davidcarlisle 's example 4 shows why allowing the `silent` `hint` on tokens is reasonable, while 2 and 3 show why the others might be confusing. The expected reading of 2 might reasonably be inferred, but 3 only with parsing (and the hint makes parsing even more confusing!).

We could say "you don't always get what you want".  Or, we could say that `hint` should only be used in applications (as the current draft has);  but perhaps `silent` should be an `isa` property, rather than a hint, then it is allowed anywhere.

**Comment by davidcarlisle** [comment]
@dginev wrote

> `intent="_($x,$f)"``

yes the user can always force more or less any literal string using `_` but at the cost of discarding all other information. The current spec warns of the possible downsides of this, which is wording I think we should keep. 
https://w3c.github.io/mathml/#mixing_intent_warning

on is-a

> should be positioned on the exact node it describes.

yes agreed which is why I allowed `:` after all concepts not just function heads, but not allowing hints in the same places isn't possible if `:` and `@` are merged.

I should say that as of a day or so ago, mathcat does accept `foo@silent` on leaf nodes (but I think silently ignores arity hints if not used on a function head)

@brucemiller 

> The expected reading of 2 might reasonably be inferred, but 3 only with parsing (and the hint makes parsing even more confusing!).

yes. I'd quite like 2 to work, so you can say the default intent for `<mo>=</mo>` is `<mo intent="equals@infix">=</mo>` but I think somehow we need to say 3 isn't supported and the hint is not used if the intent is not used as a function head. But perhaps that is too complicated and it should be made syntactically invalid. and `@infix` only being allowed as part of an explicit function head

**Comment by dginev** [comment]
> yes the user can always force more or less any literal string using _ but at the cost of discarding all other information.

More shuffled than lost, especially with [a workable convention](https://dginev.github.io/mathml-docs/intent-to-content#example-transformations-to-operator-trees) in place.

**Comment by brucemiller** [comment]
Right; but silent makes sense anywhere.  So, if we want to preserve the `hint|isa` distinction in the grammar, we'd probably want to make `silent` a property.  Otherwise, we could still merge `hint|isa`, but make the distinction in the text to the effect that "arity hints" may be ignored except in a function application.

**Comment by davidcarlisle** [comment]
> Right; but silent makes sense anywhere. So, if we want to preserve the `hint|isa` distinction in the grammar, we'd probably want to make `silent` a property. Otherwise, we could still merge `hint|isa`, but make the distinction in the text to the effect that "arity hints" may be ignored except in a function application.

Yes, the latter is more or less mathcat's current iteraton and I opened this to see if this is the way we want to specify things.

I guess we can't really decide until we decide whether to merge `:` and `@` if we do I think all hints have to be gramatcally valid anywhere, but we could say some are ignored or we could make arity hints a separate syntact class and restrict them.  I think (perhaps) I prefer a simpler grammar that allows  all hints everywhere, even if that means coming up with some careful wording on when they have an effect

**Comment by davidcarlisle** [comment]
@dginev 

> especially with [a workable convention](https://dginev.github.io/mathml-docs/intent-to-content#example-transformations-to-operator-trees) in place.

ah that's where that is, thanks! I was looking for that the other day.  We should put some version of that in the spec (perhaps as a mapping to cleaned up intent rather than to content mathml?) but while I agree such a mapping would help a lot.  If I have  a `factorial($n)` but want it read as "factorial of n"  not "n factorial" I _much_ prefer keeping the structure of a factorial function call, just adding a speech hint, `factorial@function($n)` than obscuring the structure as `_factorial($n)` (which reads correctly, but loses the `factorial` concept) or `_(factorial,_of,$n)` (which looks weird, but does read correctly (in English), and only regains the `factorial($n)` by applying your normalisation algorithm).

In the intent examples I have used  `_(` in some places eg  `intent='_($op, _of, $arg)'` at [IDxtranspose](https://mathml-refresh.github.io/intent-lists/intent3.html#IDxtranspose) as I think we should show this (and some version of your algorithm to normalise it) but hints should be preferred in most cases.

**Comment by dginev** [comment]
@davidcarlisle 
It takes some getting used to but `_(factorial,_of,$n)` has great properties and brevity. 
As does `_($n,factorial)`. Both of which force the order of the pieces - and should be used only when forcing is needed.

Meanwhile we still have `factorial($n)` where the "baseline narration" intent algorithms (and AT freedoms) continue to apply, assuming that factorial remains a Core concept.

P.S. I can move the doc somewhere better, please email me if you have a good destination/organization in mind, which I can follow.

**Comment by davidcarlisle** [comment]
> It takes some getting used to but _(factorial,_of,$n) has great properties

I remain unconvinced (and I have not seen anyone else advocate for this over `@hints`). It's good that `_(` is available as a last resort when you really have to force a specific text in a specific language, but it doesn't appear to have any actual advantages, and several disadvantages compared to `factorial@function($n)`  in this case.

> P.S. I can move the doc somewhere better, please email me if you have a good destination/organization in mind, which I can follow.

The doc  is in the right place for a document (I had just forgotten it was a document, and was looking in issues here) but I think probably some parts of that could be in chapter 5 of the main spec, something after the warning about not over-using `@hints` and `_literals` we could specify some version of your algorithm as an `intent` to `intent` mapping that would map both `_(factorial,_of,$n)` and `factorial@function($n)` to `factorial($n)`.

If we had such  normative mapping in the spec it would make the `_(` forms a lot less objectionable as they would still correspond to a defined meaning.

**Comment by davidcarlisle** [comment]
@dginev  
> More shuffled than lost, especially with [a workable convention](https://dginev.github.io/mathml-docs/intent-to-content#example-transformations-to-operator-trees) in place.

I just realised why I keep losing that, it's in a fork of w3c/mathml-docs, do you want to make a PR to push to W3C so it's in the main table of contents (or, if you'd rather keep it in your fork, just add the above link to the w3c mathml-docs index page).

It's useful to use forks for short term experiments but hard to keep track of them over an extended period.

**Comment by davidcarlisle** [comment]
https://w3c.github.io/mathml/#mixing_intent_grammar

Now has `:`and `@`  merged and allowed after any term not  just function heads,  so closing this.

There are still open issues about the processing order for multiple properties or properties on references, but discussion can happen in #449
