### ISSUE TITLE
Tricky fixity+silence in intent expressions

### ISSUE THREAD

**Issue by dginev** [w3c/mathml#442]
There are some tricky cases possible with the current intent grammar that I wanted to enumerate. Maybe one conclusion is to warn against mixing fixity hints and "silent" directives (either `@silent` or `_`).

Maybe another conclusion is to not over-rely on any single aspect of the intent syntax, without taking stock of all components of a given expression (as well as the presentation context). A weaker form of this is that "silence and fixity hints have a tricky interplay", which complicates implementation.

A third perspective is that while these misuses of the intent features *should* create usable narration, they will not imply any usable content-near expressions. They will also induce the wrong "nagivation" in accessible tree walks, so I think we may want to consider them "annotation errors" in some capacity.

Tricky fixity examples:

* infix, actually prefix
    ```xml
     intent="not@infix(_,A)"
     intent="not@infix(empty@silent,A)"
    ```
    - expected narration: "not A"
* infix, actually postfix
    ```xml
    intent="factorial@infix(x,_)"
    intent="factorial@infix(x,empty@silent)"
    ```
    - expected narration: "x factorial"
* prefix, actually infix
    ```xml
    intent="_(x,plus@prefix(y))"
    intent="pieces@silent(x,plus@prefix(y))"
    ```
    - expected narration: "x plus y"
* prefix, actually postfix
    ```xml
    intent="_(x,factorial@prefix(_))"
    intent="pieces@silent(x,factorial@prefix(empty@silent))"
    ```
    - expected narration: "x factorial"
* postfix, actually infix - exercise to the reader, just invert the prefix example
* postfix, actually prefix - exercise to the reader, just invert the prefix example

---

Separately, I am also wondering what are the technical differences between the various empty prefix forms, if any. For example:

base | empty apply | apply over silent argument
  :--- | :--- | :-- 
 `not` | `not()` | `not(_)`
 `not@prefix` | `not@prefix()` | `not@prefix(_)`
 `not@function` | `not@function()` | `not@function(_)`
 `not@postfix` | `not@postfix()` | `not@postfix(_)`
 `not@infix` | `not@infix()` | `not@infix(_)`

Since some of these may depend on tree context, I am thinking of say the minimal:
```xml
<math>
  <mo intent="<value here>">!</mo>
  <mi>P</mi>
</math>
```

I'll leave things here for now. I hope these examples help to flesh the questions out sufficiently for a discussion.

**Comment by davidcarlisle** [comment]
I suspect most of the examples you give are necessarily valid but just unhelpfully obscure, so all  we could do is warn against it.  Just as for mathml presentation it's valid to have an expression just consisting of empty `<mi></mi>` or all  in `<mphantom>` you can not totally legislate against nonsense.

Of the examples, you could make it invalid to use fixity hints on an empty argument list but it would complicate the grammar and as you show someone could still do `foo@infx(_,_)` even if `foo@infix()` was made invalid.

`_(_,_,_)`  would be valid even if we had no `@`  or `:` annotations.

**Comment by dginev** [comment]
FWIW `_(_,_,_)` implies some kind of silence in my mind, but it is unclear how long of a silence. 

Scenario 1: normalized to "nothing at all" (i.e. discarded) following
  - "_() implies pieces" and then 
  - each piece has empty content, hence discarded 
  - leading to the full construct getting discarded.

Scenario 2: normalized to "three brief pauses", following
  - "_() implies pieces" and then
  - each piece gets narrated/vocalized as a unit of a pause.
  - the second direction leads to some curious imaginary outcomes, such as:
    ```xml 
     <mo intent="_:enspace(_)">␣</mo>
     <mo intent="_:emspace(_,_)">␣␣</mo>
    ```

**Comment by davidcarlisle** [comment]
currently mathCAT does

```
MathML: <math><mi intent="_(_,_,_)">x</mi></math>
Speech: ''
```

but I don't see it's any different to the examples you give (which aren't all accepted by mathcat currently as multiple and leading `:` error)  You will always be able to generate deliberately obfuscated examples.

**Comment by davidcarlisle** [comment]
`<mo intent="_:enspace(_)">␣</mo>` produces the same but currently `:xxxx` annotations are accepted but ignored so it is treated like `<mo intent="_(_)">x</mo>`

**Comment by dginev** [comment]
>  You will always be able to generate deliberately obfuscated examples.

Right. The usefulness of drawing the line more tightly on what is grammatical is that AT vendors and adopters alike could have a clearer indication which syntax is "error recovery" and which syntax is "intended grammatical function". 

For example, if we only had intent terms - without any advanced annotations - none of my examples would have been possible.

**Comment by davidcarlisle** [comment]
> For example, if we only had intent terms - without any advanced annotations - none of my examples would have been possible.

sure but as I showed someone trying to obfuscate could use `_` or `__` or `any-unassigned-unicode-codepoint` or ....  The details change a  bit but the basic problem applies to all languages and isn't soluable in any real way.

**Comment by davidcarlisle** [comment]
I think it matters to decide if you allow  space after `:` as it affects how you search in files, can you look for `:unit` or do you have to regex search for `:\s*unit`.  But if someone generates some deliberately obscure mess of white space, underscores and brackets, just let a valid speech algorithm run and what comes out comes out: it really doesn't matter if that is an empty string or nonsense like "pause of pause comma pause pause pause comma pause"

**Comment by davidcarlisle** [comment]
```
MathML: <math><mo intent="foo(_,_,_)">x</mo></math>
Speech: 'foo of,   comma   comma'
MathML: <math><mo intent="foo@prefix(_,_,_)">x</mo></math>
Speech: 'foo      ,'
MathML: <math><mo intent="foo@infix(_,_,_)">x</mo></math>
Speech: ',   foo   foo  ,'
MathML: <math><mo intent="foo@postfix(_,_,_)">x</mo></math>
Speech: ',       foo'
MathML: <math><mo intent="foo@silent(_,_,_)">x</mo></math>
Speech: ''
```

**Comment by dginev** [comment]
> > For example, if we only had intent terms - without any advanced annotations - none of my examples would have been possible.
> 
> sure but as I showed someone trying to obfuscate could use `_` or `__` or `any-unassigned-unicode-codepoint` or .... 

The unassigned codepoint case likely needs error recovery - was it `U+FFFD`? - with some appropriate AT narration to that.

We haven't suggested to treat blocks of underscores as a single one, but that would be sensible. Maybe that is the effect already [due to](https://w3c.github.io/mathml/#intent_literal):
> a default reading is generated by replacing any -, _, . in the name by spaces and then reading the resulting phrase.

I am unsure if there is an implication that multiple consecutive spaces will have the same narration as a single space. Could be useful to clarify that.

> I think it matters to decide if you allow space after : as it affects how you search in files, can you look for :unit or do you have to regex search for :\s*unit.

Oh that is really nice, yes. It's great if `:unit` remains easy to grep for.

**Comment by davidcarlisle** [comment]
> The unassigned codepoint case likely needs error recovery - was it U+FFFD? - with some appropriate AT narration to that.

probably out of our hands, it would be rather expensive to keep  track of assigned points. So apart from the common cases with variant mathematical readings the rest is just going to end up as text sent on to speech engine or whatever component is being used.  It will do whatever it does with codepoints it doesn't know.

**Comment by NSoiffer** [comment]
I think I'm missing your point.

Assuming `not` and `factorial` are core, then they are both single argument
function/concepts. The examples you gave don't have one argument. What to
do in these kind of cases is why I raised #435. A two argument `factorial`
is no more sensible than a one argument `power`, at least as they are
commonly understood (maybe in some domain, all powers have a base 'e', but
AT can't assume that).

The discussion in #435 didn't come to an inclusion for what to do in this
situation, but I think #437 said to move to graceful degradation. So in
this case, degradation would likely be "consider them to be an open
concept", thus speak them as indicated. So, they would be treated the same
as `intent="_(x,foo@prefix(y))"` and get spoken as you indicated. The
examples you gave are clever puzzles, but I don't see what problem they
pose or issue they raise other than what I raised in #435.

Similarly, the last bunch (`not@prefix()`) seem like more error repair
cases, as would `foo@prefix()`. There is a philosophical argument about
whether functions can have no arguments, but that exists for
`intent="foo()"` also, so the hint syntax does not raise additional
problems in that regard... if that is the point of this issue.

**Comment by dginev** [comment]
@NSoiffer thanks, the walkthrough to how the narration process would first cast some of these cases as "Open" (even though they would coincide with Core names) was a good point to demonstrate alongside.

I guess the first point of this issue will be trying to align with everyone to what extent my examples are potential problems, and to what extent they are clever puzzles.

I tried to construct them in a way where they illustrate the interplay of two design choices interacting - fixity and silence.

**Comment by davidcarlisle** [comment]
> I guess the first point of this issue will be trying to align with everyone to what extent my examples are potential problems, and to what extent they are clever puzzles.

They just seem to be expected examples.  You used `_` and `@` in them but you could have used

`intent='foo()()()()()()()()()()()()()()()'`

or

`intent='foo(a)(b)(c)(d)(e)(f)(g)(h)(i)(j)(k)'`

or even

`intent='meaninglessnonsense'`

It's not possible to provide an annotation mechanism that doesn't allow nonsensical or confusing annotations.

**Comment by brucemiller** [comment]
> It's not possible to provide an annotation mechanism that doesn't allow nonsensical or confusing annotations.

And even if it is, it's probably not a good idea as it will restrict good usages we hadn't considered.  I think we should be content with a general warning that authors shouldn't attempt to be overly prescriptive of the exact speech generated.

(I think this issue is closable).
