### ISSUE TITLE
speech templates

### ISSUE THREAD

**Issue by davidcarlisle** [w3c/mathml#443]
During discussion of existing intent proposals on the last call there was a general feeling that adding `:properties` to the existing mix of `@hints` and `_literal_tokens` was making the functional intent syntax not exactly friendly and we should look again at an earlier suggestion of using a syntax closer to a free text templated string.

This is a not entirely baked start at a proposal in that direction.

------

```
template = (tchar | '\' t  | '[' S concept S ']' | '(' template ')')*
tch = char- t
t = '[]()\'
concept = concept-name (S ':' property-name)*
concept-name  = (char - '[]():$')*
property-name  = (char - '[]():$ ')*
S = [ \t\n\r]*
```

This allows spaces in concept names but not property names.

It repeats `:` so

```
[absolute value : delimited : real : unary : continuous : non-differentiable]
```

We could instead just have at most one colon, and take space separated words as properties

```
[absolute value : delimited real unary continuous non-differentiable]
```

or could keep multiple colons and allow spaces in properties

```
[absolute value : delimited : real : unary : continuous : non differentiable]
```

In all variants, `|` could be used instead of  `:` 

`$` and `()` could be allowed in concept and property names as you just need to scan for `:` or `]` but disallowed to make it easier for humans to spot  `$argref`

`$argref` is not in the grammar, but  `'$'(char-S)+` would be recognised as an argref when appearing in a string.

* Quoted symbols such  `\[ ` or  `\)` denote the symbol as part of the string.
*  Unquoted `[]` and `()` must be well matched
* the content of () is handled recursively as a template
* the content of [] is more restricted and is interpreted as a concept reference.

We could just say this in words and not have a grammar at all.

## Generating Speech

**concepts** are identified by name and arity and are **known** or **unknown**. The **known** list is system dependent but should include all the **core** list.

To determine **arity** scan forward from `]` looking for `$argref` or `(` nested template, stopping at the end of the template, so `)` or end of string,  or first `$` or `(` found.

* If no argument is found, arity is 0 (not sure, we may or may not want to distinguish symbols from 0-ary functions, depends on your foundational type theory...)

* if  `$argref`  is found, arity is 1 and argref is the argument

* if `(` is found the contained template is split on `,` (not in nested `()`) and the length of this list determines the arity the arguments are the components of the nested template, split on `,`.

**Examples**

| template |  name/arity | arguments |
| ---- | ---- | ---- |
| `(  [infinity]  )`  |  `infinity/0` | |
|`[sin] $x `      |  `sin/1` |   $1=`$x` |
|`[sin] ([pi])` |       `sin/1`  |  $1=`[pi]` |
|`[power]( [foo](a,b) , $n)` |  `power/2` | $1=`[foo](a,b)`  $2=`$n` |
| `[sin] gratuitous text ([pi])` |  `sin/1` | text=`gratuitous text` $1=`[pi]` |
| `[power  : no-ordinal]( $x , $n)`  | `power/2` | $1=`$x`  $2=`$n` properties =`no-ordinal` |

* if the name/arity is *known* the system generates system defined text for that name, it may also use the skipped text and any properties as input.

* if the name/arity is *unknown* the concept name is used as literal text, properties do not form part of the text but may be exposed via ARIA or other mechanisms.

In the above I determine arity somewhat cautiously before lookup, so need `()` in `[sin] ([pi])` It may be possible to specify lookup just on name, so `sin` would then default to arity 1 and `[sin] [pi]` would work, that might also help with defaulting `[plus]` as infix below.

## Generating a *content expression*

A **content expression**  (intent expression??) is a functional prefix form where the head of
each term is a concept name, possibly attributed with properties,

A concept expression generated from a speech template can not always
capture the indented mathematical intent (which might only be expressed as
free text) but it should capture common cases, and generators of speech
templates should be able to construct them in a way that allows
meaningful extraction of a content expression (which may involve
ensuring explicit `()` grouping and markup of content names).

To generate the prefix form, 

* arguments of concept references are determined as above, with any text that is scanned before the arguments being discarded. 
* In addition any text in the comma separated list of arguments  is discarded unless the argument just consists of a number `-?[0-9]+(\.[0-9]+)?`  
* If a template has a sequence of concept references with property `infix` (will need some default here) they should be replaced by `,` and one reference adding to the front of the template (adding `()` if not already bracketed
* If a template is a comma list not being used as the argument list of a functon which has exactly one term being a concept ref, that is similarly moved to be a function head.

    so 

  $x^3+x^2+x$

   `[power]($x,3) [plus:infix] [power]($x,2) [plus:infix] $x`
    ==>
   `[plus:infix] ([power]($x,3) , [power]($x,2) , $x)`

    free $r$-algebra on $x$

    `([free], ($r,[algebra]) on, $x)`
     ==>
    `[free]([algebra]($r), $x)` (er, perhaps...)

**Comment by brucemiller** [comment]
A key difference between this approach and that of #444, is that this one allows embedded functional notation as a mechanism to recognize the arguments to concepts, without requiring it.  When that notation is not used (and as in #444), the AT must search and guess what the arguments are. (At least, *if* it wants the arguments.)

I worry that this search & guess approach seems unreliable and puts a big burden on the AT developer and confusion for the annotator who will likely omit the gratuitous colons or `[]` or whatever needed for the AT to find which words are, or are not, the arguments.  The current proposal seems to only expect arguments to follow the concept, so things like `$x to the [[power::]] $n` or `$y in [absolute-value]` wouldn't find arguments although the speech would be as expected.

OTOH, since these two approaches emphasize "phrases to be spoken as is" (with references to other things whose speech will be interpolated), I wonder if the concept of concept is as critical as we've been assuming.  Certainly it is useful for the adaptability of speech, with `power` being the poster child.  But it seems to me that this is small set of concepts that need this treatment (or alternatively it is an unknowable set, given potential idioms in random languages).

So, I like the possibility of writing `intent="power($x,$n)"`. And since in that case it is reasonably clear that `power` is a Concept, there need not be a syntactic call-out to distinguish concepts from literals.

**Comment by brucemiller** [comment]
A second reason to distinguish concepts from literals is the desire to do some form of "content generation".  I'll have to admit that, for me, this goal is a *far* distant second to accessibility.  To the extent that this is desirable (& possible), I suspect that most annotators will be confused by the requirements needed for "magic" argument detection to work, and will fail to get it right. Those that *do* care should probably just use the functional forms.  But if the do that, is there still a way for them to provide the desired free-text?

**Comment by davidcarlisle** [comment]
@brucemiller 

> So, I like the possibility of writing `intent="power($x,$n)"`

for a generator making speech from $x^2$ it needs a rule to say squared if the index is 2, but for  specific speech string on an instance we could just say `intent="x squared"`  It seems to me the only  reason to have any of the complication is to allow some sort of functional/content form to be extracted.

But I'm not sure we have the balance right.  The existing spec with functional forms and the occasional `@hint` works quite well so long as you are relatively relaxed about the exact speech generated. But if that really  leads to

 `_(_an,_english,_sentence,_expressed_,as,_arguments,_to,_an_invisible,_function)`

I don't think it's usable.

The speech template suggestions make forcing a specific speech string a lot more reasonable, but I think the Jury is still out on whether we can make it possible to get a reliable extraction of  a content tree.

**Comment by dginev** [comment]
FWIW, if we had the wiki-style `[symbolic form|speech template]` dual annotation available, it is a somewhat reasonable vehicle to encode the two parallel aspects to a mixfix notation we are discussing (the content form and narration form). Namely, for the free algebra example:

```
[ free-algebra($r,$x) | free $r algebra on $x ]
```

I suspect this kind of duality is where the Intent "symbolic notation" and the Intent "template string" approaches inevitably meet. I also suspect there is no good trick to reconcile the diverging structure, which doesn't end up highly artificial when one considers the full breadth of mixfix notations out there. 

So `[ | ]` is one reasonable way to go on "living with duality".

Edit: for comparison's sake:
```
[ free-algebra($r,$x) | free $r algebra on $x ]

free-algebra@silent(_free, $r, _algebra, _on, $x)

(free $r algebra:free on $x)
```

**Comment by davidcarlisle** [comment]
@dginev 

> `[ free-algebra($r,$x) | free $r algebra on $x ]`

 yes but having the entire expression twice in the intent plus again in the presentation tree   isn't  wildly attractive.  I've been playing a bit with a variant of your syntax with an optional `speech|` prefix so `speech|concept:properties` Not worked out a proposal yet but something like

`free|free-algebra:  $r algebra on $x`

which reads as `free $r algebra on $x`  but dropping literals ends up with a derived 

`free-algebra: ($r, $x)`

But I do wonder if we are over-thinking this. 

The notation being annotated is R⟨X⟩ If we just used `free-algebra($r,$x)` and let it be read as a two argument function that is not clearly a bad thing. Accessible readings are not the same as conventional readings in any case, and is preserving this particular idiom really needed?

**Comment by brucemiller** [comment]
@davidcarlisle 
> > So, I like the possibility of writing `intent="power($x,$n)"`
> 
> for a generator making speech from x2 it needs a rule to say squared if the index is 2, but for specific speech string on an instance we could just say `intent="x squared"` 

Indeed. And so such concepts, and all their argument finding complications, could be avoided.

> It seems to me the only reason to have any of the complication is to allow some sort of functional/content form to be extracted.

Indeed, if such a thing is needed, possible, desirable and in scope.

*Suppose* we back up a couple of steps and just have a much simpler template form of `intent` which *only* provides for interpolation of argument's intent via reference `$NCNAME`, but also recognizes properties. 

In general, we have the simplest intents, and give AT the most flexibility when we place intents as low as possible.  Thus `<mo intent="plus">WeirdUnicode</mo>` is quite handy.  Alas, with `msup`, we have no operator to annotate. What if we leveraged properties to disambiguate:
```
<msup intent=":is-power">
   <mi>x</mi>
   <mn>2</mn>
</msup>
```
? Or something of that nature? (just thinking out loud)

**Comment by davidcarlisle** [comment]
@brucemiller 

> Suppose we back up a couple of steps and just have a much simpler template form of intent which only provides for interpolation of argument's intent via reference $NCNAME, but also recognizes properties.

Yes I wondered about that.

In one of my trials I ended up at

`(($x power: 3) plus: ($x power: 2) plus: $x)`

which gets a derived content expression  of 

`(plus: (power: $x 3)  (power: $x 2) $x)`

which works but there are apparently some people for whom "looks like lisp" isn't a compliment, so I'm not sure this is the right direction

**Comment by davidfarmer** [comment]
In this new-ish proposal, how do I indicate that

<msup>
   <mi arg="x">L</mi>
   <mn arg="y">2</mn>
</msup>
<mo>(</mo><mi>ℝ</mi><mo>)</mo>

is pronounced "L two of R"?

Should I put in a <mo>&ApplyFunction;</mo> to get
the "of" part of the pronunciation even though L^2 is not really
a function?

**Comment by brucemiller** [comment]
@davidcarlisle you *could* just say `intent="$x cubed plus $x squared plus $x".

@davidfarmer you *could* just wrap with an `<mrow intent="L 2 of R">`  (or `$x $y of R`)

**Comment by davidcarlisle** [comment]
Comparing the version of template in the initial  comment here and the one in Deyan's issue, the main difference is white space.  As I have a terminator, can be a lot freer with white space, in concept names, and also after `:` as there is a `]` separating property names from following speech template literals. However the form without `[]` looks much better in the far more common simple cases.  As noted above I also wanted to allow adding a concept reference _without_ changing the generated speech so here I added a `speech|` prefix, but otherwise used the syntax from the "colon-anchored" variant.

This allows arbitrary text string and the extraction of content  expressions in a large set of cases. It is going in the opposite direction to that just discussed with @brucemiller I think we should make a truly minimal proposal along those lines as well, but  I have this version more ready.

-----

**speech|concept:properties** version

A **template** is a string matching

```
literal =  (litralchar | '\' syntaxchar)+
argref  = `$` namechar+
number  = '-'?[0-9]+(\.[0-9]=)?
nested  = '(' template ')'
conceptref = (literal '|')? namechar+ ( (':' namechar+) +| ':')
syntaxchar = [()|:]
literalchar = char - syntaxchar 
namechar =char - syntaxchar - S
S = [ \t\n\r]
```

| Template | Speech String | Content S-Expression |
| ----          | ----                   | ----                         |
| `(free\|free-algebra:  $r algebra on $x)` | free  r algebra on x  | (free-algebra: $r $x) |
| `(  infinity:  )` |  infinity |   infinity: |
| `(sin: $x)`   |     sin(e) x  | (sin: $x) |
| `(sin: (pi:))`   |    sin(e) pi    | (sin: pi:) |
| `((foo: a b) to-the\|power: $n)` |  foo of a comma b;  to the n | (power: (foo: a b) $n) |
| `((foo: a b) power: $n)` |  foo of a comma b;  squared| (power: (foo: a b) $n) | 
| `(sin: arbitrary gratuitous text (pi:))`  | sin(e) arbitrary gratuitous text pi | (sin:  pi:)
| `(power:no-ordinal $x  $n )` |  x to the n | (power:no-ordinal $x $n)  |
| `((pi:)  plus: (pi:))` |  pi plus pi |  (plus: pi: pi:) |
| `(pi:  plus: pi:)` |  pi plus pi | (list: pi:  plus: pi:) |
| `(($x power: 3) plus: ($x power: 2) plus: $x)` | x cubed plus x squared plus x | (plus: (power: $x 3)  (power: $x 2) $x) |


-----

Here the head of each nested subterm is the unique concept name . You may need to nest arguments so they are not at the top level eg  `((pi:)  plus: (pi:))`  then to make a functional form, pull that to the head of the list and drop all literals.  If there is not a unique concept name to use as function head use `list:` (perhaps with a more unique name)

I show outer `(..)`  in the first column, but they would typically be omitted at the outer level so `intent="sin: $x"`  

To generate speech if the function for a subexpression is **unknown**, or has a `speech|` prefix, just read the template as-is.  If the function is **known** derive the functional expression (so discarding all literals, but keeping properties) then generate speech according to the **core** list or a system defined extended list of **known** functions

**Comment by davidcarlisle** [comment]
@davidfarmer, as @brucemiller just said you  could force any speech you want with 
`<mrow intent="L 2 of R">`

A more structured version giving concept references might be
`l2|lebesque-space:  of R|Real-numbers:`

or
```
<msup intent="l2|lebesque-space:">
   <mi arg="x">L</mi>
   <mn arg="y">2</mn>
</msup>
<mo>(</mo><mi intent="R|Real-numbers:">ℝ</mi><mo>)</mo>
```

But the point of the conversation above with @brucemiller  is do you (or anyone) want the version allowing structured concept refs. If everyone is simply going to supply a text alternative as
`<mrow intent="L 2 of R">`
we could remove basically all the complication.

**Comment by davidfarmer** [comment]
Proposal: an intent that means "say the parts in this order"

For example, in analytic number theory,

L(s, \chi)

is pronounced "ell ess chi".  No "of" and no comma.

Similarly, L^2 , when referring to square-integrable functions,
is pronounced "L two".

The Gegenbauer polynomial  G_n^{(\alpha)}(x)  is pronounced
"G n alpha of x"

Using "indices" as the name of that intent (I am not wedded
to that word), we could have

<mrow intent="indices($x,$y,$z)">
<mi arg="x">L</mi>
<mo>&ApplyFunction;</mo>
<mo>(</mo><mi arg="y">s</mi><mo>,</mo><mi arg="z">𝛘</mi><mo>)</mo>
</mrow>

"ell ess chi"


<msup intent="indices($x,$y)">
    <mi arg="x">L</mi>
    <mn arg="y">2</mn>
</msup>
<mo>&ApplyFunction;</mo>
<mo>(</mo><mi>ℝ</mi><mo>)</mo>

"L two of R"


<msubsup intent="indices($x,$y,$z)">
   <mi arg="x">G</mi>
   <mi arg="y">n</mi>
   <mrow>
     <mo>(</mo>
     <mi arg="z">α</mi>
     <mo>)</mo>
   </mrow>
</msubsup>
<mo>&ApplyFunction;</mo>
<mo>(</mo>
<mi>x</mi>
<mo>)</mo>

"G n alpha of x"

**Comment by davidcarlisle** [comment]
@davidfarmer  yes I wondered about "indicies" before.
 
"no of, no comma" is the `@prefix` hint format in the current spec.

In Bruce's new brutally minimal version in #445 I suspect

```
<mrow>
<mi> L</mi>
<mo intent=":prefix">&ApplyFunction;</mo>
<mo>(</mo><mi>s</mi><mo>,</mo><mi>𝛘</mi><mo>)</mo>
</mrow>
```

is enough (where `:silent`  would stop of but keep the comma)

**Comment by davidcarlisle** [comment]
@davidfarmer  or simply 

```
<mrow intent="$l $s $x">
<mi arg="l"> L</mi>
<mo >&ApplyFunction;</mo>
<mo>(</mo><mi arg="s">s</mi><mo>,</mo><mi arg="x">𝛘</mi><mo>)</mo>
</mrow>
```

But are you _sure_ that's the reading you want? I agree it's the conventional reading for sighted  readers, but I would read $x_1, x_2,x_3$  and $x1,x2,x3$ and in some contexts $x^1,x^2,x^3$ as x-1 x-2 x-3, but I can see they are different. We seem to be heading to give authors control over the exact text used, the orginal idea of intent was just to give the speech generator enough of a hint of the mathematcal structure that the speech generator can make something reasonable. I'm not totally convinced I trust authors (or me) to choose good speech templates, but I trust them more  to know the mathematical structure so I'm still not sure we should  drop the functions and `@hint` form of intent.

**Comment by davidfarmer** [comment]
I am not suggesting dropping any of the other options.

The particular case I want to solve is  L^2(X)  as
"L two of X".  Similarly for H^2(X)  as "H two" when it
means second cohomology.

Also for special functions with multiple indices (where those
indices may be in a superscript).

That got me thinking that intent="indices($x,$y,$z)" might be
a viable option, applicable in many instances.

Things like  \mathbb R^2 , pronounced  " R two " are common and
deserve a place in core.  I'd like an official way to do that,
and not a roll-your-own as if it were not in core.

**Comment by davidcarlisle** [comment]
> I am not suggesting dropping any of the other options.

the current spec, and the versions in issues 443,444,445 are mutually incompatible we need to pick some version and drop the rest.

> Things like  \mathbb R^2 , pronounced  " R two " are common and
deserve a place in core.  I'd like an official way to do that,
and not a roll-your-own as if it were not in core.

Currently with mathcat you can use

```
<math>
 <msup>
  <mi>&#x211D;</mi>
  <mn>2</mn>
 </msup>
</math>
```

which gets read as  "R 2"   Adding intent typically makes it say something else

See readings of that with and without intent on the R^2 line:

https://mathml-refresh.github.io/intent-lists/intent3.html#IDR2

**Comment by dginev** [comment]
> @dginev
> 
> > `[ free-algebra($r,$x) | free $r algebra on $x ]`
> 
> yes but having the entire expression twice in the intent plus again in the presentation tree isn't wildly attractive.

Sure, but only if the alternative is more natural+ergonomic.

I got to think briefly about function composition again today (thanks to Dennis), and it has an interesting variety of narration forms, quoting the [wiki page](https://en.wikipedia.org/wiki/Function_composition):
> The notation g ∘ f is read as "g of f ", "g after f ", "g circle f ", "g round f ", "g about f ", "g composed with f ", "g following f ", "f then g", or "g on f ", or "the composition of g and f ".

That would yield the variation:
```
[ function-composition($g,$f) | $g of $f ]
[ function-composition($g,$f) | $g circle $f ]
[ function-composition($g,$f) | $g round $f ]
[ function-composition($g,$f) | $g about $f ]
[ function-composition($g,$f) | $g composed with $f ]
[ function-composition($g,$f) | $g following $f ]
[ function-composition($g,$f) | $g then $f ]
[ function-composition($g,$f) | $g on $f ]
[ function-composition($g,$f) | the composition of $g and $f ]
```

in cases where an author decides to ensure the produced speech for `function-composition($g,$f)` matches their own preference. 

I think with the `speech|concept:properties` convention, that would look as:
```
$g of|function-composition: $f
$g circle|function-composition: $f
$g round|function-composition: $f
$g about|function-composition: $f
$g composed-with|function-composition: $f
$g following|function-composition: $f
$g on|function-composition: $f
the composition|function-composition: of $g and $f
```

Interesting. Certainly briefer! Maybe it's a workable approach, though note that it reintroduces the "shuffled arguments" problem which Bruce remarked on for my proposal - in the last variation the operation appears prefix, while in all other cases it is infix. The guessing is eliminated by the more verbose form - but it is quite verbose indeed.

**Comment by davidcarlisle** [comment]
> Sure, but only if the alternative is more natural+ergonomic.

well yes. 

I am having doubts about all the speech template versions to be honest.

g ∘ f  could be read in many ways (chosen by the reader not the author) but the orginal "intent of intent" was to annotate it as `function-composition` rather than, say `group-product` so that a screen reader had a better chance  to generate mathematically appropriate text.  Hence `intent="function-composition($f,$g)` in the current spec.

But we seem to have now a requirement for the author to force whatever idiomatic reading they want. I'm not sure that is helping us find a coherent syntax or helps accessibility.

I may choose to read  `g ∘ f` and  `G Ⓕ` as  `g circle f` but I can see they are different. Does that mean I should as author be able to force these to be read the same, or just that I should mark the intent to show they are mathematically different.

I experimented a bit with nvda: the way it reads (say) section headings or tables is clear but not as you'd conventionally read things.  I'm concerned in a way I can't really formalise other than a "feeling" that making it easier to specify exact speech (the main driving force of all three of these 44x issues) is making it easier to specify text that sounds familiar to the author but is less accessible to some readers.

I'm not saying we should  keep the current spec and not go with one of these proposals, I just don't know....

**Comment by davidfarmer** [comment]
A difficulty for me is when something well-understood is used
as an example for allowing arbitrary intent markup.

In K-14 math in the US, the notation g ∘ f  is not ambiguous:
it means "g of f" and that is also how it is usually pronounced.
That is: h = g ∘ f  means h(x) = g(f(x)) .

So, I don't think that needs to be in core, because AT should know
the standard pronunciation.  If there is another common meaning
I don't know about, then it should be in core, probably as David C
suggests:  intent="function-composition($x,$y)" .  And in that
case it would probably be a bad idea for the author to prescribe
the pronunciation.

I understand that there are good reasons to use basic examples
as illustrations, but it also is a distraction because the examples
tend to look ill-advised, and also can lead to the idea that core
is not going to do its job.

**Comment by davidcarlisle** [comment]
> A difficulty for me is when something well-understood is used
as an example for allowing arbitrary intent markup

Yes you can't win here. I tried using rabbit (🐇) examples for that reason, but not everyone appreciated that either.

I'm actually surprised by your statement that `∘` would have standard pronunciation as "of".  Function composition is normally implicit so `g(f(x))`  "g of f of x" so in those cases where it does need to be explicit `(g∘f)(x)` I don't think I'd pronounce it the same way, more likely `g composed with f, applied to x`  after a while if using this as the multiplication in some group of function actions, I'd likely as not make it silent like conventional multiplication  `3x` "three x" and just read it as g  f.  If you said "g of f"  to me I'd assume you meant g(f).

**Comment by davidcarlisle** [comment]
@davidfarmer  for example 30 seconds in to
https://nool.ontariotechu.ca/mathematics/functions/composition-of-functions.php

`(f ∘ g)(x)= f(g(x)`

read as

> f compose g, of x equals f of g of x

**Comment by dginev** [comment]
This is exactly why real examples are better - real problems are more productive to discuss, and disabuse us of kinds of certainty we shouldn't have. 

When Dennis started the `∘` conversation with me, he was working on real materials where `∘` was used as a [monoid](https://en.wikipedia.org/wiki/Monoid) operation (aside: wiki uses `•` for that operation, other variations are also possible). He wanted me to share an opinion if 
`<mo intent="generic-binary-operation">∘</mo>` would be too artificial, or there is a better way. 

Which is what opened the "but how would AT even speak that?" discussion. 

For that monoid use, the functional syntax may have led to (the Open realm) `intent="_circle:monoid-operation"` and some of the template proposals may be close to `intent="circle|monoid-operation:generic-binary-operation"` or some such -- *IF* such level of detail was useful. In the end we have two outcomes to consider - the "accessible name" and the "accessible description" for each relevant subtree of the Presentation MathML.

**Comment by davidfarmer** [comment]
I did qualify it by saying how it is pronounced in US high schools.

But it is correct that  g o f = g(f).
It is the function that satisfies

(g o f)(x) = (g(f))(x) = g(f(x)) .

Sorry if it seems I am quibbling.  I am okay with AT deciding
that  g o f  is pronounced  "g composed with f".

The Wikipedia page has 10 different pronunciations, which may
be where Deyan found his examples.

**Comment by davidcarlisle** [comment]
> But it is correct that  g ∘ f = g(f).

(g ∘ f)(x) = g(f(x)) .

yes.  But ∘ is normally introduced explictly to clarify that g ∘ f is _not_ g(f)

**Comment by brucemiller** [comment]
> > The notation g ∘ f is read as "g of f ", "g after f ", "g circle f ", "g round f ", "g about f ", "g composed with f ", "g following f ", "f then g", or "g on f ", or "the composition of g and f ".

For completeness, in #445, that would probably be the similar:

```
$g of:function-composition $f
$g circle:function-composition $f
$g round:function-composition $f
$g about:function-composition $f
$g composed-with:function-composition $f
$g following:function-composition $f
$g on:function-composition $f
the composition:function-composition of $g and $f
```
but with the distinction that the `:function-composition` isn't *necessarily* a "concept", but just a possibly unknown, possibly helpful, phrase.

**Comment by davidcarlisle** [comment]
@brucemiller  yes and all variants lose some weirdness if the annotation goes on the operator


```
<mrow>
 <mi>f</mi>
 <mo intent=":function-composition">∘</mo>
 <mi>g</mi>
</mrow>
```

even if that leaves more work for the speech generator.

For interest MathCAT generates

`f composed with g`

for that (with or without the intent)

`intent="circle:function-composition"` produces

`f circle g`


With the current version you'd have to move back to the mrow to force 

`composition of f and g`

**Comment by brucemiller** [comment]
@davidcarlisle I think this is true for *any* of the current proposals (functional or template): for all but the last form, putting intent on the operator would be preferred, as `<mo intent="of:function-composition">` or `circle:function-composition`, etc.  For the last form ("composition of f and g") you'd have to move back to the mrow.  Of course, exactly what you put as intent varies with the proposals.

**Comment by davidcarlisle** [comment]
> I think this is true for any of the current proposals

Yes, that's what I meant to say (but didn't express too well).

At least it probably has to be on the mrow. With the current syntax one could say that

```
<mrow>
 <mi>f</mi>
 <mo intent="composition@function">∘</mo>
 <mi>g</mi>
</mrow>
```

should be read as "composition of f and g" although mathcat doesn't use hints on leaves that way, it would probably require more lookahead than it really does.

But in general, as I note above, I'm becoming less convinced giving authors control over the exact speech should be an aim. If simple cases drop out of the mechanism so be it, but if there are phrases that are hard to force, I'm leaning to saying use a different/more structural speech form rather than either extreme of just supplying plain text alternative or coming up with ever more complicated syntax for specifying speech and structure in parallel.

**Comment by brucemiller** [comment]
What I'm seeing is that a concept oriented syntax (eg. functional) will be countered by  "Ah, but it should speak *this* way!", while a more template oriented syntax (eg. this one) will be met with "Ah, but it needs concepts!", and finally hybrid proposals  "are too complex!".  So, I suspect that we've gone as far as we can until we're in agreement about exactly what features are required, and what we're willing to pay for them.

**Comment by NSoiffer** [comment]
@davidcarlisle  wrote:
```
<mrow>
 <mi>f</mi>
 <mo intent="composition@function">∘</mo>
 <mi>g</mi>
</mrow>
```

> should be read as "composition of f and g" although mathcat doesn't use hints on leaves that way, it would probably require more lookahead than it really does.

Add another `mo` with a different "intent" and what should AT do? I don't think hints on leaves make sense other than "silent".

I agree with everyone who said put the `intent` as low as possible. For a functional reading, I feel that means on some surrounding `mrow`. That applies to the current functional "intent" and also for a templated string "intent".

**Comment by davidcarlisle** [comment]
@NSoiffer 
> Add another mo with a different "intent" and what should AT do?

It could ignore it, or infer some nesting or whatever.

currently if you have an mrow with exactly two mo, a `(` at the start and a `]` at the end mathcat infers a speech pattern of  "the open-closed interval..."   If you add a third mo nothing bad happens, it just doesn't match.

I don't see why that is different to matching a mrow with a single mo with a `@function` hint being read as a prefix function, if you have two mo that pattern just doesn't match.

I think conceptually `$argref` should be implementable as a macro that inlines the (possibly implied) intent of the referenced element.

```
<mrow  intent="$op@function($a,$b)">
 <mi arg="a">f</mi>
 <mo arg="op"  intent="composition">∘</mo>
 <mi arg="b">g</mi>
</mrow>
```


is `composition@function($a,$b)` so why not


```
<mrow  intent="$op($a,$b)">
 <mi arg="a">f</mi>
 <mo arg="op"  intent="composition@function">∘</mo>
 <mi arg="b">g</mi>
</mrow>
```

**Comment by davidcarlisle** [comment]
On the call 2023-03-16 we agreed to close this and consolidate discussion of template variants of  ìntent` in #446
