### ISSUE TITLE
Intent Templates (colon-anchored variant)

### ISSUE THREAD

**Issue by dginev** [w3c/mathml#444]
This issue offers my first draft to a templating syntax for Intent that preserves most features of the functional syntax. 

The big design inversion is that templates make producing the narration string trivial (linearly mapping each piece to text left-to-right), but place an additional annotation and convention burden to get usable Content-like forms for each expression. 

One basic signal for this change is using spaces as separators for the template variant, the way we do in language, rather than using commas, which are customary for symbolic expressions.

---

Some assumed pre-agreed technical syntax goals that overlap with the functional syntax:
1. we want to be able to mark "concepts"
   - and then have Core and Open aspects to that feature
2. we want to be able to mark "literals" which just "pass through" to the narration string
3. we want to have a mechanism for composing "arguments" to notations 
   - via $references to `arg="reference"` attributes on descendant nodes,
   - allowing a compositional+partial nature to Intent annotations
4. we want to be able to mark "properties" over concepts and references
   - and then have Core and Open aspects to that feature
5. we want to support nested intent expressions held by a single `intent` attribute

---

Here are some ideas that came to mind while brainstorming:

***Colon-anchored variant:*** In the interest of reducing the learning curve and keeping a small budget of special characters, I suggest we can use the colon to anchor **both** concepts and properties. Namely, if `strict-equality:relation` is a concept with a property, and `:relation` is a standalone property, then I also propose that `strict-equality:` is the syntax for a standalone concept. Without the colon, it would be a narration-oriented literal.

So what we used to think of as `transpose@postfix(_wibble)` can now be written `wibble transpose:`

--- 

***Optional grouping:*** As templates are geared towards narration, the Content-near forms can truly become an optional secondary feature. In other words, grouping the applicative structure should not be *required* in a template, but should be *possible* for advanced use.

In the functional syntax, grouping is fundamental and always available, as in `equals(2,plus(1,1))`. In the template syntax it is now easy to write that with the structure omitted, as in `1 plus: 1 equals: 2`, when only requiring a path to narration. But it should still remain *possible* to offer the grouping information. I suggest using parentheses, as usual, to get to `(1 plus: 1) equals: 2`.

Grouping offers key information for enabling both "accessible navigation", as well as "mapping to Content forms" for larger intent expressions (ones with multiple nested operations).

---

### Possible grammar

```bnf
intent      := pieces? | properties
pieces      := piece (\s+ piece)*
piece       := concept  | literal | number | reference | grouped
grouped     := '(' pieces ')'
literal     := IntentName
concept     := IntentName ':' (property properties?)?
reference   := '$' IntentName properties?
number      := '-'? digit+ ( '.' digit+ )?
properties  := ( ':' property )+
property    := IntentName
IntentName  := Letter (Letter | '-' Letter)*
```

### Features
- space-separated template string of pieces (no functional aspects)
- empty intent is allowed, only at the top-level, and is the *only* way of marking "silence"
    (~except that the single underscore is still allowed if we're using NCName, so maybe that won't fly...
      I just wanted to have one grammar without any *reliance* on underscores, for example's sake~)
- empty "concept" with properties is allowed, only at the top-level
    - for e.g. `<math intent=":chemical-formula">`
    - I claim there's no need to have any "empty" allowances inside expression arguments
- literals are natural language words, meant to be passed on as-is to narration
    - ~I used `NCName` because of David's insistence on that being the only allowed choice, but we could be more precise if we could use `Letter`~
- numbers are (unfortunately) special, since they are actually concepts - AT needs to match them to localized speech strings (unlike literals), but they shouldn't require special concept markup (and likely don't need property annotations)
- properties are as with recent group consensus, colon-separated, multiple ones allowed
- *NEW* concepts end with a mandatory colon ':' char, even when they do *not* have explicit properties
    - this *saves* us a special character, reducing the learning curve
- parentheses are used for simple "precedence grouping",
    - but building an "application tree" requires more work than the functional syntax.

### Examples

Small intent expressions with a single (or no) operator are seemingly straightforward to annotate, and to pattern-match against:

```xml
<mrow intent="absolute-value: of $x">
 <mo>|</mo>
 <mi arg="x" intent=":rational-number">x</mi>
 <mo>|</mo>
</mrow>
```

For a flat mrow with multiple active arguments, we can use grouping to indicate the expression structure (this overlaps the same need with the functional syntax). Say `x+2|y-z|`

```xml
<mrow intent="$x plus: (2 times: (the absolute-value: of ($y minus: $z)))">
  <mi arg="x">x</mi>
  <mo>+</mo>
  <mn>2</mn>
  <mo>|</mo>
  <mi arg="y">y</mi>
  <mo>-</mo>
  <mi arg="z">z</mi>
  <mo>|</mo>
</mrow>
```

Bruce raised a good example that is painful to create an applicative tree for, but will produce decent narration:

```xml
<msup intent="$x to the 7 power:">
  <mi arg="x">x</mi>
  <mn>7</mn>
</msup>
```

To enhance it to *also* have the information for the content tree, I would imagine:
```xml
<msup intent="$base to the $script power:">
  <mi arg="base">x</mi>
  <mn arg="script">7</mn>
</msup>
```

where an AT engine can use the information of the `power:` operator being placed on an `msup`, and pattern match the base-script relationship of the referenced arguments.

### Conventions

Q: How can AT know which pieces are arguments, and which are operators?
A: There likely needs to be some conventions/algorithm suggestions in place, similar to my attempt at an Intent-to-Content convention [doc](https://dginev.github.io/mathml-docs/intent-to-content).

Possible examples of such conventions (still brainstorming):

1. Grouping and Core concepts. In `($y minus: $z)`,
   - we know `minus:` is in Core, and will be seen as the operator in an infix pattern
   - grouping limits the pieces that are possible arguments from a larger intent expression
   - this can be extended to Grouping and Open concepts, for a chosen Open list
2. References default to arguments, in cases where there are *also* concepts
   - some Open cases: `($x outer-product: $z)` or `(complement: $x)` will be resolved
3. Grouping and application hints (I like this the least)
   - when we have *no* list to consult, some expressions get tricky, such as
    - `negative-infinity: is less-than: positive-infinity:`
   - grouping can't help, as this is a single application
   - so we need a hint *somewhere*, and we only have property. One could imagine (though I don't like it)
    - `negative-infinity:arg is less-than:op positive-infinity:arg`
   - which will let AT pattern-match a `arg,op,arg` pattern. (or some other names)
   - As with the `@hints` I find this a bit too artificial, and would instead prefer a convention that advertises adding more `$references` and then using the available information from the Presentation tree. (presumably there is an `mi mo mi` subtree available for this example).

In the end, such conventions - and the scope of the features we want to add and abstain from - hinges on us aligning on what makes "good design" for the first edition of the Intent spec.

As a summary, the templating approach guarantees good baseline narration for AT systems with very minimal spec support and relegates the applicative Content forms to secondary (and clearly optional). If someone wanted to encode them - they could, but no one has to.
  * ("minimal" meaning that it can only expand references, everything else gets normalized to a literal as-is narration, grouping gets discarded. Something that can be implemented in one afternoon.).

I was thinking of emailing this around internally, but now that we have #443, maybe it speeds us up to use github for the discussions. I particularly want to tag @NSoiffer , who was recently interested in investigating the "pure templating" direction.

Edit: I moved the grammar draft from `NCName` to `IntentName` since it now appears using `Letter` is a possibility.

**Comment by davidcarlisle** [comment]
Yes thanks I meant to say in #443 that at the current state of play it might be better for people to post "competing" issues. To allow more experimentation.

Comparing this with mine they are pretty similar I think except you kept NCName and I dropped it, which doesn't quite fit with

>  used NCName because of David's insistence on that being the only allowed choice,

I think there is a misunderstanding about my (old) comments re  NCName, it was in the context of an existing proposal to use `[a-z]` and I don't think ascii only identfiers are socially acceptable. NCName was a convenient pre-existing class of names.

In #443 as  I followed the sketch in the talk and used `[]` I just allowed more or less anything apart from those so   
`[absolute value]`   
with a space as a concept name.  I kind of like that, but your trailing `:` looks quite a lot less cluttered.  As for NCName, it's not really a requirement as long as we don't have a "everyone speak English" requirement. You could just have any sequence of characters other than space and `:`.   So if having concept names with spaces isn't useful, we could use your form.
I think one benefit of using spaces means we can drop the "read `_` as space" rule, but perhaps we can drop it anyway and use `absolute-value` which is still naturally read as two words.

**Comment by davidcarlisle** [comment]
@dginev 

> so we need a hint somewhere, and we only have property. One could imagine (though I don't like it)

yes basically what I had with `:infix` but I didn't like that either.  extracting some functional form from a free text string with arbitrary mixfix arguments is going to take some sleight of hand somewhere, but I suspect something along these lines is possible, if not there yet.

For the infamous free algebra example I wanted to get from

free $r$-algebra on $x$

`free $r algebra on $x`  to `free-algebra($r,$x)` but ended up at `free(algebra($r),$x)` as I was trying to avoid `@silent`

`free-algebra:silent free $r-algebra on $x`

would I think end up at `free-algebra($r, $x)` once you drop the literals and have a magic `silent` property, but I suspect that we can do better.....

**Comment by davidcarlisle** [comment]
I sort  of want

`free:concept=free-algebra $r -algebra on $x`

so it reads as `free $r-algebra on $x`  but `free` gets replaced by `free-algebra` concept ref not dropped as a literal when deriving the functional form.

**Comment by dginev** [comment]
> I think there is a misunderstanding about my (old) comments re NCName, it was in the context of an existing proposal to use [a-z] and I don't think ascii only identfiers are socially acceptable. NCName was a convenient pre-existing class of names.

Oh, delighted to learn of this! Indeed, must have been some misunderstanding or another. Do you think we can use [Letter](https://www.w3.org/TR/REC-xml/#NT-Letter) as a category in that case? 

I have always been eager to codify that in each place we use `NCName` we really are aiming for ~`Word`~ `IntentName` :
```
IntentName := Letter (Letter | '-' Letter)*
```

Edit: I said `Word` since e.g. `vice-president` is a single word, but clearly `absolute-value` is an artificial concatenation of a name *into* a word. So I'll edit and call it `IntentName` to be clearer.

**Comment by dginev** [comment]
> I sort of want
> 
> `free:concept=free-algebra $r$-algebra on $x$`

Right, the free algebra example is so nice, since it really showcases how the structure of each *facet* of using the mathematical object diverges from the rest in the case of a mixfix notation. 

It is not even the usual dual presentation vs content, it is ternary - 1) presentation, 2) content and 3) accessible narration. Using the [wiki notation](https://en.wikipedia.org/wiki/Free_algebra) and the wikidata-implied [symbol id](https://www.wikidata.org/wiki/Q5500180), I can write:
```xml
<semantics>
  <mrow intent="free $R algebra on $X" id="m1.p" xref="m1.c">
    <mi arg="R">R</mi>
    <mo id="m1.open" xref="m1.c.symbol">⟨</mo>
    <mi arg="X">X</mi>
    <mo id="m1.close" xref="m1.c.symbol">⟩</mo>
  </mrow>
  <annotation-xml encoding="MathML-Content">
    <apply id="m1.c" xref="m1.p">
      <csymbol id="m1.c.symbol" cd="wikidata">Q5500180</csymbol>
      <ci>R</ci>
      <ci>X</ci>
    </apply>
  </annotation-xml>
</semantics>
```

The one clear observation here is that the 3 different structures diverge from each other, so we need some means to encode them *in parallel*. For perfect information we'd need cross-referencing. I would say this is the limit case of "highest difficulty example" for using the different branches of MathML.

If we wanted to build the `free-algebra:` concept from the `free:` and `algebra:` pieces, I agree we need some extra annotation to be added. But we also need to indicate the arguments in some fashion (especially in cases of 2+ arguments, the order can be rather important in today's Content MathML).

---

For a quick&easy win, one can invent some ergonomic convention or another, but it is hard to make it consistent without a fully parallel data-structure to point to. Here is the maximal compression I can currently think of, relying heavily on "custom properties" to hide the Content-related information (big grain of salt whether this can be made general enough to fit any mixfix case):

```xml
<mrow intent="free $R algebra:free on $X">
  <mi arg="R">R</mi>
  <mo>⟨</mo>
  <mi arg="X">X</mi>
  <mo>⟩</mo>
</mrow>
```

I cheated by knowing too much. We are very lucky that a "free-algebra" happens to be a kind of "algebra" (which doesn't always happen with language, e.g. "fake-diamond" is not a kind of "diamond"), so we can claim the concept here is "algebra", but it also has the property of being ":free" in the mathematical sense. Then an Intent-to-Content transformation algorithm may be *extended* where the upon collecting additional properties, it can instantiate even more concrete symbols.

Does this really work? I probably need 100 examples to really know...

**Comment by davidcarlisle** [comment]
> Do you think we can use [Letter](https://www.w3.org/TR/REC-xml/#NT-Letter) as a category in that case?


we can, although it depends on the implementation language. regex are fast but these are long lists of essentially arbitrary code points so validating the names is sort of costly compared to say validating  
 `[^ :]+`    
In an XML world (that we used to live in) one may hope there were efficient tests for ncname as it's required for eg element lookup in xpath. But in practice this concern may not be real anyway.

HTML for the similar id=... dropped xml based Name restrictions so you can use more or less anything `id="2"` for example. as far as I can tell from
https://dom.spec.whatwg.org/#concept-id
you can use any string

**Comment by davidcarlisle** [comment]
Some questions mostly for @NSoiffer  I guess. They apply equally to the version sketched in #443, but I'll use this version.

Currently if I have some variant trig-like function `my-cos`  I  can use

> 
> `my-cos(𝜃)`  with speech `my cos of theta`
> 
> If I want a more trig-like reading I can use a `prefix` hint:
> 
> 
> `my-cos@prefix(𝜃)`  with speech `my cos theta`

With speech template versions I could use

`(my-cos 𝜃)`  with speech `my theta` but empty extracted expression.

If  `<mi arg="x>𝜃</mi>` appears I could use

`(my-cos: $x)`  or  `(my-cos: of $x)`  

but only if the intent processor never adds "of" for non-core functions.  Which would mean adding it to a lot of templates. 

Is that OK or do we need to bring back hints with some pre-defined properties affecting speech generation so


`(my-cos: $x)`    `my cos of theta`  
 `(my-cos:prefix of $x)`  `my cos theta`

Also if an argref is not available could we use a `:variable` property to save `𝜃` from being dropped like `of`

`(my-cos:   of  𝜃:variable)`

That property might also be used as a default intent for `<mi>` so

`<mi>𝜃</mi>`  is `<mi intent="𝜃:variable">𝜃</mi>`  

Currently the default intent for `<mi>` is effectively its content but `<mi intent="𝜃">𝜃</mi>`  has an empty derived intent expression.

**Comment by dginev** [comment]
### Progressive Enhancement for Intent Templates

I suspect we all agree there is a varied spectrum of features (and capabilities) that get enabled with each extra piece of Intent syntax we come up with. I wanted to flesh out for myself the "progressive enhancement" tiers for this Intent Template draft proposal - here is what I came up with.

- The C tier enables "custom accessible narration"
- The B tier enables "custom accessible navigation"
- The AA tier enables "symbol-based narration+translation"
- The AAA tier enables an "accessible description" + property hints

<details>

<table role="table">
<thead>
<tr>
<th align="center">Acessible Grade</th>
<th align="center">Feature</th>
<th align="left">Example</th>
</tr>
</thead>
<tbody>
<tr>
<td align="center">F</td>
<td align="left">math image</td>
<td align="left">

```html
<img src="x1.png">
```

</td>
</tr>

<tr>
  <td align="center">E</td>
  <td align="left">HTML Math</td>
  <td align="left">
  
```xml
<span>x+2|y-z|</span>
```
  
  </td>
</tr>

<tr>
  <td align="center">D</td>
  <td align="left">MathML 3</td>
  <td align="left">
    
```xml
<math>
  <mi>x</mi>
  <mo>+</mo>
  <mn>2</mn>
  <mo>|</mo>
  <mi>y</mi> <mo>-</mo> <mi>z</mi>
  <mo>|</mo>
</math>
```

  </td>
</tr>

<tr>
  <td align="center">C –</td>
  <td align="left">img, alt<br>(small expressions only, if tested with AT)</td>
  <td align="left">
    
```html
<img src="x1.png" alt="x plus two times the absolute value of y minus z">
```

  </td>
</tr>

<tr>
  <td align="center">C</td>
  <td align="left">MathML 3, alttext<br>(small expressions only, if tested with AT)</td>
  <td align="left">
    
```xml
<math alttext="x plus two times the absolute value of y minus z">
  <mi>x</mi>
  <mo>+</mo>
  <mn>2</mn>
  <mo>|</mo>
  <mi>y</mi> <mo>-</mo> <mi>z</mi>
  <mo>|</mo>
</math>
```

  </td>
</tr>

<tr>
  <td align="center">B</td>
  <td align="left">Intent templates:<br>literals and arguments</td>
  <td align="left">
    
```xml
<math intent="$x plus 2 times the absolute value of $y minus $z">
  <mi arg="x">x</mi>
  <mo>+</mo>
  <mn>2</mn>
  <mo>|</mo>
  <mi arg="y">y</mi> <mo>-</mo> <mi arg="z">z</mi>
  <mo>|</mo>
</math>
```

  </td>
</tr>

<tr>
  <td align="center">B+</td>
  <td align="left">Intent templates:<br>literals and arguments<br>(mrow scaffold for navigation)</td>
  <td align="left">
    
```xml
<math>
  <mi>x</mi>
  <mo>+</mo>
  <mrow intent="2 times $rhs">
    <mn>2</mn>
    <mrow arg="rhs" intent="the absolute value of $inner">
      <mo>|</mo>
      <mrow arg="inner">
        <mi>y</mi> <mo>-</mo> <mi>z</mi>
      </mrow>
      <mo>|</mo>
    </mrow>
  </mrow>
</math>
```

  </td>
</tr>

<tr>
  <td align="center">A</td>
  <td align="left">Intent templates:<br>literals, arguments, grouping</td>
  <td align="left">
    
```xml
<math intent="$x plus (2 times (the absolute value of ($y minus $z)))">
  <mi arg="x">x</mi>
  <mo>+</mo>
  <mn>2</mn>
  <mo>|</mo>
  <mi arg="y">y</mi> <mo>-</mo> <mi arg="z">z</mi>
  <mo>|</mo>
</math>
```

  </td>
</tr>


<tr>
  <td align="center">AA</td>
  <td align="left">Intent templates:<br>literals, arguments, grouping, concepts</td>
  <td align="left">
    
```xml
<math intent="$x plus: (2 times: (the absolute-value: of ($y minus: $z)))">
  <mi arg="x">x</mi>
  <mo>+</mo>
  <mn>2</mn>
  <mo>|</mo>
  <mi arg="y">y</mi> <mo>-</mo> <mi arg="z">z</mi>
  <mo>|</mo>
</math>
```

  </td>
</tr>

<tr>
  <td align="center">AAA</td>
  <td align="left">Intent templates:<br>literals, arguments, grouping, concepts, properties, mrow wrappers</td>
  <td align="left">
    
```xml
<math>
  <mi>x</mi>
  <mo>+</mo>
  <mrow intent="2 times:invisible-operator (the absolute-value: of $inner")>
    <mn>2</mn>
    <mo>|</mo>
    <mrow arg="inner">
      <mi>y</mi> <mo>-</mo> <mi>z</mi>
    </mrow>
    <mo>|</mo>
  </mrow>
</math>
```

  </td>
</tr>

</tbody>
</table>

</details>

I got to 10 steps in the table, and things start to get slippery whenever we have multiple possible mechanisms (e.g. what can be achieved with parentheses in an intent expression can *usually* be achieved with adding `mrow` elements to the tree).

I don't think this comment is introducing anything new for the group to consider, it is just a kind of "summary card" for what a templating approach may offer.

**Comment by NSoiffer** [comment]
Responding to @davidcarlisle question about functions (my-theta $x)...

I don't think it is feasible for AT to know to say "of" without some hint -- what's different between `my-cos` and `apple`? How can I know one is a function and the other a variable? Perhaps the speech string should refer to an invisible apply function if it is in the tree?

One tricky part we have been skipping over is the potential need to delimit where the "of" ends. Usually this happens because complicated arguments are enclosed in parens as in $\sin(2\theta-\pi/2)$. With the speech template, will authors really make sure to add an end word? For 2D notations, will they use start/end words (e.g., "begin binomial m plus n choose 2 m plus 3 end binomial")? For people who can see the screen, how do we make those optional words?

Note: I do worry that authors won't think of these things. I just checked MathCAT, and indeed, even I left out bracketing words for binomials and I should know better.

**Comment by davidcarlisle** [comment]
@NSoiffer  

> With the speech template, will authors really make sure to add an end word?

No, they wont. I suspect the easier we make it to supply a simple string,  the more you will be backed in to a corner and find it harder to generate anything else.

**Comment by dginev** [comment]
> With the speech template, will authors really make sure to add an end word?

If they do, they'll run into the inverse problem that such a word is not always needed and certain readers may prefer not to hear it. 

As far as #444 is concerned, this would have to be addressed with a convention that implies a symbolic expression, which AT can then use to decide if the provided words have to be modified for a specific reader. 

For example, 
`(my-cos: taken at ($x plus: $z))` 
may have to be written for the symbolic alternative of
 `my-cos@prefix(_taken_at, plus@infix($x,$z))`.

so that AT can infer to provide `end-my-cos` for certain readers and not others.

**Comment by brucemiller** [comment]
> @NSoiffer
> 
> > With the speech template, will authors really make sure to add an end word?
> 
> No, they wont. I suspect the easier we make it to supply a simple string, the more you will be backed in to a corner and find it harder to generate anything else.

I thought that was pretty much the point of the templates; that AT doesn't even try to generate anything else.

**Comment by davidcarlisle** [comment]
> I thought that was pretty much the point of the templates; that AT doesn't even try to generate anything else.

Yes but having tried it I have really gone off the idea. Basically any `intent` I add ends up being less accessible than having no intent at all and letting mathcat, ie Neil, generate something.

Just something seemingly trivial like wanting a fraction spoken as "divided by" instead of "over" you add
`intent="$n divided by $d"`  and (probably) you have prevented  AT separately announcing the numerator and denominator.

People (including me) will force the conventional, sighted, readings, not a reading appropriate for a screen reader.

**Comment by brucemiller** [comment]
That mathcad currently appears less accessible when using templates doesn't seem a fair test, since (as far as I understand), mathcad doesn't currently support any of those template syntaxes (but presumably *could*).

OTOH, your last comment, is spot-on: the template will/should read exactly what's given.  Whether that is a bug or a feature seems to depend on who you ask, and when you ask them.

**Comment by davidfarmer** [comment]
Maybe we are reaching the conclusion that intent is for cases that
are truly ambiguous, and authors are discouraged from using it to
select among different pronunciations of the same mathematical
concept (because they could make it worse!).

So, fractions should not get an intent, if they are just fractions.

f(x), where there is a FunctionApply after the f should not get an intent
saying that  f  is a function and  x  is its argument.
(And in general, it is better to put the effort into making the MathML
markup better, especially when that removes the need for intent).

|x|  and  (a,b)  should get an intent.

If I write  f * g , and that has a specific meaning, then put an intent
on the  *  .  And be happy with the fact that it will say
"f foobar g"
and don't try to force it to say
"the foobar of f and g"

**Comment by dginev** [comment]
> authors are discouraged from using it to select among different pronunciations of the same mathematical concept (because they could make it worse!).

Rather than design for any given implementation approach, (or design in fear not to make its outcomes worse), I think we should instead focus on the phenomena we see in examples, and which intent syntax has the right trade-offs to improve "bad AT outcomes" into "good AT outcomes", compared to the baseline MathML 3 readouts.

Being able to force specific speech is useful *exactly* in cases where AT systems haven't implemented sufficient coverage (i.e. the Open terrain). 

It is natural to expected better AT outcomes for a "simple symbolic syntax" in Intent Core where AT knows "as much as a mathematician", and better AT outcomes for a "simple template syntax" in Intent Open where AT "knows only the Presentation tree". 

The question is if we have sufficient ability to design a syntax combining the two aspects, or if we'll leave one of the sides in the "dirty hacks" territory. As David C has reminded in different issues, we can't actually forbid users of Intent to force the speech, we can only make it look prohibitively ugly. `divided-by@infix($n,$d)` or `_($n, _divided-by, $d)` or ... will remain possible, and will be used if found useful.

I expect (and can testify that) people who remediate documents in the "Open" realm will have to reach for things of that caliber on occasion, until AT's special casing rules cover the entirety of STEM.

**Comment by davidcarlisle** [comment]
> That mathcad currently appears less accessible when using templates doesn't seem a fair test

Yes sorry, I was comparing what mathcat _actually_ generates with no intent to what (I _think_) the  "template" issues specify should be generated with various added intents.

The end result  after trying  several of these was that I was a lot less convinced I could improve things by adding an intent than I was when I started.

> Whether that is a bug or a feature seems to depend on who you ask, and when you ask them.

Yep. I would have given a different answer last week, and I'm not sure I won't give a different one next week.

**Comment by davidcarlisle** [comment]
for example

```
<mfrac intent="$n over $d">
 <mrow arg="n"><msup><mi>x</mi><mn>2</mn></msup><mo>+</mo><mn>1</mn></mrow>
 <mrow arg="d"><msup><mi>x</mi><mn>2</mn></msup><mo>−</mo><mn>1</mn></mrow>
</mfrac>
```

Looks I think reasonable in any of 44x "template" versions and will occur often even if we advise against it. 

Currently it doesn't parse but I _think_ we are proposing that this forces

```
x squared plus 1; over; x squared minus 1;'
```

whereas if left without intent I get

```
the fraction with numerator; x squared plus 1; and denominator x squared minus 1;
```

I can't see anyone supplying inline speech templates with this kind of structural announcement built in.

**Comment by brucemiller** [comment]
>  we can't actually forbid users of Intent to force the speech, 

Of course we can: simply be not giving them the means to do so.

> I expect (and can testify that) people who remediate documents in the "Open" realm will have to reach for things of that caliber on occasion, until AT's special casing rules cover the entirety of STEM.

*have* to? They may *think* they have to, but in doing so will they actually make the speech less, rather than more, accessible?  It's not clear to me whether "natural speech" is the goal here (depending on which way the wind is blowing).

**Comment by davidcarlisle** [comment]
>have to? They may think they have to, but in doing so will they actually make the speech less, rather than more, accessible? It's not clear to me whether "natural speech" is the goal here (depending on which way the wind is blowing).

Yes I think (this week;-) we were right with the original intent of intent: Allow the author to disambiguate the meaning, but mostly leave it up to AT to generate appropriate speech forms, even if that is not the form the author would use.

**Comment by davidcarlisle** [comment]
On the call 2023-03-16 we agreed to close this and consolidate discussion of template variants of  ìntent` in #446
