### ISSUE TITLE
Named functions and superscripts

### ISSUE THREAD

**Issue by davidfarmer** [w3c/mathml#447]
Here are two suggestions for core which are slightly different than
the other core intents I have been thinking about.

Named functions
---------------

If  A(n,m)  is the Ackerman function, then `intent="Ackerman"` is
not optimal because the reader may prefer hearing  "A"  instead
of "Ackerman" if it appears repeatedly.  There is no simple way
for the AT to over-ride the verbose reading.

Consider

`<mi intent="named-function('Ackerman')">A</mi>`

The `named-function` intent tells AT that a verbose setting
should use the name of the function, but with a terse setting it
is okay to use just the literal content.

There are many special functions where this could be useful.

Superscripts as indices
-----------------------

Subscripts are usually thought of as an index.  So  `x_n`  might
be pronounced as  "x sub n", depending on the AT.

Sometimes superscripts are powers and sometimes they are
indices or something else. I suggest `intent="index"` to indicate
it is not a power.

Thus, the square integrable functions on the set `X`, denoted
`L^2(X)` in LaTeX and usually pronounced  "ell two of X"
would be

```
<msup><mi>L</mi><mn intent="index">2</mn></msup>
<mo>&ApplyFunction;</mo><mo>(</mo><mi>X</mi><mo>)</mo>
```

Maybe AT will pronounce it "ell sup two" instead of "ell two",
but that is okay since it is better than "ell squared"
and I think we already agreed that we don't want the author
to micromanage the pronunciation.

This idea leverages the fact that AT already has to examine
the contents of a superscript because of special cases like
squared and cubed.  So the `index` intent does not need to
go on the msup.

The `index` intent can take an argument, as in this example
involving the Gegenbauer polynomials, in LaTeX:
`G_n^{(\alpha)}(x)`.  Note that the MathML indicates
the parentheses around the alpha are not pronounced:

```
<msubsup><mi intent="named-function('Gegenbauer')">G</mi><mi>n</mi>
<mrow intent="index($x)"><mo>(</mo><mi arg="x">α</mi><mo>)</mo></mrow>
</msubsup><mo>&ApplyFunction;</mo><mo>(</mo><mi>x</mi><mo>)</mo>
```

Maybe the `index` intent makes people more comfortable with "power"
being the default intent of a superscript?

(Apologies to the DLMF, which prefers "Ultraspherical" to "Gegenbauer"
and uses a C instead of a G.)

**Comment by davidcarlisle** [comment]
Yes I expect `<mn intent="index">2</mn>` could be handled as `<mn intent="@index">2</mn>` or `<mn intent=":index">2</mn>` in the current proposals, otherwise it's going to get read as "index" .

(Not) reading the name is something I worry about, especially with the "template" versions of intent where I suspect the system will have a lot less flexbility to do other than read the template string (or ignore it and read the notation).
In my own area, a lifetime ago, $H^3$ was almost always the third co-homology group, but usually you'd just read "H3" .

The problem with `<mi intent="named-function(Ackerman)">A</mi>` is that's hard to integrate with existing proposals where intent (if used) masks the element content. `<mi intent="x">y</mi>` is read as x.  

It could be a special case core function (I suppose) that optionally acted as if it was not there 

or it could have both forms in the intent  `<mi intent="named-function(Ackerman,A)">A</mi>`

or maybe it's enough to have `<mi intent="Ackerman">A</mi>`  and rely on an existing global option to directly read the characters in the notation, so `A`, not the intent.

**Comment by NSoiffer** [comment]
## Named Functions
Both MathCAT and SRE have a verbosity setting, and that is I think the appropriate way to decide whether to read a long form or a short form. The big drawback though is that it is global, so all or nothing. One can imagine a counter where someone says "switch to the short form" after (user setting) 10 times, but that's very speculative. The key however is to give AT a way to make some choice. I think a property such as `verbose` would be useful. Then you can write
```
<mi intent='Ackerman:verbose'>A</mi>
```
The AT in verbose mode would use the intent but in terse mode would use the contents (this is just brain stormng).

Somewhere we would need to document the various properties and what they might be used for. We haven't really gotten to that step, but your suggestion of a verbose/terse reading seems like a quite useful property.

## Superscripts as indices
My first instinct is to say the "L 2" example should be marked up as (using properties)
```
<msup intent=':silent'><mi>L</mi><mn intent="index">2</mn></msup>
<mo>&ApplyFunction;</mo>
<mo>(</mo><mi>X</mi><mo>)</mo>
```
Other possibilities on the `msup` (depending on details to be worked out on how properties work):
`intent='index:silent($base, $exp)`
`intent='$base $exp'`
or even `intent=index($base, $exp)` where `index` would be a core function

**Comment by davidcarlisle** [comment]
> `<mi intent='Ackerman:verbose'>A</mi>`

I like this, in general using properties to access system specific options in a controlled way looks like it may be a useful thing.

> `<msup intent=':silent'><mi>L</mi><mn intent="index">2</mn></msup>`

I would have expected that to have produced silence?

you could also do

`<msup intent='L2'><mi>L</mi><mn>2</mn></msup>`

> intent='index:silent($base, $exp)

yes I have used that (with `@silent`) in some of the examples with the current function/hint form.

**Comment by davidfarmer** [comment]
I am specifically suggesting "index" as a core intent.  I think it is important and common
enough to warrant that, instead of using "silent" or some other generic approach.

Similarly for "named-function".  If it is in core, then AT knows how to incorporate
it into its verbosity settings.  There also is a case for indicating another level of
verbosity.  For example, 
`named-function('Bessel function of the first kind', 'Bessel-J')`.

A `verbose` parameter, as in `intent='Ackerman:verbose'` could be usable
in other contexts and maybe avoid the need for `named-function`.

**Comment by davidcarlisle** [comment]
> `named-function(Bessel function of the first kind, Bessel-J)`

Yes I  nearly suggested `<mi intent="named-function(Ackerman,A)">A</mi>` in response to your first example.

(it would need to be without the quotes).

I'm a bit nervous about that though as I think all other suggested core functions, if the system doesn't recognise them (despite a SHOULD  requirement) nothing too bad happens, if you get "power of x comma 2" instead of "x squared" you'd survive, but you'd I think never want that read as "named-function of Bessel function of the first kind comma Bessel-J" so it's more like a mandatory syntax extension than a normal intent function that is popular enough to be in core.

**Comment by NSoiffer** [comment]
>I like this, in general using properties to access system specific options in a controlled way looks like it may be a useful thing.
```
<msup intent=':silent'><mi>L</mi><mn intent="index">2</mn></msup>
```
> I would have expected that to have produced silence?

My thinking is that if you have `foo:silent($x)`, then `foo` is not pronounced, but the `$x` value is. So leaving off  `foo` says "don't say whatever you would have said for this element", just pronounce the arguments. This means you don't need to introduce an artificial name to get silence.

Note: I'm not saying this is the best way to mark it up, just that it is one option.

If we do introduce an `index` intent for core, then (as David alluded to), it should make sense if AT doesn't handle it. So, does "index L comma 2" make sense in this case? Is there a better word to use?

**Comment by davidcarlisle** [comment]
@NSoiffer 

> My thinking is that if you have foo:silent($x), then foo is not pronounced, but the $x value is. So leaving off foo says "don't say whatever you would have said for this element", just pronounce the arguments

I was thinking  
`<msup intent=':silent'><mi>L</mi><mn>2</mn></msup>`   
is not a funcall so it's like  
 `<msup intent='wibble:silent'><mi>L</mi><mn>2</mn></msup>`   
which is silent. But (I think)
` <msup intent=''><mi>L</mi><mn>2</mn></msup>`   
is not a string template of empty but "no template" so does pronounce the L 2 so your interpretation is certainly possible, and probaby more useful.

For  all the 44x template variants though, the simplest way to get " L 2" is 
`<msup intent='$L $n'><mi arg="L">L</mi><mn arg="n">2</mn></msup>`

If we don't want people to do that, why are we adding templates and not sticking to the function-only form in the current spec?

**Comment by davidfarmer** [comment]
I don't understand the concern about a hypothetical AT which implements "intent"
but does not understand how to handle something in core.

That same (hopefully non-existent) AT might say the word "silent" pretty often,
and pronounce "$x" as "dollar eks".  There are many examples of what could go
wrong if AT only partially implements the core elements and the basic idea of `intent`.
Are the concerns about `named-function` different in some way?

By the way, we also need `named-set`and maybe a couple others.  `named-object` could
cover them all, but I like the idea of saying what it is.  Sort-of what `isa` is supposed to do. 
Maybe `named-X` is valid for any string `X`, and most AT ignores the value of `X`.

If we can't assume that AT properly handles core, then why are we expending effort to
figure out the right way to do things?

**Comment by davidcarlisle** [comment]
> That same (hopefully non-existent) AT might say the word "silent" pretty often,

Not if `:silent` / `@silent`  is a property/hint.

The current wording is that the list of functions known to the system is open but SHOULD include the list in core, so this is a much softer requirement than the system being able to parse the intent syntax.

> Are the concerns about named-function different in some way?

If it  is a function, the currently defined default behaviour would be to pronounce the name and to mask the element content except as referenced by `$arg` so

`<mi intent="named-function(Ackerman)">A</mi>`

would be "named-function of Ackerman"  and A would not be pronounced at all.  You could have


`<mi intent="named-function(Ackerman,A)">A</mi>`

with a core function that just read one of its arguments or of course we could specify the rules in a way that `<mi intent="named-function(Ackerman)">A</mi>` could say A, but we'd need to say how that worked in general not just for this. 

In all previous iterations of an intent spec if an intent has no `$arg` (or implied self ref from `$self` or leading `:` or something) then the generated speech is a function of the intent string, not the element content.

`<mi intent="B">A</mi>`

is an A pronounced B.

We can change it but we would have to find a general mechanism for when the element content is referenced.

`<mi intent=":Ackerman">A</mi>`

would (in 446 version of templates) be an A which had a Ackerman property that the AT may make available in some system specfic way. Is that enough or do we need more? The whole pressure for these template versions is to have simpler syntax, which makes it harder to add specific features.

**Comment by dginev** [comment]
> I don't understand the concern about a hypothetical AT which implements "intent"
but does not understand how to handle something in core. [...]
> Are the concerns about named-function different in some way?

Custom artifacts that go beyond a unifying principle (such as "encyclopedic concepts") pose an additional cognitive and implementation burden on developers (for both generation and consumption of Intent). 

Each new special-purpose construct that gets added to `Intent` makes the spec harder to adopt. (`$ref`, `:property`, `@hint`, custom names, aliases, self-references, speech overrides, global lists, multiple separators, are examples of such constructs).

To maximize the chances of success for Intent's adoption, the range of provided features should be chosen carefully, ideally with broad consensus by the ecosystem of AT-adjacent developers. And since we have the option to continue extending Intent in MathML 5, starting with a small initial basket of features is a viable approach, at least in theory.

**Comment by NSoiffer** [comment]
Catching up a little...

I wrote
> My thinking is that if you have foo:silent($x), then foo is not pronounced, but the $x value is. So leaving off foo says "don't say whatever you would have said for this element", just pronounce the arguments

My example should have used the functional syntax
```
<msup intent=':silent'($l, $index><mi arg='l'>L</mi><mn arg='index'>2</mn></msup>`.
```
I agree with @davidcarlisle  reasoning that without the functional syntax, it would just be silent.

@davidfarmer wrote:
> I don't understand the concern about a hypothetical AT which implements "intent" but does not understand how to handle something in core.

We will come out with an initial list for core, but it will grow over time. All AT will never be in exact sync with core, so it is important that if an intent is added to core, then AT that reads non-core elements read it in some reasonable manner -- i.e., the name should make sense if read. For example, "power of x comma 2" is far from ideal, but at least it is meaningful. Even for the initial list, this principle of "sensibility" for the name choice is a good one to follow.

**Comment by davidfarmer** [comment]
Closing, because I will submit a separate issue with a functional intent grammar that
incorporates (but improves upon) these suggestions.
