### ISSUE TITLE
merge hints and properties

### ISSUE THREAD

**Issue by davidcarlisle** [w3c/mathml#450]
After the call on 2023-03-16 we still have three currently active `intent` proposals

1. [current spec](https://github.com/w3c/mathml/blob/f59c7688557132d1f83e070d04510fc92c94ff4f/src/mixing.html#L72) `@` hints with a fixed list
3.   PR #438 which adds `:` properties to the grammar from 1.
4.  The template version from #446 which has `:` properties and no `@`

It would be good to reduce the number of variants and to allow the public spec to better track recent discussions.

Experience with examples using  #446 suggest merging hints and properties is viable and allows a useful simplification of the grammar avoiding questions about relative positioning of `@` and `:`

I would propose to modify #438 so that it drops `@` and just has `:`, and then to merge to the main branch. All recent discussons have assumed properties in some form, so the current spec version is misleading.

We could use `@` for the combined hints/properties but using `:` has the nice feature that most "good" intent examples would be valid for both the functional and template variants, allowing easy comparision. Differences would only show on multi-word template strings v `_(_whatever`

**Comment by brucemiller** [comment]
See also the discussion in #436, which gradually evolved into essentially this proposal.

**Comment by NSoiffer** [comment]
Since we allow multiple properties, and the properties have many potential uses, it doesn't seem necessary to call out "syntax" as a specific use with `@`, so let's go ahead with the merge.

**Comment by davidcarlisle** [comment]
completed by #438
