### ISSUE TITLE
Nested intents, or separate tree?

### ISSUE THREAD

**Issue by davidfarmer** [w3c/mathml#453]
As discussed in #451 , a tricky situation is when the presentation
tree does not reflect the mathematical structure.  An example
suggested by @dginev is "the mean of (x sub i)" .  Parentheses
added to indicate the mathematical meaning.

Two reasonably common ways of writing that are, LaTeX notation:
`\overline{x}_i`  and  `\langle x_i \rangle`.  (Let's not quibble
over the different between mean and expected value.)

In MathML:
```
<msub>
  <mover accent="true">
    <mi>x</mi>
    <mo>¯</mo>
  </mover>
  <mi>i</mi>
</msub>
```
and
```
<mo>⟨</mo>
  <msub>
    <mi>x</mi>
    <mi>i</mi>
  </msub>
<mo>⟩</mo>
```

The first example does not accurately convey the meaning,
because it looks like "(the mean of x) sub i".  But that is
common notation and the reader is supposed to interpret it correctly.

Wrapping the second example in an `mrow` allows one to accurately
indicate the meaning/pronunciation by only referring to `$arg`s,
with no nesting of function calls.

The first example requires either changing the presentation tree,
or nesting function calls.

Proposal:  keep the simpler, functional intent notation, with no nesting.

Allow an `intent-tree` attribute which is used by AT.  An element could have
either an `intent` or an `intent-tree`, but not both.  The `intent-tree`
would be MathML markup with `intent`s contained within it.
(Not sure if the intent-tree contains the markup, or the id of a hidden
element containing the markup.)

This allows the implementation by AT to be simpler.  It probably also
decreases the errors from hand-editing the intent since giving a meaningful
tree to AT, and trusting it to do the right thing, should lead to better results.

Using an `intent-tree` is probably not necessary when the only
changes are adding `mrow`s and `arg`s.

When there is an `intent-tree`, the AT would use that and not the
contents of the element or its children.  For the use case of a sighted
reader who what to hear the pronunciation and highlight the element,
then perhaps there could be a matching between the `arg`s in the
original tree and the `intent-tree`.

**Comment by davidcarlisle** [comment]
MathML already has a way of attaching a logical tree following the mathematical meaning,

```
<semantics>
 <mrow> ... </mrow>
 <annotation-xml>.
   .. Content MathML or OpenMath or lisp S-expression or whatever tree syntax is needed
</annotation-xml>
</semantics>
```

It seems to me the whole point of `intent` is to provide an inline annotation that does not require referencing a parallel tree structure.

**Comment by dginev** [comment]
@davidcarlisle I had left what I thought were two nice examples that even without an extra affordance (such as a new attribute, or resorting to `<semantics>`) a pure Presentation tree can introduce an element scaffold that can carry a complex intent, when only using the simple syntax of #451 : 

https://github.com/w3c/mathml/issues/451#issuecomment-1475303842

So one doesn't really *need* any special-purpose markup, just a more elaborate scaffold of `<mrow>`s. What's worse, no Intent proposal is *immune* to generators introducing such scaffolds, irrespective of what the exact intent attributes and syntax may be. The moment `$references` are allowed, the cat is out of the bag.

If someone had the desire to insist on only the simplest possible intent expressions being possible in theory, I think they would also need to enforce a canonical (minimal) element scaffold for the presentation tree.

**Comment by davidcarlisle** [comment]
@dginev  yes I agree they are good examples, I took them as showing why you should not restrict function arguments to `$argref` as it is not actually a restriction so much as forcing a less natural markup.

**Comment by NSoiffer** [comment]
I'll second @davidcarlisle's "good examples".

The grammar can make it harder to do some things, but given `_` as a function or `:silent`, restricting references in the function head can won't stop "bad" markup. And we definitely need `$references` for function arguments, so clever folks like Deyan will find ways to do things that I don't like/think are bad. Still, it doesn't mean the design can't discourage "bad" markup by making it more convoluted to do that markup.

**Comment by davidcarlisle** [comment]
>  Still, it doesn't mean the design can't discourage "bad" markup by making it more convoluted to do that markup.

Agreed, which is why it is problematic to restrict function arguments to `$argref` as in practice it encourages the bad markup of `<msub>`  inside `<msup>`  rather than the good markup of `<msubsup>` for  $X_i^n$

Actually I have not  seen here or in #451 any real motivation for the restriction. It is not related to the rest of that proposal. It is a restriction that could be made for any of the intent proposals, including the functional version in the current draft or funcall arguments in the template version in 446

**Comment by davidfarmer** [comment]
I accept that preventing nested intents  can lead to problems.  And based on the
recommendations I assume nesting does not significantly complicate the work
for the AT producers.

Closing, and I will look at the implications for #451
