### ISSUE TITLE
Must core intent work as a literal expression?

### ISSUE THREAD

**Issue by davidfarmer** [w3c/mathml#455]
I am having trouble understanding how to write core intents
if it is necessary that those provide a reasonable reading
if spoken literally.  This seems to remove the distinction
between core and open.  But if "core" does not mean "what we
can reasonably expect AT to know about", then what is it?

Maybe what I am asking for is some progress on what is in core,
confirming that it can handle what we need it to do.

Here are some specific instances:

1) How to say "this is a matrix" or "this is a vector" or
"this is a system of equations"?  In all those cases there
is more than one way to markup the content.

2) How to disrupt the usual pronunciation of superscripts
and subscripts?  For example, when  H^2  is not "H squared"
and  \log_2  is not "log base 2".

I am fine with  "H sup 2"  and  "log sub 2".  My preference
is to put an intent on the  `mn` containing the 2,
either `intent="index"` in both cases,  or  `intent="subscript"` or
`intent="superscript"` as appropriate.  None of those give
sensible output when only the intent is pronounced:  the AT has
to also say the content of the `mn`.

Putting the intent on the `msup` requires the intent to encode
the fact that the "2" is in a subscript or superscript.  But that
information is sitting there in the markup!

3) The previous example concerns `msub` and `msup`.  Examples
involving `mover` include  \overline{z} , which may mean
complex conjugate, and  \hat f , which may mean Fourier transform.

Both of those could be accomplished by an intent on the `mover`.
Why should `mover` require a different treatment than `msup`?
A specific example to consider is  z^* , which may also
mean complex conjugate, but uses an `msup`.

4) The expression `{a | b}` might mean "the set of a, with conditions b",
or "the set of a, such that, b", commonly (in the US) called
"set builder notation".  This could be specified by
`intent="setbuilder($a, $b)` on a surrounding `mrow`.  Requiring
the intent to self-pronounce seems to require a more cumbersome markup,
including words in the language of the author.

5) How to indicate the name of an object?  For example,  `J` might
be a "Bessel function of the first kind", colloquially referred to
as "Bessel-J".  Authors feel a need to tell the name of an object.
How to tell AT that a particular `J` is a Bessel function of the
first kind, but not force AT to say that phrase every time?
DLMF puts the full name in the element's `title`.

I think it would be preferable to distinguish between a standard name
and a name which is not well-known, possibly coined by the author.

6) How to indicate the value of a number?  All of `3.14`, `3,14`,
and `0.314e1` represent the same number.  There also are complex
numbers.  I think we should allow many formats.  This could be
accomplished by a specified wrapper for numbers.  (Issue #451 mentioned
`number(.)` and `[.]`.)   That markup is not be self-pronouncing.

**Comment by davidcarlisle** [comment]
Some **personal** answers.

"this is a .." can be marked up as  a property on an empty intent so `<mtable intent=":system-of-equations">` although we do need to enumerate some standard properties, as we have for `infix` etc  see https://mathml-refresh.github.io/intent-lists/intent5.html#IDbracedsystemofequations
(which currently gets read as "cases" as I just made up the property name)

> How to disrupt the usual pronunciation of superscripts

again a property, most naturally on the msup I think
see https://mathml-refresh.github.io/intent-lists/intent5.html#IDhofconvexconjugate
where I used a (speculative) property to stop it being `power` although that is not actually needed here as mathcat picked up the `*` and did not default to power here that won't always be the case.

> include \overline{z} , which may mean complex conjugate

many over bar readings from your original spreadsheet are suggested at

https://mathml-refresh.github.io/intent-lists/intent1.html#id70

> The expression {a | b} might mean "the set of a, with conditions b",

I used such-that here:

https://mathml-refresh.github.io/intent-lists/intent1.html#id62

> but not force AT to say that phrase every time?

currently you have the option of not supplying the long name every time or perhaps

`<mi intent="Bessel-function-of-the-first-kind:read-content">J</mi>`

would tell AT to use J while still leaving the long name available, or perhaps we can extend the syntax as you suggested earlier to provide `(long | medium| short)` names.... (to be decided...)

I think you can possibly use `intent=123.456`  together with some properties. 

Some speculative suggestions that don't really work at

https://mathml-refresh.github.io/intent-lists/intent3.html#IDNumbers

**Comment by davidcarlisle** [comment]
>  But if "core" does not mean "what we can reasonably expect AT to know about", then what is it?

I think it's a list that we say SHOULD be implemented (in spec legalese)

Effectively that means that initial implementations of an initial list probably will implement them. However unless we then freeze the list for all time, it will be highly likely that at any given time some implementations do not have rules for some core functions. They will not be non-conformant, just not meeting that "should" requirement.

**Comment by dginev** [comment]
> How to tell AT that a particular J is a Bessel function of the
first kind, but not force AT to say that phrase every time?

My suspicion is that specific AT guidance of this sort is better left as "out of scope" for Intent and delegated to AT system configuration. See SRE's [options to control speech output](https://github.com/Speech-Rule-Engine/speech-rule-engine#options-to-control-speech-output) as one example.

There are many possible questions about speech customization:
 - when to use an intent name vs using the presentation,
 - what narration to use upon repetition (and at which point of repetition),
 - what narration to use in standalone context (e.g. `<math>`) vs deep down in a large expression tree.
 - which connector words to use in which contexts (open-interval "from"-"to" vs open-interval "between"-"and")
 - lengths of pauses/connector words based on how deep an operator is, how many and what kinds of arguments it is provided, and which other operations are in the surrounding context
 - and more

The other point I like to raise is that a lot of the required metadata happens to be "global" in nature - and would fit well within a shared global list/dictionary/resource of some sort. In contrast to specifying configuration details each time an `<mi>J</mi>` is written in a document.

The part that falls conveniently within the "ARIA parity" realm is having an "accessible description". That description is provided and available *on demand*, and remains otherwise unspoken (e.g. carried via [aria-description](https://w3c.github.io/aria/#aria-description)). Being able to provide that was one of the original motivations of isa #426 (now `:properties`). In this example it is simply:
```
<mi intent=":bessel-function-of-the-first-kind">J</mi>
```

**Comment by davidfarmer** [comment]
Some properties are special and are (or should be) immediately useful to AT, such as
"this is a matrix".  Other properties are maybe useful in the future, such as the name
of a function, or the fact that G is a group.

We are hiding useful information if there is no indication of the category of the property.
That is: a name, or a class of mathematical objects, or some other mathematical
property such as being prefix.

**Comment by dginev** [comment]
> Some properties are special

I dislike special cases - I tend to call them artifacts, to make my bias clear. Artifacts increase the learning curve, make the spec more complex to implement, and harder to reason about. To my taste no property is special, but some are expected to be "supported". 

A `:matrix` property may be so useful and common that the spec gives it a "Core" label and states compliant tools SHOULD provide dedicated speech rules for it.

Most properties won't be expected to be "supported". To stay consistent, it would help the predictability of narration if all property values are chosen to be self-vocalizing (as a baseline narration fallback).

---

> We are hiding useful information if there is no indication of the category of the property.

Right, if there is no guiding principle to what goes inside the property values, they're too chaotic to do symbolic manipulation of any kind. They would still be perfectly usable for an accessible description text.

My current guiding principle is "encyclopedic names", where there is an (optional) external global resource (or several) that can be anchored into for additional information. 

E.g. for the Bessel function example there is a unique [wikipedia page](https://en.wikipedia.org/wiki/Bessel_function) and associated [wikidata page](https://www.wikidata.org/wiki/Q219637), the latter containing a `subclass of: function; subclass of: special function` annotations. An ambitious AT could precompile a large list of ~10,000-20,000 of such entries, in anticipation of their use. 
There are even redirects available for anchoring the specific function names, 
- e.g. "https://en.wikipedia.org/wiki/Bessel_function_of_the_second_kind"
- redirects to "https://en.wikipedia.org/wiki/Bessel_function#Bessel_functions_of_the_second_kind"

If we are to keep Intent sufficiently simple, it is a reasonable trade-off to delegate the "ontology building" aspect of formalization to a different mechanism, possibly one that is completely external to MathML. 

Another similar consideration that Neil had mentioned is to make provisions for "bound variables" in large operators, such as sums, products, integrals. For similar reasons I would prefer that kind of formalization also remain out-of-scope for Intent, as whether a variable is free or bound does not influence narration. If a generator/author finds that information to be crucial, they can always reach for `<mi intent=":bound-variable">x</mi>` and `<mi intent=":free-variable">y</mi>`, with an expectation of a self-vocalizing accessible description (i.e. as Open realm properties)

**Comment by davidcarlisle** [comment]
> We are hiding useful information if there is no indication of the category of the property.

Yes possibly. We have tried having two categories hint (`@`) and property `:` but have them currently merged.

It depends how things work out, if there is a fixed list of properties directly affecting speech `infix`, `silent`, `system-of-equations` ...  then perhaps it's enough  to have everything else being an open list that may be known to some application.

Or it has come up more than once if we will need some name=value scheme to extend the essentially boolean properties

`G :wikidata=Q83478: openmath=group1-group :whatever`

but it's a lot of syntactic overhead if we don't have a clear use case for what is going to use the property.

in practice the properties in a document don't need to be globally unique, if you know any property in the document matching Q... is  wikidata identifier you don't need `:wikidata=Q83478` simply `:Q83478` would be enough.  perhaps.

**Comment by dginev** [comment]
> :Q83478

@davidcarlisle I would probably lean to using:
```xml
<semantics intent=":bessel-function-of-the-first-kind">
  <mi>J</mi>
  <csymbol cd="wikidata">Q219637</csymbol>
</semantics>
```

if you wanted to anchor to a concrete wikidata id at that exact location. Hearing the Q-id spoken out loud as part of `intent=":Q219637:bessel-function"` could be quite disorienting for a non-sighted reader who requests the accessible description of the element. Imagine a MathML expression which has these Q-id properties added on *every* meaningful element - it would be really artificial to vocalize.

Edit: but really, I think the formalization details are global, and don't have to be in the actual document. Connecting `:bessel-function-of-the-first-kind` to `Q219637` should be possible to do just once, in an external list of some sort.

**Comment by davidcarlisle** [comment]
@dginev 

> Hearing the Q-id spoken out loud as part of intent=":Q219637:bessel-function"

oh sure yes,  with that suggestion I was assuming a workflow where unknown properties were ignored, so Q219637 would never get read, If an application knew it was wikidata, it could look it up and possibly generate speech or a link, otherwise it would be as if it wasn't there.   That seems to be the main difference between `foo` and `bar` in `intent="foo:bar"` , `foo` by default will be read as-is  `bar` by default will do nothing.

**Comment by davidfarmer** [comment]
Based on the comments here, and the discussion on the call, I think it is
workable to not distinguish between different types of properties.
You can say `G is a group` or `G is abelian` or `G is a dihedral group`
by using as many properties as you wish.

It remains to decide which of those properties are supposed to be known to
AT.  I think we also need to start agreeing on some simple/common examples of
intent markup.

So I will close this issue and open another, to discuss some particular examples.
