### ISSUE TITLE
Redirect old editor's draft

### ISSUE THREAD

**Issue by annevk** [w3c/mathml#468]
https://www.w3.org/Math/draft-spec/ should point to the latest editor's draft.

**Comment by davidcarlisle** [comment]
oops, thanks.

Predates public github drafting, tempted to delete but I guess a redirect safer.

**Comment by davidcarlisle** [comment]
fixed:

```
$ cvs diff .htaccess
Index: .htaccess
===================================================================
RCS file: /w3ccvs/WWW/Math/.htaccess,v
retrieving revision 1.27
diff -r1.27 .htaccess
11a12,13
> RewriteRule ^draft-spec/(.*)$ https://w3c.github.io/mathml/$1 [Redirect,Last]
> 
```

**Comment by annevk** [comment]
Anyone stumbling upon https://www.w3.org/TR/MathML3/ (which https://www.w3.org/TR/MathML/ redirects to at the moment) would want it to redirect. Also https://www.w3.org/Provider/Style/URI.html.
