### ISSUE TITLE
Add a :structure (or :literal) property?

### ISSUE THREAD

**Issue by NSoiffer** [w3c/mathml#492]
Some of us just finished a paper talking about `intent`. In it, we have several examples, including examples that say "... can be spoken as ... or as ...". In this case, we want no interpretation. E.g., $|x|$ should be spoken something like "vertical bar x vertical bar". That is, we want it to speak as "vertical bar x vertical bar can be spokens as absolute value of x or as determinant of x".

Without a property, this would have to be done using literals:
```
<math>
  <mo intent="_vertical-bar">|</mo>
  <mi>x</mi>
  <mo intent="_vertical-bar">|</mo>
</math>
```
This isn't horrible, but a property seems more elegant IMHO.

**Comment by davidcarlisle** [comment]
I thought we had added `:structure` to the core properties already, but apparently not.

The mathml example collection does have a `:structure` version of every example eg


https://w3c.github.io/mathml-docs/intent-examples/#id-2-871ed5ca252d8234d40d5a3cb7907740

which shows

```
<math intent=':structure' display='block'>
 <mrow>
  <mo>|</mo>
  <mi>x</mi>
  <mo>|</mo>
 </mrow>
</math>
```

read by MathCAT as `vertical line x vertical line`

**Comment by dginev** [comment]
This has been discussed on a couple of previous occasions, mostly related to "default modes": https://github.com/w3c/mathml/issues/433#issuecomment-1420212046

What I remember is that it partially overlaps "legacy mode", but explicitly prevents AT from making guesses, insisting on speaking the exact presentation structure/layout of an expression.

I think `:literal` is a bad fit for that, `:layout` seems better. But `:structure` is a good fit as well.

**Comment by NSoiffer** [comment]
It's embarrassing when someone else points out that I have already mentioned this and I had forgotten my own contribution  :-)

We haven't discussed [my suggestion](https://github.com/w3c/mathml/issues/433#issuecomment-1420212046) in a while, but rereading it, I still agree with it.  As it pertains to to this discussion, `:structure` along with how it should be handled/what it means still seems right to me.

Focusing on just the `:structure` description I gave (click on details in the link), are people generally ok with that part? Are there changes people would like to see?

If we get agreement, I can move it into the [core properties list](https://w3c.github.io/mathml-docs/intent-core-properties/).

**Comment by davidcarlisle** [comment]
`:structure` looks good to me

**Comment by dginev** [comment]
To raise the concern early, [structure](https://en.wikipedia.org/wiki/Structure_(mathematical_logic)) has a formal use in universal algebra, which I could imagine leveraged in the Open terrain as:
```xml
<mi intent=":structure">𝒜</mi>
```

As one would have done with `<span aria-description="structure">𝒜</span>`. So we may want to qualify the "structure".

This appears slightly related to the discussion in https://github.com/w3c/mathml/issues/488#issuecomment-1991870897 , which suggested `:by-column` or `:column-wise` as a hint to reading order. We may want to keep to a single naming convention and use `:by-structure`, or the fully qualified `:read-by-structure`?

**Comment by NSoiffer** [comment]
Choice of a name is important, but common names should be short (it's a basic feature of words in languages, although obviously not true for all common words). If the worry is that `:structure` might be used as an open property, I would say the open property is the one that needs to be longer/more explicit.

**Comment by polx** [comment]
What about `:typographic` ?
(I would be good also with `:verbatim`)

**Comment by NSoiffer** [comment]
I like `:verbatim`. In the paper, I chose the phrases "syntactic reading" and "semantic reading". So let me put `:syntactic` up for consideration. I'm not sure I'd vote for it though.

**Comment by davidcarlisle** [comment]
I don't like `:verbatim` at all, with my tex `\begin{verbatim}` hat on, that would make me think it would read 

`<mi>x</mi><mo>+</mo>...` 

 as

`less than em i greater than x less than ....`

Of the ones suggested I prefer `:structure` . While it could have potentially other meanings, as @NSoiffer says above, if we are defining core properties we get to choose. So other open/contributed properties can choose a different name.  The other core properties are similar: it's `:function`  which could potentially have had any number of meanings but we define what it is, we don't call it `:read-as-a-function-with-possible-of-connecting-word` to ensure a unique name.

**Comment by dginev** [comment]
Right, `:function` encounters the same problem, that's a good point.

**Comment by davidcarlisle** [comment]
@dginev or to read the same data differently, `function` and `silent` and the other core properties show that this isn't a problem. 

The core properties are (will be) defined in the spec, so by definition they will not clash with anything else. We should call it something that is vaguely representative of its use. calling it `:wibble` wouldn't help, but we do not have to worry about clashing with other uses.

**Comment by NSoiffer** [comment]
Summary from [25 April meeting](https://lists.w3.org/Archives/Public/www-math/2024May/0000.html) courtesy GPT4:

> The meeting revolved around determining whether to add a structural property and what to name it. NS favored the inclusion of a property to avoid being overly literal. DG suggested naming it "by columns" or "verbatim," emphasizing clarity. PL preferred "by notation," while NS leaned towards "syntactic" or "tree" to maintain a less semantic focus. Discussions also touched on the default levels for speech interpretation and handling exceptional cases like square roots and primes. Overall, the group aimed for clarity without overthinking terminology, seeking a balance between structure and intent in mathematical expressions.

I like the final line that suggests, at least as far as AI is concerned, the WG is pragmatic and moderate in its discussions. :-)

**Comment by NSoiffer** [comment]
The 2 May meeting decided to vote on a name and move on. The winner is "literal".

**Comment by davidcarlisle** [comment]
This property needs to be added to the list of core properties and the spec.

**Comment by NSoiffer** [comment]
Closing as text was added to the draft.
