### ISSUE TITLE
Remove some deprecated attributes

### ISSUE THREAD

**Issue by fred-wang** [w3c/mathml#5]
This proposal is to remove the following attributes:

1) general attribute: other.
2) math attributes: macros, mode.
3) mglyph attributes: fontfamily, index. See also #25
4) token elements attributes: fontfamily, fontweight, fontstyle, fontsize, color, background. See also #1
5) deprecated namedspace attributes: veryverythinmathspace,
verythinmathspace, thinmathspace, mediummathspace, thickmathspace,
verythickmathspace, veryverythickmathspace. https://mathml-refresh.github.io/mathml/chapter3.html#id.3.3.4.2.1 See also #1 and #75 

Math WG thread: https://lists.w3.org/Archives/Public/www-math/2016Aug/0008.html

**Comment by physikerwelt** [comment]
1. Should we suggest using data- instead?

**Comment by fred-wang** [comment]
These attributes are currently not in MathML Core, so this is just for MathML 4.

**Comment by fred-wang** [comment]
cc @rwlbuis, @emilio

We agreed on 2019-02-25 that currently deprecated attributes should not go into MathML Core: https://lists.w3.org/Archives/Public/public-mathml4/2019Feb/0048.html

I checked the spec & schema and cannot find any of the attributes listed in https://github.com/mathml-refresh/mathml/issues/5#issue-410423622

We still need to:
* [ ]  Check WPT tests (I doubt there are contained in any test)
* [ ]  Send intent-to-remove to mozilla/webkit-dev mailing lists (maybe old Math WG too?).
* [ ]  Remove browser implementation.
* [ ]  Decide what to do for the full MathML spec (remove them?).
* [ ]  Add polyfill to https://github.com/mathml-refresh/mathml-polyfills if necessary.

Note: some deprecated attributes might still be used like font or colors (e.g. https://bugzilla.mozilla.org/show_bug.cgi?id=1027354  ). Others have never been implemented or have already been removed without complaints ( e.g. namedspace attributes ).

Also, "mathvariant" is supposed to take precedent over the deprecated attributes "fontweight" and "fontstyle". In term of CSS, that means that mathvariant has to reset font-style/font-weight to avoid weird results. There are some hacks in Gecko/Stylo that can be removed once we get rid of "fontweight" and "fontstyle".

**Comment by fred-wang** [comment]
From https://lists.w3.org/Archives/Public/public-mathml4/2019Mar/0026.html 

1. Remove "other" from MathML full (maybe suggest data-*)
2. Remove macros, mode from MathML full
3. Remove fontfamily, index from MathML full
4. Deprecate fontfamily, fontweight, fontstyle, fontsize, color, background from MathML full
5. Remove named attributes thinmathspace etc

**Comment by fred-wang** [comment]
Resolution:
  https://github.com/mathml-refresh/mathml/issues/5#issuecomment-472827820

Specification:
  Removal/Deprecation from full, with extra explanations.

Implementation:
  WebKit: https://bugs.webkit.org/show_bug.cgi?id=197492
  Firefox: https://bugzilla.mozilla.org/show_bug.cgi?id=1548524
  Not implemented in Chromium.

Polyfill:
  TBD

Tests:
  - Remove WPT tests or check that these values are not supported.

**Comment by fred-wang** [comment]
These are not in core per https://github.com/mathml-refresh/mathml/issues/5#issuecomment-472827820 ; @davidcarlisle please check the full spec and do the necessary change, if any.

**Comment by fred-wang** [comment]
The mode attribute has been removed from Gecko:

https://bugzilla.mozilla.org/show_bug.cgi?id=1573438

(WebKit has never implemented it)

Polyfill:

    window.addEventListener("load", function() {
        const namespaceURI = "http://www.w3.org/1998/Math/MathML";
        Array.from(document.body.getElementsByTagNameNS(namespaceURI, "math")).
            forEach(math => {
                if (math.hasAttribute("mode")) {
                    var value = math.getAttribute("mode").replace("display", "block");
                    math.removeAttribute("mode");
                    if (!math.hasAttribute("display"))
                        math.setAttribute("display", value);
                }
            });
    });

**Comment by fred-wang** [comment]
* other, macros, fontfamily, index have never been implemented in browsers
* fontfamily, fontweight, fontstyle, fontsize, color, background was removed in https://phabricator.services.mozilla.com/D43111 and tests were added to mathml/relations/css-styling/attribute-mapping-001.html
* mode was removed in https://phabricator.services.mozilla.com/D41742 but no test were added
* named attributes thinmathspace etc were removed a long time ago from Gecko but I can't find any test

**Comment by fred-wang** [comment]
>     * mode was removed in https://phabricator.services.mozilla.com/D41742 but no test were added

- test added for mode: https://github.com/web-platform-tests/wpt/pull/19113

>     * named attributes thinmathspace etc were removed a long time ago from Gecko but I can't find any test

We have removed support for namedspaces **length values** in  #75 and have tests for that. So it does not seem necessary to test the legacy namedspaces **attributes** that allowed to override these values.
