### ISSUE TITLE
Add "grid" property for `mtable`?

### ISSUE THREAD

**Issue by NSoiffer** [w3c/mathml#504]
We currently have the core properties for tables: [matrix](https://w3c.github.io/mathml-docs/intent-core-properties/#prop-matrix) , [piecewise](https://w3c.github.io/mathml-docs/intent-core-properties/#prop-piecewise) , [system-of-equations](https://w3c.github.io/mathml-docs/intent-core-properties/#prop-system-of-equations) , [lines](https://w3c.github.io/mathml-docs/intent-core-properties/#prop-lines) , [continued-row](https://w3c.github.io/mathml-docs/intent-core-properties/#prop-continued-row) , [by-row](https://w3c.github.io/mathml-docs/intent-core-properties/#prop-by-row) , [by-column](https://w3c.github.io/mathml-docs/intent-core-properties/#prop-by-column).

It seems to me we left out a (default?) property for reading the table as just a table: `table` (or maybe `grid`). Am I missing something?

**Comment by dginev** [comment]
Isn't it the case that `lines`, `by-row` and `by-column` when used standalone already have that implication? 

Maybe a case for renaming `lines` to `table` ?

**Comment by NSoiffer** [comment]
`lines`, like `system-of-equations`, ignores column boundaries. It is useful for step-by-step derivations among other things.

`by-column` doesn't make sense for the properties that ignore column boundaries and really only makes sense for `matrix` (which is also used for determinants). So one could use `matrix` if you wanted to each entry read out, but `matrix` seems inappropriate for tables not related to matrices. Perhaps the right thing to do is to change the `matrix` property name to `grid` or some other generic layout term. That way one isn't confused by why there is `matrix` but `determinant` (what do I use for determinants?).

**Comment by dginev** [comment]
> [lines](https://w3c.github.io/mathml-docs/intent-core-properties/#prop-lines)
> Effect: the table should be read without implying any mathematical context other than a multi-line display

I think the documentation should directly say the column boundaries are silent. To me the current docstring for `:lines` is very close to how I imagine a new `:grid:by-row` readout.

`:matrix` has example readouts that use the `matrix` word, so it seems near a concept use. That makes it hard to rename into `:grid`.

**Comment by davidcarlisle** [comment]
As @dginev says, my understanding of the matrix property is that it is for mathematical matrices so  completely the opposite of a proposed grid property that would presumably imply a tabular layout with no implied mathematical structure

**Comment by NSoiffer** [comment]
Given the differing opinions, it seems clear that we need more clarity on the properties. 

@davidcarlisle: if `:matrix` is only for matrices, what is used for determinants? How would the speech of a matrix be different than that of a grid or determinant other than the wrapper around the table ("the 2 by 3 matrix ...")? That wrapper (or "the 3 by 3 determinant...") comes from having parens or brackets around the `mtable` (or vertical lines).

Note: the spec lists "lines" but only describes "matrix" and "system-of-equations".  The [core property doc](https://w3c.github.io/mathml-docs/intent-core-properties/#prop-lines) says
> lines
>   Effect: the table should be read without implying any mathematical context other than a multi-line display
>  Applicability: mtable

@dginev: that seems pretty clear that it is columns should _not_ be read.  On the other hand, it doesn't hurt to be more specific for all of the table properties as misinterpretations happen as evidenced here.

**Comment by davidcarlisle** [comment]
@NSoiffer 

>  if :matrix is only for matrices, what is used for determinants?

I should regenerate with the latest mathcat but at least at some point if you used a `determinant`
 _concept_ on the mrow holding the vertical bars and a matrix _property_ on the mtable then you got

> the determinant of the 2 by 2 matrix; .....

https://w3c.github.io/mathml-docs/intent-examples/#id-0-42f452b821276f28a9e7fabfcf9f5c28

compare with

https://w3c.github.io/mathml-docs/intent-examples/#id-0-07d5bf6d4bb17eb690c44022b3d7a8d2

which uses the determinant concept on the mtable

> the 2 by 2 determinant ....

**Comment by NSoiffer** [comment]
If it says that, it is a bug. But a quick glance at the code shows that it is either saying "determinant" or "matrix" (if... else...), so I don't think it does it now. I need to call it a day, so running a test will have to wait until the morning.

**Comment by davidcarlisle** [comment]
It seemed quite natural to me, I'm not sure why you say it's a bug, the `|..|` gets read as "determinant of", whether the ... is a variable M or an explicit matrix, because of the `determinant` concept, then the argument gets read as "2 by 2 matrix ..." because of the `matrix` property on the mtable.

**Comment by davidcarlisle** [comment]
call of 2024-09-24 decided to call the property `array`  which will cause the `mtable` to be read by rows and columns.
