### ISSUE TITLE
Define the "mrow" algorithm.

### ISSUE THREAD

**Issue by bfgeek** [w3c/mathml#53]
As above.

This needs to define what the layout pass of the algorithm is, as well as the intrinsic sizes pass.

Specific care here needs to be taken with how child margins are handled (if at all).

**Comment by fred-wang** [comment]
Regarding intrinsic sizes, the mpadded element can be problematic: I opened #81

**Comment by fred-wang** [comment]
It's now described

https://mathml-refresh.github.io/mathml-core/#layout-of-mrow

but we need to fix #111

**Comment by fred-wang** [comment]
I think this can be closed now, we have spec details and tests
