### ISSUE TITLE
Define the "mfrac"/(other things that "stack") algorithm.

### ISSUE THREAD

**Issue by bfgeek** [w3c/mathml#54]
As above.

This needs to define the layout pass, and the intrinsic sizes pass.

Special care needs to be taken with margins.
This needs tests.

**Comment by NSoiffer** [comment]
Full list of stacking elements:
* `mfrac` (unless `bevelled="true"`)
* `moverunder`/`mover`/`munder` (not that the limits may decrease in size)
* `mstack` (elementary math)

I don't think the sub and superscript (and multiscript) elements would be considered stacked, but others might disagree.

`mstack` is part of elementary math and probably should expand into a table (with various attrs set). If that's done, each digit belongs in it's own column. This means that it might not be considered a stacking element.

**Comment by fred-wang** [comment]
I don't think we should consider `mstack` in MathML Core: https://github.com/mathml-refresh/mathml/issues/67#issuecomment-469603151

**Comment by fred-wang** [comment]
They are now described in

https://mathml-refresh.github.io/mathml-core/#fractions-mfrac
https://mathml-refresh.github.io/mathml-core/#underscripts-and-overscripts-munder-mover-munderover

However, we need to address #111

**Comment by fred-wang** [comment]
I think this can be closed now, we have spec details and tests
