### ISSUE TITLE
Add tests for dynamic updates to MathML tree.

### ISSUE THREAD

**Issue by bfgeek** [w3c/mathml#57]
The current implementations currently are bugging wrt. paint invaldiations, etc.

There should be a portion of the test-suite which tests these types of invalidation bugs.

This is especially important if MathML diverges from the standard CSS box model (interpreting border/padding/box-sizing/etc) differently, as this is a source of issues for implementations.

----------------------------

Dynamic attributes of MathML elements:
https://mathml-refresh.github.io/mathml-core/#dfn-mathml-attributes
- [x] class ( mathml/relations/html5-tree/dynamic-1.html )
- [x] dir ( mathml/relations/css-styling/dynamic-dir-1.html )
- [x] displaystyle ( mathml/relations/css-styling/displaystyle-013.html )
- [x] id ( mathml/relations/html5-tree/dynamic-2.html )
- [x] mathbackground ( mathml/relations/css-styling/presentational-hints-002.html )
- [x] mathcolor  ( mathml/relations/css-styling/presentational-hints-002.html )
- [x] mathsize  ( mathml/relations/css-styling/presentational-hints-002.html )
- [x] mathvariant  ( mathml/relations/css-styling/presentational-hints-002.html )
- [x] scriptlevel ( mathml/relations/css-styling/presentational-hints-002.html )
- [x] legacy maction's actiontype, selection(no observable behavior) 
- [x] form (mathml/presentation-markup/operators/mo-form-dynamic*.html) 
- [x] fence (no observable behavior)
- [x] separator (no observable behavior)
- [x] style ( mathml/relations/html5-tree/dynamic-2.html )
- [x] lspace (mathml/presentation-markup/operators/mo-lspace-rspace-dynamic.html)
- [x] rspace (mathml/presentation-markup/operators/mo-lspace-rspace-dynamic.html)
- [x] stretchy (mathml/presentation-markup/operators/mo-stretch-properties-dynamic-001.html)
- [x] symmetric (mathml/presentation-markup/operators/mo-stretch-properties-dynamic-001.html)
- [x] maxsize (mathml/presentation-markup/operators/mo-stretch-properties-dynamic-001.html)
- [x] minsize (mathml/presentation-markup/operators/mo-stretch-properties-dynamic-001.html)
- [x] largeop (mathml/presentation-markup/operators/mo-stretch-properties-dynamic-001.html)
- [x] movablelimits (mathml/presentation-markup/operators/mo-movablelimits-dynamic.html)
- [x] mpadded's width height depth lspace voffset ( mathml/presentation-markup/mpadded/mpadded-001.html )
- [x] mspace's width height depth (mathml/presentation-markup/spaces/space-1.html) 
- [x] munderover's accentunder accent (mathml/relations/css-styling/scriptlevel-001.html)
- [x] encoding (no observable behavior)
- [x] display (mathml/relations/html5-tree/display-1.html)
- [x] linethickness ( mathml/presentation-markup/fractions/frac-linethickness-002.html )
- [ ] mtd's columnspan, rowspan => moved to #220 

Dynamic tree of MathML elements:
- [x] annotation ( mathml/presentation-markup/tokens/dynamic-mtext-like-001.html )
- [x] annotation-xml ( mathml/presentation-markup/tokens/dynamic-mtext-like-001.html )
- [x] maction ( mathml/presentation-markup/mrow/dynamic-mrow-like-001.html )
- [x] math ( mathml/presentation-markup/mrow/dynamic-mrow-like-001.html )
- [x] merror ( mathml/presentation-markup/mrow/dynamic-mrow-like-001.html )
- [x] mfrac (mathml/presentation-markup/fractions/frac-created-dynamically*,  mathml/relations/html5-tree/dynamic-childlist-001.html )
- [x] mi ( mathml/presentation-markup/tokens/dynamic-mtext-like-001.html )
- [x] mmultiscripts ( mathml/relations/html5-tree/dynamic-childlist-001.html )
- [x] mn ( mathml/presentation-markup/tokens/dynamic-mtext-like-001.html )
- [x] mo ( mathml/presentation-markup/tokens/dynamic-mtext-like-001.html )
- [x] mover ( mathml/relations/html5-tree/dynamic-childlist-001.html )
- [x] mpadded ( mathml/relations/html5-tree/dynamic-childlist-001.html )
- [x] mphantom ( mathml/presentation-markup/mrow/dynamic-mrow-like-001.html )
- [x] mprescripts ( mathml/presentation-markup/mrow/dynamic-mrow-like-001.html )
- [x] mroot ( mathml/relations/html5-tree/dynamic-childlist-001.html )
- [x] mrow ( mathml/presentation-markup/mrow/dynamic-mrow-like-001.html )
- [x] ms ( mathml/presentation-markup/tokens/dynamic-mtext-like-001.html )
- [x] mspace ( mathml/relations/html5-tree/dynamic-childlist-001.html )
- [x] msqrt ( mathml/relations/html5-tree/dynamic-childlist-001.html )
- [x] mstyle ( mathml/presentation-markup/mrow/dynamic-mrow-like-001.html )
- [x] msub (  mathml/relations/html5-tree/dynamic-childlist-001.html )
- [x] msubsup (  mathml/relations/html5-tree/dynamic-childlist-001.html )
- [x] msup (  mathml/relations/html5-tree/dynamic-childlist-001.html )
- [x] mtable ( mathml/presentation-markup/tables/dynamic-table-001.html )
- [x] mtd ( mathml/presentation-markup/tables/dynamic-table-001.html )
- [x] mtext ( mathml/presentation-markup/tokens/dynamic-mtext-like-001.html )
- [x] mtr ( mathml/presentation-markup/tables/dynamic-table-001.html )
- [x] munder (  mathml/relations/html5-tree/dynamic-childlist-001.html )
- [x] munderover (  mathml/relations/html5-tree/dynamic-childlist-001.html )
- [x] none ( mathml/presentation-markup/mrow/dynamic-mrow-like-001.html )
- [x] semantics ( mathml/presentation-markup/mrow/dynamic-mrow-like-001.html )

Other dynamic tests:
- css visibility: mathml/relations/css-styling/visibility*
- css color: mathml/relations/css-styling/color*
- DOM: mathml/relations/html5-tree/clipboard-event-handlers.tentative.html, mathml/relations/html5-tree/css-inline-style-dynamic.tentative.html, mathml/relations/html5-tree/math-global-event-handlers.tentative.html
- many tests check element properties by creating them dynamically.

**Comment by fred-wang** [comment]
Right, I think it is somewhat controversial whether this is better handled by fuzzing than by conformance tests... Anyway, Gecko and WebKit definitely have this kind of tests and we can import them.

**Comment by fred-wang** [comment]
Just to add more to the discussions, my colleague @rwlbuis pointed out that SVG has some error rules https://www.w3.org/TR/SVG11/implnote.html#ErrorProcessing that implies not displaying some parts of the content. I'm not sure how it is actually implemented in browsers.  

There are also empty elements in MathML like mspace that are not supposed to have any child. I wonder how we should handle them compared to e.g. empty HTML elements. See https://github.com/web-platform-tests/wpt/pull/15722

**Comment by fred-wang** [comment]
This is still work in progress. See the "dynamic" tests listed on https://mathml-refresh.github.io/mathml-core/#dom-and-javascript

**Comment by fred-wang** [comment]
We still need to check whether we have dynamic tests for all the MathML elements and attributes.
Current list is https://mathml-refresh.github.io/mathml-core/#mathml-elements-and-attributes

**Comment by fred-wang** [comment]
I updated the issue description to show the current status. I think we have a relatively good coverage for dynamic tests now. I'm sure we can still improve this but it's probably better to consider specific cases in separate issues.

**Comment by fred-wang** [comment]
For future reference, here is a more recent analysis of dynamic tests (new ones added):
https://bugzilla.mozilla.org/show_bug.cgi?id=1918308#c0

@davidcarlisle can you please transfer this issue to the mathml-core repo.
