### ISSUE TITLE
math-script-level should respect style containment.

### ISSUE THREAD

**Issue by bfgeek** [w3c/mathml#60]
See above. Just so we don't forget :)

**Comment by fred-wang** [comment]
cc @emilio @rwlbuis @mrego @bkardell

@bfgeek Can you please elaborate a bit more about this issue? IIUC, style containment affects selectors that may change things outside the element like counters or quotes. It's true that math-script-level looks like a bit like a counter but it only affects the font-size of the element and its descendants.

**Comment by emilio** [comment]
Yeah, if math-script-level works at computed-value time then it doesn't seem that style containment is applicable. It's more like inheritance than like counters.

**Comment by fred-wang** [comment]
Ian replied:
> Yeah not totally sure - probably just wanted to make sure it wasn't special like counters.

I think this issue can be closed then.
