### ISSUE TITLE
Deprecate/Remove mphantom

### ISSUE THREAD

**Issue by fred-wang** [w3c/mathml#65]
The mphantom element is inspired from LaTeX's \phantom and makes sense in a non-Web context.

In a Web context, it's really equivalent to mrow with `visibility: hidden`, so it's probably not very useful. Let's decide if we want to deprecate/remove it from MathML full/core.

**Comment by NSoiffer** [comment]
That's a good point. It is used (I've used it) for the same reasons it is there in TeX. Since it is used, it should remain in "full", but can go from "core" if we can write a polyfill for it. I assume it would simply turn into the contents wrapped with
 ```  <mrow style="visibility:hidden;"> ... </mrow>```

Maybe the `mrow` isn't even needed? Hopefully none of the children turn `visibility` back on... Any other potential problems?

**Comment by fred-wang** [comment]
Yes, mphantom is implemented in WebKit/Gecko the same way as mrow but with some "visibility: hidden" in the CSS user agent stylesheet.

Indeed users actually don't need to insert an mrow, you can just put "visibility: hidden" on any MathML element to hide a MathML subtree. However, MathML defines mphantom as "mrow-like" (which implies several properties) so polyfills should really rely on mrow in general to keep the current mphantom behavior.

Yes, it's possible to turn visibility back on descendants or on the mphantom itself if the user explicitly change the corresponding CSS style. I don't think that's an issue though? We should give freedom to users to override things if they really want to.

**Comment by fred-wang** [comment]
...and since it is used a lot, I think "Core" should just say it is deprecated for now and recommend the alternative of mrow with "visibility: hidden".

**Comment by NSoiffer** [comment]
I'm baffled by your comment. If something is used with some frequency, we should be _very_ cautious about deprecating it. The full spec is not aimed at just web applications, so saying "use mrow with 'visibility: hidden'" is not practical in environments that lack CSS support.

The full spec will say what is in core and if someone is targeting only browsers, then they may make the decision that they don't want JS running to handle mphantom, but that is an author decision. They may care about more interoperability with non browser applications.

**Comment by fred-wang** [comment]
OK, ignore my last comment then. In any case, I don't care about what is in MathML full as long as what is written in MathML Core remains equivalent to "mrow + visibility: hidden".

**Comment by fred-wang** [comment]
So as I understand the current status is
* Keep it in MathML Core, interpreted as mrow algo + "visibility: hidden"

**Comment by davidcarlisle** [comment]
I think that is good, yes.

**Comment by fred-wang** [comment]
Resolved on 2019/06//03 as in https://github.com/mathml-refresh/mathml/issues/65#issuecomment-472850668
Core spec updated: https://mathml-refresh.github.io/mathml-core/#mphantom
