### ISSUE TITLE
Suggested change to description of merror layout in core spec

### ISSUE THREAD

**Issue by NSoiffer** [w3c/mathml#66]
The [core spec says this](https://mathml-refresh.github.io/mathml-core/#merror) about `merror`:

> The merror element displays its contents as an ”error message”. This might be done, for example, by displaying the contents in red, flashing the contents, or changing the background color.
> 
> For the layout algorithm described in this document, the merror element must be treated the same as the mrow element. The user agent stylesheet must set some CSS properties on the merror element in order to highlight the error. As suggested in section 2.3.2, this can for example be achieved with the rule:
> 
> merror {
>   outline: solid thin red;
>   background-color: lightYellow;
> }

I think it would be useful (and conformant with the HTML5 spec) to indicate what the error is when the content is not a string of text describing the error. This would occur when an `merror` is created because of a content error such as the wrong number of arguments to `msup`. I see two possibilities:
* Use the `tittle` attr so a tooltip comes up that explains the error ("wrong number of args to mfrac", etc).
* Use `aria-describedby` and point off to a description of the error

I prefer the first solution although `tittle` has some accessibility issues. Those will hopefully go away in the future as screenreaders adopt to current standards.

**Comment by fred-wang** [comment]
As I say on https://github.com/mathml-refresh/mathml/issues/15#issuecomment-469589832 I don't think we should rely on merror's rendering to indicate invalid markup. Also report of errors is generally done via the developer console.

Finally, I guess you are right that maybe merror is not in core, I opened w3c/mathml#70 ; if merror stays in core, then I would oppose any additional complexity (I don't understand where the attributes you suggest are coming from? users? generated?). Even the current suggested rendering might not work until we clarify w3c/mathml#9

**Comment by fred-wang** [comment]
I think this is something for an "invalid markup" polyfill, so adding the label

**Comment by davidcarlisle** [comment]
Closing as no change needed.
