### ISSUE TITLE
mpadded: prohibit vertical pseudo-units in horizontal attributes

### ISSUE THREAD

**Issue by fred-wang** [w3c/mathml#81]
cc @rwlbuis, @emilio

mpadded support pseudo-units https://mathml-refresh.github.io/mathml/chapter3.html#presm.mpaddedatt which allows width to depend on vertical metrics like this:

    <mpadded width="200%height">

This is causing issue for calculating intrinsic width. I propose to add a restriction and to disallow vertical pseudo-units (height, voffset, depth) in horizontal attributes (lspace, width). Probably worth adding in #55 too

**Comment by rwlbuis** [comment]
AP: contact Brian Kardell about this. Since I don't think he can be referenced here directly, I'll ping him internally through the Igalia infrastructure.

**Comment by rwlbuis** [comment]
Brian, I briefly looked into the above case where width depends on height. I thought of CSS calc, it can use vw/vh, but that is not quite the same. Can you think of some way to do this that would make the mpadded pseudo units unneeded?

**Comment by rwlbuis** [comment]
After discussing with Brian, he mentioned the upcoming aspect-ratio CSS property should fix the "set width using height" and "set height using width" problems:
https://www.smashingmagazine.com/2019/03/aspect-ratio-unit-css/
https://drafts.csswg.org/css-sizing-4/#ratios

**Comment by rwlbuis** [comment]
Note that aspect-ratio would not know about height/depth attributes/concepts as specified for mpadded, it would just know about content width and height.

**Comment by fred-wang** [comment]
cc @distler

These are the possible non-length values that can be generated by itex2MML or TeXZilla: 
lspace="-100%width" (\mathllap)
lspace="-50%width" (\mathclap)
height="+[LENGTH][UNIT]" (\mathraisebox)
depth="+[LENGTH][UNIT]" (\mathraisebox)
depth="depth" (\mathraisebox)

**Comment by fred-wang** [comment]
We agreed to prohibit vertical pseudo-units in horizontal attributes and horizontal pseudo-units in vertical attributes during meeting from 10/06/2019.

**Comment by fred-wang** [comment]
The core spec no longer refers to MathML 3 for the mpadded syntax and pseudo-units have been restricted:
https://mathml-refresh.github.io/mathml-core/#adjust-space-around-content-mpadded

**Comment by fred-wang** [comment]
tests added
