### ISSUE TITLE
Add a list of ideas for people willing to contribute

### ISSUE THREAD

**Issue by fred-wang** [w3c/mathml#82]
@physikerwelt raised that during the initial meeting.

Here is a list of random ideas:

  * Participate to the survey: #55
  * Write polyfills for non-Core features: https://github.com/mathml-refresh/mathml-polyfills
  * Experiment CSS/HTML/MathML-Core polyfills (mglyph, tables, elementary math) so we can take decision about what to propose.
  * Write WebExtensions for browsers (e.g. polyfills, check non-core features etc)
  * WHATWG/W3C validators for new mathml schemas?
  * Write/Review WPT tests for MathML Core?

**Comment by briansmith** [comment]
FWIW, I would be willing to help with doing some (pure) CSS-based polyfilling if others would agree to implement `math-script-level` and `font-feature-settings: 'ssty' 1` in their CSS implementations. This is the biggest blocker for my current (private) polyfill efforts. In particular, my `<msup>` and `<msub>` polyfills don't use the right glyphs in math fonts without these features.

**Comment by fred-wang** [comment]
@briansmith That would be great. `font-feature-settings: 'ssty' 1` should already be supported in browsers. Regarding `math-script-level`, this is currently on Igalia's list for the Chromium implementation.

**Comment by NSoiffer** [comment]
The topic of including polyfills in the MathML Full spec to show how to make use of MathML came up in the MathML Full meeting today. That is what let me to this old issue.

I believe that the state of MathML core is that are `math-style` (`compact`/`normal`) and `math-level` that are exposed. The names were changed from the original proposal after discussion with some CSS group members and others. The MathML attrs `displaystyle` and `scriptlevel` map to these CSS values. @fred-wang can correct me if I have this wrong.

@briansmith: does this solve your problem. Note that polyfills exists for many MathML full features. They are located at https://github.com/mathml-refresh/mathml-polyfills. I'm sure they can be improved -- a big problem is finding a good target for them they transform into (you want to use as much of MathML Core as possible). There are still a few features that need polyfills if you are still interested in working on them.

I think the other issues listed in the initial issue are dealt with and this can be closed. Any objections to closing this?

**Comment by NSoiffer** [comment]
No objections to closing were raised, so I'm closing this.
