### ISSUE TITLE
Deprecate/Remove the mstyle element

### ISSUE THREAD

**Issue by fred-wang** [w3c/mathml#89]
I think we already agreed that we should keep mstyle in core as it is widely used. However, it was proposed to deprecate it in favor of mrow: https://github.com/mathml-refresh/mathml/issues/1#issuecomment-473416390

To do that, we would first need to allow all mstyle attributes on mrow ; see #88

**Comment by fred-wang** [comment]
From https://lists.w3.org/Archives/Public/public-mathml4/2019Apr/0022.html ; "Neil: suggests removing mstyle from core."

I don't remember what was the resolution from previous meeting, but as I already said from the implementer side it's easy to just make mstyle use the same C++ classes as mrow for layout purpose and to map DOM attributes to CSS properties. So it's not really useful to remove it (for browser implementers).

From https://github.com/mathml-refresh/mathml/issues/55 it seems mstyle is still used a lot so I would keep in in Core. As Dani said in https://github.com/mathml-refresh/mathml/issues/1#issuecomment-473416390 we can deprecate it in Full and suggest mrow instead. #88 would be needed first (or at least allow mstyle attributes on mrow).

**Comment by NSoiffer** [comment]
Doesn't appear that anything remains to be done. Treated as mrow.
