### ISSUE TITLE
Ensure good integration of MathML with the accessibility tree

### ISSUE THREAD

**Issue by littledan** [w3c/mathml#9]
@joanmarie has noticed some issues here with respect to the current MathML/accessibility integration. I'll defer to her for details, but it will take time to gather the relevant information. Filing this issue so people remember to come back to it.

**Comment by fred-wang** [comment]
Asking to Joanie, this can be closed and handled somewhere in other issues. We have https://github.com/mathml-refresh/mathml/issues/64 for example, and other semantics discussion happening in the MathML CG and other groups.
