### ISSUE TITLE
Make display:contents map to display:none 

### ISSUE THREAD

**Issue by fred-wang** [w3c/mathml#90]
cc @rwlbuis @bkardell @mrego @emilio

From https://drafts.csswg.org/css-display/#unbox-mathml

> For all MathML elements, display: contents computes to display: none.

TODO: check the implementation status in webkit/firefox and write tests for these.
Rob did https://github.com/Igalia/chromium-dev/commit/177eb951392219339c47526c65c1789439a1d6b0

**Comment by fred-wang** [comment]
Probably we can also add a note in the core spec, pointing to https://drafts.csswg.org/css-display/#unbox-mathml

**Comment by emilio** [comment]
It should be working in Gecko AFAICT: https://searchfox.org/mozilla-central/rev/11cfa0462a6b5d8c5e2111b8cfddcf78098f0141/servo/components/style/style_adjuster.rs#127

**Comment by fred-wang** [comment]
Thanks  @emilio , yes I think I saw this code recently :-)
Adding the rules in WebKit/Chromium and writing a WPT test should be easy.

**Comment by fred-wang** [comment]
Spec update: https://github.com/mathml-refresh/mathml-core/commit/d4bb13a46889ea24ef5a184609c044bfed507d31

**Comment by Jamesernator** [comment]
Any chance of getting a dedicated mathml element that functions like `display: contents;`? Currently there's no way to group elements (e.g. within a `<mrow>`).

e.g.:

```html
<mrow>
  <!-- Would have styles effectively like display: contents -->
  <mgroup id="energyTerm">
    <mi>E</mi>
  </mgroup>
  <mo>=</mo>
  <mgroup id="resultTerm">
    <mi>m</mi>
    <mo>&InvisibleTimes;</mo>
    <msup>
      <mi>c</mi>
      <mn>2</mn>
    </msup>
  </mgroup>
</mrow>
```

**Comment by fred-wang** [comment]
@Jamesernator In the short term, I personally don't think we are going to introduce new MathML elements in MathML Core since the goal is to try to find a core subset to implement in browsers.  We are doing more css compat work, so maybe we could reopen the discussion in the future about `display: contents` (https://github.com/w3c/csswg-drafts/issues/2167) if there are concrete/important use cases for it. It's not obvious to why it's needed in your example, using an explicit mrow is a better grouping (resultTerm) or equivalent to the element alone (energyTerm).

**Comment by Jamesernator** [comment]
The example isn't very good I just wanted to be short, this is a better example:

```html
<!doctype html>

<style>
  #container {
    border: 1px solid grey;
    width: 100px;
  }

  #firstTerm:hover {
    color: green;
  }

  #restOfSeries:hover {
    color: blue;
  }
</style>

<div id="container">
  <math>
    <mn id="firstTerm">1</mn>
    <mo>+</mo>
    <mgroup id="restOfSeries">
      <mi>A</mi>
      <mo>+</mo>
      <msup>
        <mi>A</mi>
        <mi>2</mi>
      </msup>
      <mo>+</mo>
      <msup>
        <mi>A</mi>
        <mi>3</mi>
      </msup>
      <mo>+</mo>
      <msup>
        <mi>A</mi>
        <mi>4</mi>
      </msup>
      <mo>+</mo>
      <mi>...</mi>
    </mgroup>
  </math>
</div>
```

This can't be replaced with `<mrow>` because `<mrow>` does not break when there's insufficient space.

e.g. With an `<mgroup>` suggested element or `display: contents` on something it'd look like:

<img width="115" alt="Screen Shot 2019-08-26 at 6 19 45 pm" src="https://user-images.githubusercontent.com/8518303/63676391-2ff2c180-c82e-11e9-9c10-1e3c0c477e3d.png">

But trying to use `<mrow>` for this doesn't work because it doesn't break:

<img width="182" alt="Screen Shot 2019-08-26 at 6 21 41 pm" src="https://user-images.githubusercontent.com/8518303/63676476-5f093300-c82e-11e9-9e1e-434f0f6a3cd6.png">

**Comment by fred-wang** [comment]
@Jamesernator OK, I guess you are testing in Gecko? Ideally linebreaking should be improved and supported in any mrow, so you won't need such an mgroup element ( w3c/mathml-core#127 ). But defining a full linebreaking is going to be tricky so it's also postponed for later until we sort out the other issues...

**Comment by Jamesernator** [comment]
> OK, I guess you are testing in Gecko?

Yes. I had looked for `overflow: linebreak` in the mathml core spec but couldn't find it so I supposed it had been removed, didn't notice the "Define MathML line breaking?" boxes.

**Comment by NSoiffer** [comment]
The MathML 3 spec has a section on linebreaking:  https://www.w3.org/TR/MathML3/chapter3.html#presm.linebreaking. As @fred-wang said, it is not well supported in Gecko and other places. I suspect we will revisit linebreaking for core to see what can be done to make it easier to implement, but that's a lower priority item.

**Comment by fred-wang** [comment]
Tests:

https://w3c-test.org/mathml/relations/css-styling/display-contents.html
https://w3c-test.org/mathml/relations/css-styling/not-participating-to-parent-layout.html
