### ISSUE TITLE
OpenType MATH values for menclose notations 

### ISSUE THREAD

**Issue by fred-wang** [w3c/mathml#97]
Just converting OpenType MATH appendix into github issues:

> In section 3.3.8 we describe the MathML menclose element. This one contains many notations that are not mentioned in the OpenType MATH specification. Some rendering suggestions are given based on the value of OverbarRuleThickness but perhaps new values should be introduced in the MathConstants subtable to cover these notations.

**Comment by NSoiffer** [comment]
As far as I can tell, this contains the only reference to a TeX value (ξ8 -- rule thickness) in the core spec. I agree it would be good to change this to an OpenType MATH spec value. Looking at the OpenType spec, there are several values with descriptions that include "Suggested: default rule thickness", but I don't see a value for rule thickness. Did I miss something?

**Comment by fred-wang** [comment]
> Looking at the OpenType spec, there are several values with descriptions that include "Suggested: default rule thickness", but I don't see a value for rule thickness. Did I miss something?

AFAIK, the default rule thickness is not defined. The current mathml core spec says ξ8  is OverbarRuleThickness. In any case all the menclose parameters are more or less arbitrary as they are no direct equivalent in OpenType MATH.

**Comment by fred-wang** [comment]
merged into https://github.com/mathml-refresh/mathml/issues/216
