### ISSUE TITLE
Is schemas.xml needed?

### ISSUE THREAD

**Issue by fred-wang** [w3c/mathml#98]
@davidcarlisle Can we remove this file: https://github.com/mathml-refresh/mathml-core/blob/master/schemas.xml ? It does not seem to be used in the core repo.

**Comment by davidcarlisle** [comment]
Ah it is supposed to be mapping files to the relax ng schema that they
should match see the one in

mathml/src/xml/schemas.xml

but the one in core is just a stub with nonsense values, it looks like it
was not updated as we evolved the source files from the tex originals.

If I was editing or checking the files I'd want a file there (emacs uses it
for example) but I could always have a local gitignored one if others don't
find it useful.

I will delete the one that is there in any case.
